Step01
next-step/js-lotto pull request #131
Opened 2022-07-10 11:19 UTC by J-Ymini

step01 리뷰 부탁드립니다!

- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x]  소비자는 자동 구매를 할 수 있어야 한다.
- [x]  복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.
- [x]  위 기능들이 정상적으로 동작하는지 Cypress를 이용해 테스트한다.

2022-07-12 16:42 UTC, thenewpark requested changes
용민님 안녕하세요~! 로또 미션의 리뷰어로 함께하게 된 리뷰어 박신영입니다. 
코드 라인에 코멘트 남겨두었으니 확인 부탁드릴게요!     
이번 스텝에서 반영하지 않으시더라도 대부분 이후 미션을 진행하실 때에도 공통으로 적용될만한 부분이라 참고해주시면 될 것 같습니다 🙂     

MVC라면... MVC 구조를 도입해보고 싶으셨던 이유가 있으실까요?      
저는 이번 미션이 MVC와 같은 패턴을 적용하지 않아도 충분히 구현할 수 있다고 생각하는데요..!    
용민님께서 필요를 느끼신 게 아니라면 일부러 적용하실 필요는 없을 것 같습니다 🤔     
우선 로또라는 도메인 데이터, 비즈니스 로직을 담고 있는 파일과 View 로직을 담고 있는 파일을 더 명확하게 구분해보는 것부터 시작해보시면 어떨까요? 🙂   

모든 미션에서 그렇듯이 모든 피드백을 반영하셔야 하는 것은 아니니 
피드백 확인해주시고, 자유롭게 반영해보신 뒤에 다시 리뷰 요청 주셔요!       
혹은 다음 스텝에서 이어서 반영해보고 싶으시다면 그것도 코멘트로 알려주셔요, 저도 머지 후에 다음 스텝에서 이어서 확인하겠습니다 🙏 

고생 많으셨습니다~!

2022-07-12 16:42 UTC, thenewpark commented on cypress/integration/lotto.spec.js
> +// 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.
테스트 케이스를 작성하실 때 참고하실 용도로 옮겨두신 것이겠지요? 🙂 
의미를 담은 주석이 아니라면 커밋하기 전에 한번씩 확인해서 지우기를 권장드립니다~!

2022-07-12 16:42 UTC, thenewpark commented on cypress/integration/lotto.spec.js
> +    purchaseButton().click();
type하는 것, click 하는 것까지를 하나의 동작으로 보고 custom command로 만들어보면 어떨까요? 
https://docs.cypress.io/api/cypress-api/custom-commands 
```js
insertMoney('7000'); 
purchase();
```
요런 식으로 조금 더 사용자 동작에 가깝게 읽히는 E2E 테스트 코드를 작성할 수 있지 않을까 해서요! :)

2022-07-12 16:42 UTC, thenewpark commented on index.html
> +              <label class="flex-auto my-0 purchased-lotto-alert">총 0개를 구매하였습니다.</label>
언뜻 `alert`이라는 이름이 오류 텍스트를 표현하는 것처럼 읽혔는데, 용민님 의견은 어떠신가요?

2022-07-12 16:42 UTC, thenewpark commented on src/css/index.css
> +  font-size: 1.25rem;
px과 rem 단위를 사용하시는 기준이 있으실까요?

2022-07-12 16:42 UTC, thenewpark commented on cypress/integration/lotto.spec.js
> +      expect(text).to.equal('1,000원부터 입력이 가능합니다.');
상수 선언도 잘 해주셨으니, 테스트 코드에서도 프로덕션 코드에서 사용하는 상수를 동일하게 가져와서 사용하면 어떨까요?    
메시지가 변경되면 사실 정상 동작인데도 테스트 케이스가 깨지고,     
무엇때문에 깨지는지 한번 더 들여다보게 되는 문제가 있는 경우가 많아서요 🙏

2022-07-12 16:42 UTC, thenewpark commented on cypress/integration/lotto.spec.js
> +  it('로또 1장의 가격은 1,000원이다.(1,000원 이하로 금액을 입력할 경우)', () => {
테스트 명세를 함수의 이름과 비슷하다고 생각해보시면 어떨까요~?    
요 명세가 테스트 하는 내용을 잘 설명해주는 내용일까요?

2022-07-12 16:42 UTC, thenewpark commented on cypress/integration/lotto.spec.js
> +      expect(item).to.have.css('display', 'none')
E2E 테스트이니만큼 요런 구체적인 구현 사항을 테스트 대상으로 삼기보다     
'해당 엘리먼트가 사용자 눈에 보이는지 안보이는지'를 테스트할 것을 권장드립니다.     
display 속성으로 제어하지 않도록 수정할 수도 있고, 그렇게 되면 정상 동작인데도 테스트만 깨지게 되니까요    
- https://docs.cypress.io/guides/references/assertions#Text-Content > visibility, existence 등의 assertion을 참고해보셔도 좋을 것 같아요

2022-07-12 16:42 UTC, thenewpark commented on src/js/constants.js
> +  LOTTO_UNIT: 1000,
가격의 단위이니 `PRICE`도 붙여주면 어떨까요?

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +const generateRandomLottoNumber = () => Math.floor(Math.random() * 45) + 1;
상수화 잘해주셨으니 요런 45같은 숫자도 매직넘버로 남겨두지 말고 상수를 활용해보면 어떨까요?

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +const generateLottoTicket = (lottoCount) => {
오우 요 함수의 크기가 꽤 큰데요! 
아래 사항들을 고려해서 조금 더 작은 단위로, 간결하게 수정해볼 수 있을까요?-? 
- 가능하다면 for문보다는 Array 내장 메서드를 활용
- 함수 하나가 하나의 역할만 할 수 있게

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +    $('.lotto-result-list').appendChild(newListItem);
반복문을 돌 때마다 매번 새로 DOM 셀렉팅 + DOM 삽입이 일어나게 될 것 같은데요..!      
요런 값비싼 작업은 반복문에서 여러번 일어나게 하기보다는 한번에 모아서 하게 바꿔볼 수 있을까요? 🙂

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +    newListItem.appendChild(listOfLottoNumber);
append와 appendChild api를 함께 찾아보셔도 좋을 것 같아요 🙂

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +    Number($('.price-input').value) / LOTTO_INFORMATION.LOTTO_UNIT;
소수점에 대한 대응이 필요하지 않을까 싶은데, 어떠신가요?

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +const getPurchasedLottoResult = () => {
`get~`이라는 이름을 가지고 있다면 이름대로 `purchasedLottoResult`를 return해줄 거라 기대할 수 있을 것 같은데 어떻게 생각하시나요..! 
네이밍에 대한 용민님 의견이 궁금합니다 🙏

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +  for (let i = 0; i < $$('.purchased-lotto-result-view').length; i++) {
- 요기도 반복문보다 Array 메서드를 활용해볼 수 있지 않을까요?    
- 반복문을 돌 때마다 DOM 셀렉팅이 일어나는데요, 요것도 DOM에 접근하는 것을 최소화할 수 있을까요?

2022-07-12 16:42 UTC, thenewpark commented on src/js/getLottoResult.js
> +    $$('.purchased-lotto-result-view')[i].style.display = 'block';
가능하면 스타일은 css에서 책임질 수 있게 하면 좋을 것 같은데 어떠신가요?     
스타일을 적용하는 것이 css에도 있고 js에도 있다면 이후 유지보수를 할 때에 수정이 어느쪽에서 일어나고 있는지 헷갈릴 수 있을 것 같아요 :) 기본적으로 관심사 분리 측면에서도 구분해서 사용하는 게 맞을 것 같고요.

2022-07-12 16:42 UTC, thenewpark commented on src/js/handleLottoNumbersToggle.js
> +  $('.lotto-result-list').classList.add('flex-col');
반복해서 사용되는 곳이 많은 셀렉터같은데, 요런 것도 상수화해두어도 괜찮지 않을까요?    
휴먼 에러 방지차..!

2022-07-12 16:42 UTC, thenewpark commented on src/js/purchaseLotto.js
> +  while ($('.lotto-result-list').firstChild) {
DOM 구조에 의존하는 로직은 DOM 구조가 변경되면 깨지기 쉬운데요!     
DOM 구조를 변경해도 문제가 없도록 수정해보면 어떨까요?

2022-07-12 16:42 UTC, thenewpark commented on src/js/purchaseLotto.js
> +    $('.price-input').value % LOTTO_INFORMATION.LOTTO_UNIT !== 0
조건식이 길어지는 경우 의미를 파악하기 위해 매우 주의깊게 읽어야할 수 있을 것 같아요. 
https://github.com/qkraudghgh/clean-code-javascript-ko#%EC%A1%B0%EA%B1%B4%EB%AC%B8%EC%9D%84-%EC%BA%A1%EC%8A%90%ED%99%94-%ED%95%98%EC%84%B8%EC%9A%94 요런 내용을 참고해보시면 좋을 것 같습니다!

2022-07-14 15:33 UTC, J-Ymini commented on index.html
> +              <label class="flex-auto my-0 purchased-lotto-alert">총 0개를 구매하였습니다.</label>
음, 저는 alert이라는 뜻 그대로, 구입된 로또를 알리기 위해 해당 클래스 네임을 선택하였습니다! 만일 수정한다면 어떤 키워드를 선택하는 것이 보다 적절할까요?(notice 도 적절해보이는것 같습니다!)

2022-07-14 15:46 UTC, J-Ymini commented on cypress/integration/lotto.spec.js
> +    purchaseButton().click();
오.. custom commands를 적용하니 훨씬 가독성이 좋아진 것 같습니다! 감사합니다 ㅎㅎ

2022-07-15 05:18 UTC, J-Ymini commented on src/css/index.css
> +  font-size: 1.25rem;
lotto repository의 `src > css > shared > typhography.css` 폰트가 rem으로 지정되어 있어서, 추가로 스타일링을 rem으로 지정하였습니다!

2022-07-15 05:23 UTC, J-Ymini commented on cypress/integration/lotto.spec.js
> +      expect(text).to.equal('1,000원부터 입력이 가능합니다.');
넵 좋은 방법인것 같습니다! :)

2022-07-15 05:28 UTC, J-Ymini commented on cypress/integration/lotto.spec.js
> +  it('로또 1장의 가격은 1,000원이다.(1,000원 이하로 금액을 입력할 경우)', () => {
해당 테스트는, 1000원 이하의 금액 입력시 alert을 체크하도록  작성하였습니다만, 이러한 경우 테스트 명세를 수정하면 좋을까요?(
설명해주신 내용이 잘 이해가 가지 않는것 같아, 다시 한번 설명해주시면 감사하겠습니다 ㅎㅎㅎ.. ㅠㅠ
)

2022-07-15 05:39 UTC, J-Ymini commented on cypress/integration/lotto.spec.js
> +      expect(item).to.have.css('display', 'none')
넵 확인하였습니다. 해당 엘리먼트의 visible 유무로 케이스를 짜니, 가독성 측면에서도 훨씬 더 나은것 같습니다! :)

2022-07-15 05:40 UTC, J-Ymini commented on src/js/getLottoResult.js
> +const generateRandomLottoNumber = () => Math.floor(Math.random() * 45) + 1;
넵! 이 부분은, 제가 상수로 따로 빼놓았는데 활용을 하지 않았었네요 ㅎㅎ.. 감사합니다!

2022-07-15 05:52 UTC, J-Ymini commented on src/js/getLottoResult.js
> +    Number($('.price-input').value) / LOTTO_INFORMATION.LOTTO_UNIT;
`getPurchasedLottoResult`의 함수를 실행할 때, `purchaseLotto.js`에서 해당 금액이 1000원 단위인지 먼저 체크했기에 따로 소숫점에 대한 대응은 하지 않았습니다!. 혹시 이 부분은 어떤식으로 바꿔보면 좋을까요~?

2022-07-15 06:03 UTC, J-Ymini commented on src/js/getLottoResult.js
> +    $$('.purchased-lotto-result-view')[i].style.display = 'block';
이러한 경우, 선택된 dom의 스타일링을 직접 지정해주기보다는 className의 add/remove가 더 적합할까요~?

2022-07-15 06:30 UTC, J-Ymini commented on src/js/handleLottoNumbersToggle.js
> +  $('.lotto-result-list').classList.add('flex-col');
앗! 그렇군요 ㅎㅎ :)

2022-07-15 06:47 UTC, J-Ymini commented on src/js/getLottoResult.js
> +        currentLottoCount += 1;
아 동일한 데이터의 중복이 일어나는군요!! 확인했습니다 :)

2022-07-15 07:29 UTC, J-Ymini commented on src/js/getLottoResult.js
> +const generateLottoTicket = (lottoCount) => {
넵! Array 내장 메서드 사용, 함수 역할 분리 모두 적용하여 수정해보았습니다 :)

2022-07-15 07:30 UTC, J-Ymini commented on src/js/getLottoResult.js
> +    $('.lotto-result-list').appendChild(newListItem);
넵! 반복적으로 DOM을 건드려 요소를 추가하는 방식보다는 , 한번에 추가하는 방식으로 바꿔보았습니다!

2022-07-15 07:36 UTC, J-Ymini commented on src/js/getLottoResult.js
> +  for (let i = 0; i < $$('.purchased-lotto-result-view').length; i++) {
넵! 말씀하신 두 부분 수정해보았습니다 :)

2022-07-15 07:38 UTC, J-Ymini commented on src/js/getLottoResult.js
> +const getPurchasedLottoResult = () => {
함수의 네이밍의 경우, 제가 깊이 고려하지 않고 작성한 듯 싶습니다..! 
말씀하신대로 함수에 `get` 이 붙을 경우, 특정 값을 반환해야 하는 것이 문맥상 더욱 적절해보입니다..!

2022-07-15 08:29 UTC, J-Ymini commented on src/js/purchaseLotto.js
> +  while ($('.lotto-result-list').firstChild) {
넵, 우선 말씀하신 대로 수정해보았습니다만, 제가 맞게 수정했는지 피드백 주시면 감사하겠습니다!(제가 이해한게 맞는지.. 확인하고자 합니다!)

2022-07-15 08:54 UTC, J-Ymini commented on src/js/purchaseLotto.js
> +    $('.price-input').value % LOTTO_INFORMATION.LOTTO_UNIT !== 0
넵 참고하도록 하겠습니다 :)

2022-07-15 08:55 UTC, J-Ymini commented
신영님 안녕하세요!
꼼꼼한 리뷰 감사합니다 ㅎㅎ :)
리뷰해주신 내용 최대한 반영해보려고 했습니다..! 중간중간 제가 이해를 못한 부분들도 있을텐데, 확인해주시고 피드백주시면 감사하겠습니다!

2022-07-17 11:04 UTC, thenewpark commented on index.html
> +              <label class="flex-auto my-0 purchased-lotto-alert">총 0개를 구매하였습니다.</label>
아하 저는 `window.alert()` 이 에러 상황에서 쓰이고 있다보니 조금 더 오류와 관련된 키워드로 생각하게 되었던 것 같아요 :)      
수정한다면 말씀해주신 것처럼 'notice'나, 혹은 'info', 'message' 같은 키워드를 사용해볼 수도 있지 않을까요?

2022-07-17 11:04 UTC, thenewpark commented on src/css/index.css
> +  font-size: 1.25rem;
아하 용민님이 새로 작성해주신 부분에서 rem과 px이 함께 사용되고 있길래, 
경우에 따른 기준이 있으실지 궁금해서 남겨보았습니다!

2022-07-17 11:07 UTC, thenewpark commented on cypress/integration/lotto.spec.js
> +  it('로또 1장의 가격은 1,000원이다.(1,000원 이하로 금액을 입력할 경우)', () => {
아 네네! 말씀해주신 것처럼 alert을 체크하는, 에러 케이스에 대한 테스트인데 고런 부분이 명세만 보았을 때는 잘 알 수 없을 것 같아 코멘트 남겨보았습니다 🙂      
**'(사용자가) 1000원보다 작은 금액을 입력한 경우, 에러 메시지가 뜨고 구매할 수 없어야 한다'** 와 같은 명세라면 실제로 테스트 케이스에서 확인하는 대상과 명세가 조금 더 일치하지 않을까요?

2022-07-17 11:09 UTC, thenewpark commented on src/js/getLottoResult.js
> +    $$('.purchased-lotto-result-view')[i].style.display = 'block';
넵 저는 스타일을 직접 지정하는 것은 css의 역할이고, 가능하면 js에서는 className의 add/remove 정도로 제어하는 것이 관심사 분리 측면에서 필요하다고 생각합니다..!

2022-07-17 11:19 UTC, thenewpark commented on src/js/purchaseLotto.js
> +  while ($('.lotto-result-list').firstChild) {
아 `firstChild`부분이 조금 우려되어 코멘트 드렸었는데요..! 🙂    
스타일링을 위한 DOM이 추가될 수도 있고, 구조가 변경될 수도 있으니 firstChild와 같이 DOM 순서에 의존적이라면 DOM을 수정했을 때 예상치못하게 앱의 로직 자체가 깨질 수 있을 것 같아서요.      
가능하면 별도의 셀렉터를 지정하거나, 생각하시는 다른 방법 중 firstChild 없이 적용할 수 있는 방법이 있다면 step2에서 적용해보시면 어떨까요~?

2022-07-17 11:24 UTC, thenewpark approved these changes
용민님 안녕하세요~! 수정해주신 부분 잘 확인하였습니다 👏👏👏👏👏     
추가로 질문 남겨주신 부분들은 코멘트에 답변 남겨두었고,     
수정해보실 부분은 step2에서 반영해주시면 함께 확인하겠습니다!          

그럼 step2에서 뵙겠습니다!

2022-07-17 11:24 UTC, merged