[클린코드 3기] 이지수 로또 미션 STEP 1
next-step/js-lotto pull request #136
Opened 2022-07-12 11:00 UTC by jisoo-log

여러가지 자괴감이 느껴지는 과제제출입니다 ㅎㅎ
코드가 돌아는 가는데 정말 우아하지 않게 돌아가는 느낌이네요.
리액트로 짜면 어떻게 짜야겠다 생각이 드는데 Vanilla JS 는 정말 어떻게 다뤄야 하는지 처음부터 끝까지 하나도 모르겠네요.. html, css, js 공부를 제대로 안하고 react 를 무작정 시작하면 이렇게 할줄아는게 없구나 싶습니다.

하면서 궁금했던 부분 
- 확인을 누른 후에 로또 관련된 내용이 나오는건 조건부 랜더링밖에 안떠오르는데 Vanilla JS는 어떻게 컨트롤하는지
- 이 다음스텝에 가면 결국 상태관리가 필요해질것 같은데 Vanilla JS는 어떻게 컨트롤 하는지..
- UI와 로직의 분리는 어떻게 시작을 해야할지..
- TDD를 해보려했는데 그 로또를 계산하고 만들고서 화면에 보여주는 부분에서 갑자기 개발해야할 분량이 확 많아지면서 끊기게 되었는데 어떻게 하면 조금씩 끊어서 할 수 있었을지?

일단 어떻게든 제출은 했으니 다른분들 코드 많이 참고해서 수정해보겠습니다 ㅜㅜ

2022-07-12 17:05 UTC, yujo11 requested changes
안녕하세요 지수님! 로또 미션 함께 하게 된 조윤호입니다! 

코드 보는데 전혀 어려움이 없었습니다! 자괴감 안 느끼셔도 될거 같아요

> 확인을 누른 후에 로또 관련된 내용이 나오는건 조건부 랜더링밖에 안떠오르는데 Vanilla JS는 어떻게 컨트롤하는지

이미 잘 하고 계신거 같습니다! React에서 State의 변화에 따라 컴포넌트 등을 조건부로 렌더링 하는것처럼 VanillaJS에서도 똑같이 하시면 됩니다! (다만 React처럼 편하게는 안 되겠지만요 ㅎㅎ...)

> 이 다음스텝에 가면 결국 상태관리가 필요해질것 같은데 Vanilla JS는 어떻게 컨트롤 하는지..

"어떻게"라고 하기에는 다양한 방법들이 있을거 같은데요. 지수님이 생각하시는 방식으로 시도해보시면 좋을거 같습니다!

>UI와 로직의 분리는 어떻게 시작을 해야할지..
코드를 보면 이미 시도를 하고 계신거 같은데요. 지금과 같은 방식으로 하셔도 무방하실거 같습니다

>TDD를 해보려했는데 그 로또를 계산하고 만들고서 화면에 보여주는 부분에서 갑자기 개발해야할 분량이 확 많아지면서 끊기게 되었는데 어떻게 하면 조금씩 끊어서 할 수 있었을지?

정확히 어떤 부분에서 끊기게 되었는지는 잘 모르겠네요ㅠㅠ 

다만 어떤 어려움이 있었을지는 짐작이 가는데요. 한번에 개발하는 모든 분량을 테스트하기가 어렵다면 점진적으로 테스트를 작성해 나가셔도 좋을거 같습니다!

아래처럼 테스트를 작성하시고 실패하는 테스트들이 성공하도록 점진적으로 기능을 개발해보시면 좋을거 같네요!

- 로또를 구입했을 때
  - 구매한 로또 개수를 보여준다.
  - 구매한 로또 개수만큼 로또 아이콘을 보여준다..
  - ....


미션 진행하느라 고생 많으셨습니다 지수님! 리뷰 및 코멘트 확인하고 다시 리뷰요청 부탁드리곘습니다!

2022-07-16 13:38 UTC, jisoo-log commented on cypress/integration/test/test.spec.js
> +    cy.get('.lotto-numbers-toggle-button').click({ force: true });
Command 사용하도록 수정했습니다 :)

2022-07-16 13:39 UTC, jisoo-log commented on cypress/integration/test/test.spec.js
> +  });
넵 막상 작성할때는 생각 못했던 부분인데 고치면서 저도 정리가 되는 기분이네요 ㅎㅎ 감사합니다.

2022-07-16 13:43 UTC, jisoo-log commented on src/js/validate/money.js
> +};
앗 return 바로 할 수 있는거 회사에서도 지적 많이 받던 부분인데 또 이렇게 썼었네요..
음 이전에 계산기 코드에서 다른분들이 짠걸 보다보니 validate 를 모듈로 나눠서 하는 경우를 봐서요. 뭔가 최대한 쪼개고 싶은데 제가 기준을 잡기 어렵다 보니 따라해봤습니다 ㅎㅎ 로직중 true, false로 검증하는 부분을 모아두려 했던건데 좀 의미없어진것 같기도 하네요.

2022-07-16 13:49 UTC, jisoo-log commented on src/js/view.js
> +const template = `
이유는 없고 잘 몰라서 그렇습니다 ㅎㅎㅎㅎㅎ
자바스크립트로 DOM을 직접 수정해본적이 없다보니, 이것저것 검색하다가 찾은 createElement를 무작정 썼습니다.
동적으로 만들때는 CreateElement, 정적으로 그냥 넣을때는 Template literal을 더하면 되겠다하고 혼자 이상하게 이해하고 맘대로 작성한 것 같습니다. 그런데 저번 수업때 강사님이 이렇게 하면 안된다고 엄청! 강조하셔서 최대한 Template literal 활용하는 방향으로 수정해봤습니다.

2022-07-16 13:50 UTC, jisoo-log commented on src/js/lotto.js
> +    if (lotto.length === 6) break;
앗 이부분도 부끄럽네요 ㅎㅎ 수정했습니다

2022-07-16 14:06 UTC, jisoo-log commented
@yujo11 안녕하세요 윤호님. 피드백 해주셔서 감사합니다 :)
코드 최대한 수정해보려고 노력했으니 다시 피드백 부탁드립니다!

그리고 전에 여쭤본 상태관리는 제가 로또 저장해둘 용도로 클래스를 하나 만들어놨는데 이게 이상한게 아닌지 모르겠네요 ㅎ

2022-07-17 06:31 UTC, JunilHwang approved these changes
안녕하세요 지수님!
원래 제가 리뷰를 해야 하는게 맞는데.. 어쩌다보니(?) 처음에 윤호님께서 리뷰를 해주셨네요 ㅎㅎ
이번에는 제가 리뷰를 남겨봤습니다!
일단 이번 단계의 경우 여기서 마무리 하고,
이번에 남긴 피드백은 다음 단계를 진행하면서 고민해보시면 좋을 것 같습니다.
궁금한점 있으면 코멘트 남겨주시거나 DM 부탁드려요!
감사합니다 🙇‍♂️

2022-07-17 06:31 UTC, JunilHwang commented on src/js/constants/index.js
> +  MAX_NUM: 45,
MIN도 필요하지 않을까요?

2022-07-17 06:31 UTC, JunilHwang commented on src/js/constants/index.js
> +  NOT_MULTIPLE_OF_1000: '로또 구입 금액을 1,000원 단위로 입력해 주세요.',
`1,000` 이라는 문자 대신에 LOTTO에 정의된 상수를 활용해보면 어떨까요?

2022-07-17 06:31 UTC, JunilHwang commented on src/js/element.js
> +};
음.. setValue라는 이름과는 조금 동떨어진 동작 같아 보여요!
더 명시적인 이름을 사용해주면 어떨까요?

2022-07-17 06:31 UTC, JunilHwang commented on src/js/validate/money.js
> +};
더 많은 검증로직이 있어야 하지 않을까요?

2022-07-17 06:31 UTC, JunilHwang commented on src/js/lotto.js
> +};
Numbers 보단 Size가 어울릴 것 같아요!

2022-07-17 06:31 UTC, JunilHwang commented on src/js/lotto.js
> +};
```suggestion
const lottoNumbers = Array(LOTTO.MAX_NUM).fill(1).map((v, k) => v + k);
const generateLotto = () => lottoNumbers.sort(() => 0.5 - Math.random()).slice(0, LOTTO.LENGTH);
```
이런식으로 표현할 수 있답니다!
![image](https://user-images.githubusercontent.com/18749057/179386842-f8fba49a-18dd-4636-adc2-1c129a154a9e.png)

그리고 정렬까지 해주면 더 좋겠네요 ㅎㅎ

```suggestion
const lottoNumbers = Array(LOTTO.MAX_NUM).fill(1).map((v, k) => v + k);
const generateLotto = () => lottoNumbers.sort(() => 0.5 - Math.random()).slice(0, LOTTO.LENGTH).sort((a, b) => a - b);
```

2022-07-17 06:31 UTC, merged