[클린코드 3기] 김대원 로또 미션 STEP 2
next-step/js-lotto pull request #143
Opened 2022-07-17 05:59 UTC by largeKim

안녕하세요!

기능이 추가되고 데이터 부분이 필요해 추가하다보니,

각 함수들의 작성방법과 위치는 적절한지

함수는 잘 작성한 건지 모르겠습니다(특히 lottoViewModule 내부 getWinningResultViewMode과 같은 경우…).

고쳐야될 부분이 많다는 생각이 들지만, 코드 리팩토링을 어떤방식으로 접근해야 할지

바쁘시겠지만 조심스럽게 가이드 부탁드리겠습니다.

감사합니다!

2022-07-19 02:13 UTC, Tanney-102 requested changes
안녕하세요 대원님!
분리되어있는 모듈들을 토대로 요구사항을 잘 작성해주셨네요!
다만 조금 정리 되었으면 하는 부분이 있어 코멘트 드립니다.

1. 우선 model이 한 곳에서 관리되었으면 합니다.
winning result는 lottoModule에서 얻어내고 이를 view에서 쓰기 쉽게 가공하는 일은 lottoViewModule에서 하고 있는데 코드 복잡성만 증가하는 것 같아요! 
handler에는 lottoModule에 데이터를 요청 => 결과 반환 => 이 결과를 view 넘김 => render
와 같이 핵심적인 흐름만 남겨두었으면 합니다.

2. 테스트 파일을 목적에 맞게 잘 분리했으면 합니다.
지금은 e2e/winningResult.cy.js에 몇몇 함수에 대한 유닛테스트가 포함되어 있는 것 같습니다.

3. LottoError 클래스의 목적이 모호합니다.
Error 객체를 상속하면서 constructor에 alert이나 console.error같은 사이드 이펙트를 가지고 있는 건 바람직하지 않아보입니다. 차라리 throw된 에러를 처리할 수 있는 유틸을 만들어시면 어떨가 싶네요~!
또는 try catch문을 통해 alert 처리만 해주셔도 무난할 것 같습니다.

2022-07-25 10:01 UTC, largeKim commented on src/js/index.js
> +  if (isInvalidInputMoneyUnit(LOTTO_PER_PRICE, +$moneyInput.value)) {
submit 이벤트로 받고있는데
혹시

e.target.querySelector('input.money-input').value 

이런방식을 말씀하시는 걸까요 ?

2022-07-26 17:01 UTC, Tanney-102 commented on src/js/index.js
> +  if (isInvalidInputMoneyUnit(LOTTO_PER_PRICE, +$moneyInput.value)) {
input에 name attribute가 채워져있으면 form 이벤트 타겟을 통해 접근하실 수 있습니다.
예를 들어
`<input name="input1" />`
이런 input이 있으면 
`e.target.input1` 또는 `e.target.elements.input1`
요렇게 접근하실 수 있어요!

2022-07-26 17:10 UTC, Tanney-102 requested changes
안녕하세요 대원님~
리뷰 반영하신 것 확인했습니다!
질문 주셨던 form event 관련해서만 마저 반영해주시면 될 것 같습니다!

2022-07-27 07:21 UTC, largeKim commented
@Tanney-102 
추가 리뷰 정말 감사드립니다!
보면볼수록 기본이 정말 부족하다는게 많이 느껴지네요..
다음 PR에서는 좀 더 생각하고 고민해볼 문제들이 많은 것 같습니다!
다시한번 감사드립니다!

2022-07-28 17:34 UTC, Tanney-102 approved these changes
리뷰 반영 감사합니다!
고민해볼만한 문제들이 많은만큼 크게 성장하시리라 믿습니다~!
그럼 다음 스텝에서 뵙겠습니다.

2022-07-28 17:34 UTC, merged