[클린코드 3기] 임창묵 로또 미션 STEP 1
next-step/js-lotto pull request #149
Opened 2022-07-19 16:46 UTC by blackMoja

안녕하세요 준일님! 
제가 최근에 회사에 야근이 너무 잦아서 지금에서야 로또 과제의 PR을 올립니다.. 🥲
로또 2~3 일차는 다음주 화요일까지 꼭..! 리뷰를 받도록 하겠습니다 🙂

로직을 짜면서 이전에 계산기 미션에서 테스트 로직을 작성해보지 않았고 그에따른 방향성을 조금 잡지 못하였는데
이번 과제에서 기능 위주로 한번 테스트 코드를 작성하였습니다.
아무래도 처음 테스트 코드를 작성하는 부분이여서 많이 부족하다는 것을 많이 느꼈습니다.

테스트 코드를 짜면서 고민했던 부분은 로직 개발의 우선순위를 어디로 두어야 할까? 에 대한 고민이 조금 많았습니다.
대부분 테스트코드를 겸한 코드라고 보자면 테스트 코드 -> 테스트 통과된 코드 기반의 개발진행을 목표로 하고 있는데
혹시 준일님께서는 테스트 코드를 작성하시면서 개발을 진행하실때 순서나 고려하시는 포인트를 공유해주신다면 감사하겠습니다..ㅎㅎ

이번 과제는 전반적으로 한 파일에 모든 기능을 담는다기 보다는 크게 2가지 기능을 기준으로 나누어서 개발을 진행하였습니다.
코드를 막 개발완료하기 전 문뜩 드는 생각이 lotto class 기반으로 확장시켜서 진행하였으면 조금 더 깔끔한 구조가 나왔을탠대 하는 아쉬움도 조금 있어서 추후 리펙토링도 진행 할 예정 입니다. 

피드백 주시는 코드 구조 및 테스트 코드에 대해서 빠르게 반영하고 다시 코멘트로 피드백 드리겠습니다 :)
감사합니다!

2022-07-22 17:50 UTC, Tanney-102 requested changes
창묵님 안녕하세요! 리뷰어 오태은입니다!
리뷰가 조금 늦어지게 되어 죄송해요😢
말씀해주신대로 스텝 2,3 올려주시면 최대한 빠르게 확인하겠습니다🙏

전반적으로 역할에 따라 모듈을 나누려고 하신 노력이 보여서 좋았어요!
이와 관련한 코멘트 몇가지 남겼으니 확인하시고 고민해보셨으면 좋겠습니다!

추가로 테스트 코드에 대한 고민을 공유해주셨는데 테스트 코드를 작성하는 것 자체에 대한 고민이실까요? 혹은 TDD에 대한 고민이실까요?
조금만 더 자세히 고민을 나눠주시면 답변드리는데 도움이 될 것 같아요!
테스트는(특히 e2e는) 저도 늘 어렵고 고민이 많은 분야라 같이 이야기 나눠봤으면 좋겠네요~

2022-07-22 17:50 UTC, Tanney-102 commented on src/js/lotto.js
> +}
validation 하는 함수를 잘 분리해주셨네요!
더 나아가서 에러 메시지를 처리하는 방식도 분리해주면 어떨까요?
같은 상황에서 에러 메시지를 다른 방식(예를 들어 스낵바나 토스트 ui 등)으로 처리 해주도록 하는 요구사항이 생기면 비슷한 로직을 반복해서 구현하게 될 것 같습니다.

두가지 정도 제안해봅니다.
1. checkValidate은 true/false만 반환하고 사용처에서 에러처리(alert)
2. 에러 메시지를 처리하는 callback 받기

2022-07-22 17:50 UTC, Tanney-102 commented on src/js/lotto.js
> +}
'is' prefix는 보통 boolean 값을 반환하는 함수나 boolean 변수에 많이 사용합니다.

다른 개발자가 이 함수를 볼 때 
이름이 isPriceValidate이네? => 어떤 경우에 price가 valid할까(true를 반환할까) => 어떤 경우에 price가 invalid할까(false를 반환 할까)
와 같은 흐름으로 읽을 수 있게 작성해주시면 좋겠습니다.

2022-07-22 17:50 UTC, Tanney-102 commented on src/js/lotto.js
> +const updateStyle = () => {
updateStyle이라는 이름은 조금 모호한 것 같습니다.
실제 코드가 style을 update이 하고 있긴하지만 display: none으로 감춰져있던 resultForm과 numberForm을 '보여주는'데 이 함수의 목적이 있다고 생각합니다.
무엇을 하기 위한 함수인지 구체적으로 네이밍해주시면 좋겠습니다.

2022-07-22 17:50 UTC, Tanney-102 commented on src/js/lotto.js
> +    $lottoNumberForm.style.display = 'block'
그리고 display: none을 제거하기 위해 특정 값(여기서는 block)을 주는 건 좋은 방법은 아니라고 생각해요.
위 form들의 display가 flex로만 바뀌어도 요런식의 코드는 모두 수정되어야합니다.
대안을 고민해보셨으면 좋겠습니다.

2022-07-22 17:50 UTC, Tanney-102 commented on src/js/lotto.js
> +  }
updateStyle 함수에 대해 하나만 더 이야기 하자면..
이 모듈에는 어울리지 않는 함수 같습니다.
제가 느끼기에 lotto.js는 앱의 서비스 내지는 컨트롤러의 역할을 담당하고 lottoResult.js 가 view를 담당하는 것으로 보입니다.
updateStyle은 view에 어울리는 함수라고 생각 됩니다.

2022-07-22 17:50 UTC, Tanney-102 commented on src/utils/getLottoNumber.js
> +}
유틸보다는 서비스에 가까운 것 같습니다. lotto.js로 옮겨가면 좋겠습니다.

2022-07-22 17:50 UTC, Tanney-102 commented on src/js/lottoResult.js
> +}
'renderLotto'인제 render 이상의 일을 하고 있습니다.
여기서 getLottoNumber를 호출하기 보다 서비스 쪽에서 이미 만들어진 로또 리스트를 인자로 받아 렌더만 해주도록 수정해보면 어떨까요?

2022-07-26 15:58 UTC, blackMoja commented on cypress/integration/lotto.spec.js
> +        .length === 0
개발 의도는 lottoNumbers 배열의 숫자가 45 미만, 중복값이 없는 배열의 구조가 맞는지에 대한 부분을 검증하고자 하였습니다!

2022-07-31 08:23 UTC, blackMoja commented
안녕하세요 태은님! 
요즘 회사가 너무 바빠서 시간나는대로 바로 수정하여 올렸습니다 ~

말씀해주신 피드백을 기준으로 많이 수정하여 코드를 개선하였습니다!
늦었지만 더 많은 피드백 주시면 빠르게 처리하도록 하겠습니다 

감사합니다~

2022-08-02 00:06 UTC, Tanney-102 commented on cypress/integration/lotto.spec.js
> +        .length === 0
아하 이해했습니다!
우선 45 미만인지 검사하는 로직은 없는 것 같아요!
그리고 중복을 검사하는 로직임을 변수명이나 함수명으로 표현해주시면 코드를 읽는 사람(함께 일하는 동료나 미래의 자신)이 더 빠르게 코드를 소화할 수 있을 것 같습니다!
예를 들어
```js
 const hasDuplicatedItem = (items) =>
      items.filter((item, index) => items.indexOf(item) != index)
        .length === 0
```

2022-08-02 00:13 UTC, Tanney-102 approved these changes
안녕하세요 창묵님!! 바쁘신 중에도 열심히 미션 진행하시고 리뷰 반영해주시느라 고생이 많으셔요~
완벽하지 않아도 좋으니 최대한 이 과정을 완주하셨으면 합니다!
아직 반영이 되지 않은 부분은 다음 스텝 진행하시면서 고민해보셔도 좋겠습니다!
(꼭 모든 리뷰를 반영하지 않으셔도 좋습니다. 많이 고민만 해주세요!)
그럼 다음 스텝에서 뵙겠습니다!

2022-08-02 00:13 UTC, merged