[클린코드 3기] 정대윤 로또 미션 STEP 2
next-step/js-lotto pull request #153
Opened 2022-07-23 13:38 UTC by sensecodevalue

# ⛳️작업 내용 (구현 컨샙)
### 리팩터링
- MVC 패턴으로의 변경이 있었습니다.
  - 기존 `components` 하위에 있던것들은 컴포넌트 부르기도 뭐하고 view와 handling하는 것들이 모여있었습니다.
  - 그래서 해당  `components` 폴더를 `view`와 `controller`로 분리하였습니다.
  - `Model`은 store로 했습니다.

- `store` 코드의 변경이 있었습니다. <해당부분은 계속 보면서 연구 개발중입니다!>
  - 기존 index에 있던 `dispatch` `commit` 생성 부분을 분리했습니다.
  - 상수로 관리되는 `dispatch` `commit` key값들도 상수파일로 분리했습니다.

### STEP1 리뷰적용
- step1에서 작성된 `로또 생성 테스트`의 테스트 코드의 경우 각각의 코드가 독립적으로 될 수 있도록 변경을했습니다.
  - 하지만 테스트를 추가하거나 등의 리팩터리은 진행하지 못했습니다.
- 로또 도메인에서 사용되는 상수들은 `domain/lotto` 하위에 정의하였습니다.

### STEP2
- `로또 당첨 번호 입력 테스트`, `당첨 결과 모달 기능 테스트`, `당첨 결과 확인 테스트` 가 추가되었습니다.
  - STEP1의 `로또 생성 테스트`는 아직...입니다.ㅠ

### [데모링크](https://sensecodevalue.github.io/js-lotto/) - https://sensecodevalue.github.io/js-lotto/

# 🎯 기능 요구사항
- [x] 결과 확인하기 버튼을 누르면 당첨 통계, 수익률을 모달로 확인할 수 있다.
- [x] 로또 당첨 금액은 고정되어 있는 것으로 가정한다.
- [x] 다시 시작하기 버튼을 누르면 초기화 되서 다시 구매를 시작할 수 있다.

# 📊 테스트 요구사항
- [x] 결과 확인하기 버튼을 누르면 당첨 통계, 수익률을 모달로 확인할 수 있다.
- [x] 다시 시작하기 버튼을 누르면 초기화 되서 다시 구매를 시작할 수 있다.

# ❓ 질문
1. 구조 변경이 적절히 이루어 졌는가 궁금합니다. 
  - M(S)VC에 맞추어 변경되었습니다.
  - 반응형 관련 코드를 core 하위에 두었습니다. 
  - lotto 관련 코드를 domain하위에 두었습니다.
2. modal 같은 경우, 같은 코드가 반복되어 사용되어 hooks형태면 쉽게 사용할 수 있겠다는 생각에 useModal형태로 사용했습니다.
 - 해당 형태가...적절한지는 잘모르겠습니다.
 - 혹시 다른 방법이 있을까요?

# 📎레퍼런스

2022-07-24 02:45 UTC, JunilHwang requested changes
안녕하세요 대윤님! step2 진행 잘 해주셨네요 👍 

일단 질문에 대한 답변을 드리자면,

> 구조 변경이 적절히 이루어 졌는가 궁금합니다.

도메인을 분리한 부분은 무척 잘하셨습니다!! 그리고 도메인 코드에 대해서 단위 테스트를 작성해보시면 어떨까요?
다른 부분들도 구조는 무척 잘 작성해주신 것 같습니다 👍 

다만 controller 내에서도 depth를 구분해주시면 어떨까 싶어요!


> modal 같은 경우, 같은 코드가 반복되어 사용되어 hooks형태면 쉽게 사용할 수 있겠다는 생각에 useModal형태로 사용했습니다. 해당 형태가...적절한지는 잘모르겠습니다. 혹시 다른 방법이 있을까요?

관심사를 잘 분리해주셨네요 ㅎㅎ 적절하게 작성하신 것 같습니다.
다만, 이것도 관점에 따라서는 controller가 되지 않을까요?
hooks로 묶는 기준이 뭘까요?

---

그리고 확인해야 할 부분은,
- 구매 금액이 음수일 때에 대한 처리
- 구매 금액을 `123456789000` 처럼 입력했는데 앱이 멈추네요! 어떤 이유 때문일까요?
- 사용성도 조금 신경써주시면 좋을 것 같아요!
  - 가령 모달을 닫을 때 esc 같은 키를 이용해서 닫을 수도 있어야 하지 않을까요?
  - 로또 당첨 번호를 입력한 후에 자동으로 다음 input으로 넘어가게 해주면 어떨까요?
  - 그리고 전송할 때가 아니라 입력할 때 validate를 해주면 어떨까요?

나머지는 리뷰 내용을 확인해주세요! 감사합니다 🙇‍♂️

2022-07-24 02:45 UTC, JunilHwang commented on cypress/e2e/spec.cy.js
>    it('1000원 단위 금액 입력 후 구매한다.', () => {
음수에 대한 처리가 없네요!

2022-07-24 02:45 UTC, JunilHwang commented on src/js/store/createCommit.js
> +}
파일 이름과 함수 이름을 일치시켜주면 어떨까요?

2022-07-24 02:45 UTC, JunilHwang commented on src/js/store/createDispatch.js
> +    act({ state, action, mutation, getter }, ...payload);
인자들이 전혀 사용되고 있질 못하네요 ㅠㅠ

2022-07-24 02:45 UTC, JunilHwang commented on src/js/domain/lotto/constants.js
> +};
왜 constants는 파일로 분리를 하는걸까요?
그냥 domain 내에서만 사용된다면 파일로 분리할 필요가 있을까요?
오히려 같은 파일 내에 둬야 관리하기가 쉽다고 생각해요!

2022-07-24 02:45 UTC, JunilHwang commented on src/js/domain/lotto/getLottoRank.js
> +}
switch/case를 사용하지 않고, if를 사용하지 않고 해결할 수 있는 방법이 있지 않을까요?

2022-07-24 02:45 UTC, JunilHwang commented on src/js/domain/lotto/checkWinningLotto.js
> +}
validate 파일과 합쳐도 무방해보여요!

2022-07-24 02:45 UTC, JunilHwang commented on src/js/controller/ButtonRestart.js
> +  };
store를 갱신한 다음에 dom을 다시 조작하고 있네요!
이런 과정 없이 store에 반영 되면 다시 render가 되도록 일관성 있게 유지하면 어떨까요?
어디선가는 store에 반영만 하고 어디선가는 dom을 직접 조작하고 있어서
store 코드를 직접 확인하지 않으면 전체적인 흐름을 이해하기가 무척 어려울 수 있을 것 같아요!

2022-07-26 10:04 UTC, sensecodevalue commented on cypress/e2e/spec.cy.js
>    it('1000원 단위 금액 입력 후 구매한다.', () => {
음수에 대한 처리와 최대 값은 100,000원으로 하여 리뷰내용을 추가했습니다!
[8b5952a](https://github.com/next-step/js-lotto/pull/153/commits/8b5952a6da6f2cf63e6411d5e1b5ee7b6f97ef01)

2022-07-26 10:05 UTC, sensecodevalue commented on src/js/store/createCommit.js
> +}
변경하였습니다!
[8bd77b0](https://github.com/next-step/js-lotto/pull/153/commits/8bd77b068d5490cc8ed0aa5dd92d238ee1089095)

2022-07-26 10:07 UTC, sensecodevalue commented on src/js/store/createDispatch.js
> +    act({ state, action, mutation, getter }, ...payload);
네 맞습니다!! 디스페치의 경우 다른 디스페치를 사용할 수도 있어야되고 함수로 주입시키는 것 보다는 class의 형태가 맞다고 생각하여 리팩터링했습니다.
```js
import reactiveState from '../core/reactive/reactiveState.js';

export default class Store {
  constructor({ state, getter, mutation, action }) {
    this.state = reactiveState(state);
    this.getters = getter;
    this.actions = action;
    this.mutations = mutation;

    this.getter = this.getter.bind(this); // setTimeout 코드로 this주입....
    this.dispatch = this.dispatch.bind(this);
    this.commit = this.commit.bind(this);
  }

  getter(name) {
    const get = this.getters[name];
    if (!get) {
      throw new Error(`${name} is not found in getter`);
    }

    return get(this);
  }

  dispatch(name, ...payload) {
    const act = this.actions[name];

    if (!act) {
      throw new Error(`${name} is not found in action`);
    }
    act(this, ...payload);
  }

  commit(name, payload) {
    const mutate = this.mutations[name];

    if (!mutate) {
      throw new Error(`${name} is not found in mutation`);
    }
    mutate(this, payload);
  }
}

```

2022-07-26 10:08 UTC, sensecodevalue commented on src/js/domain/lotto/constants.js
> +};
넵 맞습니다!! 상수를 공통적으로 사용되는곳을 제외하고 변경을 하였습니다.
[ca350b1](https://github.com/next-step/js-lotto/pull/153/commits/ca350b1598491a7f810da07e0c4a231334a2997f)

2022-07-26 10:09 UTC, sensecodevalue commented on src/js/domain/lotto/getLottoRank.js
> +}
이걸 어떻게 줄일까하여 딕셔너리 형태면 많이 줄일 수 있을것이라고 생각했습니다. [9985081](https://github.com/next-step/js-lotto/pull/153/commits/9985081493600a2461cd84c9d4487be6e274ff3a)

2022-07-26 10:10 UTC, sensecodevalue commented on src/js/domain/lotto/checkWinningLotto.js
> +}
네 맞습니다!! 적용했습니다. 감사합니다!! 
[78cf740](https://github.com/next-step/js-lotto/pull/153/commits/78cf74054a8a452f289bb79cf9948f3b2c09751b)

2022-07-26 10:12 UTC, sensecodevalue commented on src/js/controller/ButtonRestart.js
> +  };
해당 부분은 지속적으로 어떻게할까를 생각해보았습니다!
처음에는 render를 무족건 반환하게하여 app.js에서 한번에 등록시키도록할까...도 생각했다가
결국 controller를 class형태로 바꾸고 render 함수를 선언하면 자동으로 등록되어 랜더링 되도록 변경하는 방법을 진행해 보려구 합니다!
혹시 해당부분 다른 더 좋은 방법있다면 조언 부탁드립니다!

2022-07-26 11:57 UTC, JunilHwang approved these changes
안녕하세요 대윤님! 피드백 반영 잘 해주셨네요 👍 
몇 가지 리뷰 더 남겼으니 다음 스텝 진행하실 때 참고하시면 될 것 같습니다 ㅎㅎ
기본적으로 `export default`를 해주는 함수/클래스 이름과 파일 이름을 일치시켜주는게 좋답니다! 그래야 ide나 editor에서 탐색하기 더 수월하고, 특히 코드를 보는 사람 입장에서 덜 헷갈려요!

이제 마지막 단계만 남았네요 ㅎㅎ 조금만 더 힘내봅시다! 화이팅 💪💪

2022-07-26 11:57 UTC, JunilHwang commented on cypress/e2e/spec.cy.js
> +  it('금액 입력창에 100000만원 이상의 금액을 입력 후 구매한다.', () => {
`이상`이기 때문에 경계값은 100000이 아닐까요!?
혹은 테스트 명을 변경해야 할 것 같아요~

2022-07-26 11:57 UTC, JunilHwang commented on cypress/e2e/spec.cy.js
>      cy.alert('로또 구입 금액을 1,000원 단위로 입력해 주세요.');
여기서 alert를 띄울 필요는 없을 것 같아요~

2022-07-26 11:57 UTC, JunilHwang commented on src/js/store/Store.js
> +    mutate(this, payload);
mutate가 this에 대한 모든 정보를 가지고 있을 필요가 있을까요?

2022-07-26 11:57 UTC, JunilHwang commented on src/js/store/Store.js
> +    return get(this);
getter도 state에 대한 정보만 알고 있어도 무방할 것 같아요!

2022-07-26 11:57 UTC, JunilHwang commented on src/js/store/Store.js
> +  }
멤버변수는
```suggestion
  state, getters, actions, mutations;
  
  constructor({ state, getter, mutation, action }) {
    this.state = reactiveState(state);
    this.getters = getter;
    this.actions = action;
    this.mutations = mutation;
    
    // bind가 꼭 필요할까요?
    this.getter = this.getter.bind(this);
    this.dispatch = this.dispatch.bind(this);
    this.commit = this.commit.bind(this);
  }
```

멤버변수는 클래스 필드에 미리 정의해주세요!
그래야 이 코드를 보는 다른 사람이 어떤 멤버변수가 사용되는지 파악하기가 쉽답니다 ㅎㅎ

2022-07-26 11:57 UTC, JunilHwang commented on src/js/view/ResultTableRow.js
> +};
이 코드도 View 보단 Domain에 해당하는 코드가 아닐까요?

2022-07-26 11:57 UTC, JunilHwang commented on src/js/controller/Result/Yield.js
> +  };
이 코드도 도메인에 해당하는 코드가 아닐까요?

2022-07-26 11:57 UTC, JunilHwang commented on src/js/hooks/useModal.js
> +export default function useModal() {
useModal은 사용되고 있지 않네요!

2022-07-26 11:57 UTC, JunilHwang commented on src/js/controller/Modal/Open.js
> +}
파일 이름과 일치시키면 어떨까요?

2022-07-26 11:57 UTC, JunilHwang commented on src/js/controller/Modal/Close.js
> +}
앞선 내용과 동일합니다!

2022-07-26 11:57 UTC, JunilHwang commented on src/js/controller/Lotto/NumbersToggleButton.js
> +export default function LottoNumbersToggleButton() {
앞선 내용과 동일합니다!

2022-07-26 11:57 UTC, JunilHwang commented on src/js/controller/Lotto/List.js
>  export default function LottoList() {
앞선 내용과 동일합니다!

2022-07-26 11:57 UTC, JunilHwang commented on src/js/controller/Lotto/Amount.js
>  export default function LottoAmount() {
앞선 내용과 동일합니다!

2022-07-26 11:57 UTC, merged