[클린코드 3기] 이지수 로또 미션 STEP 2
next-step/js-lotto pull request #156
Opened 2022-08-03 16:04 UTC by jisoo-log

일정상 많이 늦어서 정말 민망하지만 지금이라도 하나하나 빨리 해보려고 합니다 ㅎㅎ

step2를 하면서 고민한 부분은,

1. random으로 만들어진 로또 숫자가 당첨된 내용은 어떻게 테스트해야하는지 궁금합니다.
함수 unit 테스트로 대체해야할까요?
아니면 화면에 랜더링된 값을 가져와서 계산한 내용을 확인해야할까요?

2. 지금 최대한 store 사용을 줄이고 싶어서 버튼 클릭할때 로직을 바로바로 연결했는데, 어느정도 정보를 저장해두고 사용하는게 좋을지도 궁금합니다.
원래 중간에 로또 당첨 관련 로직도 넣어봤다가, 지금은 lotto 정보 하나만 들고 있게 했습니다. 
뭔가 store 거치면 뭔가 다른곳에 의존하는 느낌이 들어서 최대한 분리해낸건데 어떤게 좋은건지 잘 모르겠습니다.

2022-08-04 03:41 UTC, JunilHwang requested changes
안녕하세요 지수님!
2단계 미션 잘 진행해주셨네요 👍 

아직 몇 가지 고려할 부분이 있는 것 같아요!
테스트 코드가 조금 빈약한 것 같고,
Array 관련된 메소드를 더 적극적으로 활용하는 것도 필요할 것 같습니다 ㅎㅎ

그리고 index.js에 여러 로직을 많이 작성해주셨는데, index.js는 export 하는 역할로만 사용하면 어떨까요?
보통 `src/js/index.js`의 경우 `app.js` 혹은 `main.js` 처럼 네이밍 해서 많이 사용한답니다!

나머지는 피드백 내용을 확인해주세요!

2022-08-05 03:19 UTC, jisoo-log commented on src/js/view.js
>          />
오 이쪽을 줄일 생각을 못했네요 감사합니다 :)

2022-08-05 03:22 UTC, jisoo-log commented on src/js/constants/index.js
>  };
묶어놓는다는 의미가 관심사별로 파일을 따로 분리하라는 말씀이실까요??

2022-08-05 06:44 UTC, JunilHwang requested changes
안녕하세요 지수님! PR에 올린 질문에 대한 답변을 드리자면,

> random으로 만들어진 로또 숫자가 당첨된 내용은 어떻게 테스트해야하는지 궁금합니다.
함수 unit 테스트로 대체해야할까요?
아니면 화면에 랜더링된 값을 가져와서 계산한 내용을 확인해야할까요?

- `로또 숫자 만드는 로직`을 추상화(함수로 만든다거나)해서 관리할 수 있지 않을까요?
- `로또 숫자 만들기`과 이에 대한 `결과물` 을 따로 따로 관리하면 될 것 같아요!
- 즉, `random으로 만들기`에 대해 필요한 테스트를 하고, `로또 당첨`에 대한 테스트를 하는거죠!

> 지금 최대한 store 사용을 줄이고 싶어서 버튼 클릭할때 로직을 바로바로 연결했는데, 어느정도 정보를 저장해두고 사용하는게 좋을지도 궁금합니다.
원래 중간에 로또 당첨 관련 로직도 넣어봤다가, 지금은 lotto 정보 하나만 들고 있게 했습니다.
뭔가 store 거치면 뭔가 다른곳에 의존하는 느낌이 들어서 최대한 분리해낸건데 어떤게 좋은건지 잘 모르겠습니다.

React나 Vue의 경우 state가 변경되면 render가 자동으로 실행됩니다.
UI가 data의 변화에 민감하게 반응하는거죠
그래서 store에 이런 장치를 하나 추가해주면 어떨까요?

그리고 다시 코드를 보면서 느껴진걸 이야기드리자면
- 이벤트 등록 함수에 on과 handle을 같이 쓰고 있네요. 지금 같은 상황에서는 handle을 사용하는게 맞아요!
- view.js에 이벤트 함수가 많이 있네요!
- render과 view와 event handler의 차이를 명확히 구분해서 관리해주면 어떨까요?
- 그리고 render와 view와 event handler에서 store는 어떤 레이어에서 사용해야 하고 어떤 레이어에서 사용하면 안될까요?
- render와 view와 event handler는 서로 어떤 관계일까요? 어떤 역할을 수행해야 할까요?
- 여기에 domain(lotto)가 끼어든다면, 마찬가지로 domain은 어떤 레이어에서 의존해야 좋을까요?

이런 고민들을 해보시면 좋을 것 같습니다!

2022-11-17 12:51 UTC, pocojang approved these changes
3기가 마무리되어 머지합니다
향후 미션을 더 진행하게 되거든 리뷰어와 협의 하에 진행해주세요 😄

2022-11-17 12:51 UTC, merged