[클린코드 4기 유한나라] 로또 미션 STEP1
next-step/js-lotto pull request #159
Opened 2022-11-12 15:49 UTC by nara04040

#요구사항 
- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x] 소비자는 자동 구매를 할 수 있어야 한다.
- [x] 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.
- [x] 위 기능들이 정상적으로 동작하는지 Cypress를 이용해 테스트한다.

 ## 아쉬웠던점
- 구현능력이 많이 부족하여 구체적인 설계없이 무작정 코드를 치기 시작하여 엉망진창으로 코드를 짠 느낌이 있었습니다.  코드를 짜면서도 제 자신이 너무 답답함을 많이 느꼈던 것 같습니다. 향후 리팩토링을 진행하고 step2,3 미션을 진행할 때는 좀 더 생각하면서 코드를 구현해야겠다는 생각이 들었습니다.
- 함수이름선정이 너무나도 힘들었습니다. 직관적으로 작성했다고 느꼈지만 나중에 함수이름을 보았을 때 제가 알아보지 못하는 경우가 많아서 코드를 다시 읽어야하는 상황이 있었습니다. 향후 리팩토링을 하면서 이점도 수정하고싶습니다.
- paymentCost()함수에 모든 기능구현을 몰아넣은것 같습니다. 이점을 수정하고 싶다는 생각이 많이 들었습니다.

2022-11-15 15:19 UTC, jho2301 commented
리뷰 드리고 있습니다!

2022-11-16 00:17 UTC, jho2301 requested changes
안녕하세요 유한나라님!
리뷰어 전환오라고 합니다.

1. 전반적으로 하나의 파일에 모든 코드가 작성되어있어서 모듈 분리가 필요해보여요.
이번 로또 어플리케이션에는 UI를 다루는 코드, 로또 번호를 생성하는 코드, 사용자 동작을 감지하는 코드, 입력받은 데이터를 저장하는 코드 등등이 있었을 것인데 이 코드들이 한 모듈에 모여있으면 금새 복잡해지고 관리하기 어려운 프로그램이 됩니다. 각자 코드의 목적/용도에 따라 모듈을 구분해볼 수 있으면 좋겠습니다.

2. 후기에도 적어주셨지만 함수이름이 많이 직관적이지 못하다는 인상을 받았어요 😢 
간단하게 실천해볼 수 있는 방법을 설명드리자면,
1. 함수가 한 가지 기능만 담당하도록 분리해봅시다.
2. 해당 기능을 한글로 표현해봐요. 함수는 동작의 묶음이기 때문에 필연적으로 동작의 늬앙스가 이름에 들어가야할 것입니다.  e.g.) 로또티켓요소를 만든다
3. 이를 파파고에 번역시켜보세요 . e.g) createLottoTicketElement

함수네이밍이 패턴이 어느정도 정해져있기 때문에 다른 분들 코드를 많이 보시고, 작성해보시면 어느정도 시간이 지난 후부터는 지금과같은 막막함이 들지는 않을 거에요.

3. 다른 참여자분들의 코드를 분석해보시면 어떠띾요?

이번 코스의 장점 중 하나가 동일한 과제로 많은 사람들이 코드를 작성해 제출한다는 것인데요. 유한나라님이 고민한 부분이 있을 것인데, 다른 사람들의 코드를 보면서 어떤 답들이 있는지 확인해볼 수 있어요. 이런 기회를 활용해서 다른 참가자 분들은 어떻게 코드를 작성했는지, 그렇게 작성한 코드로 어떤 피드백을 받았는지 분석해보는 시간을 가져보시면 어떨까요? 보다 밀도있게 학습을 할 수 있게되지 않을까 생각합니다.

4. 
> paymentCost()함수에 모든 기능구현을 몰아넣은것 같습니다. 이점을 수정하고 싶다는 생각이 많이 들었습니다.

paymentCost는 사용자의 동작을 감지해 동작하는(금액입력), 이벤트핸들러 함수이기 때문에 동작에 관련한 기능들이 모일 수 밖에 없어요. 다만 해당 함수가 알아야하는 동작인가를 계속해서 고민해보면서 핸들러 함수를 구성해보시면 좋을 것 같아요. 그리고 기본적으로 이벤트핸들러함수는 event객체를 인자로 전달받기때문에 이 event객체를 잘 활용해보시면 좋겠습니다  https://developer.mozilla.org/ko/docs/Learn/JavaScript/Building_blocks/Events

2022-11-16 00:17 UTC, jho2301 commented on src/js/index.js
> +function paymentCost() {
해당 함수는 유저가 금액을 입력하고 제출하는 동작을 핸들링하는 함수이니

handlePayment 정도가 어떨까 싶네요

이벤트리스너로 등록되는 함수들은 일반적으로 handle-이라는 prefix가 붙으면 일관적으로 네이밍을 작성해줄 수 있어요

2022-11-16 00:17 UTC, jho2301 commented on cypress/integration/lotto.spec.js
> +  });
beforeEach를 사용해주시면 테스트마다 visit이 수행되도록 할 수 있어요

2022-11-16 00:17 UTC, jho2301 commented on cypress/integration/lotto.spec.js
> +  });
이렇게 어찌보면 당연한 테스트는 작성하지 않는 것이 오히려 나을때도 있겠습니다.
테스트작성도 품이 드는 비용이기 때문에, 동작에 대한 부분을 테스트하는 것이 보다 효율적일 거에요
어떤 것은 당연하고 어떤 것은 당연하지 않은지 고민해보는 것도 좋겠습니다

2022-11-20 07:05 UTC, jho2301 approved these changes
리뷰 반영해주신 것 잘 확인했습니다. 다음 스텝에서도 이번 스텝에서 피드백 드린 것 기반으로 진행해보시면 좋을 것 같아요 화이팅입니다

2022-11-20 07:06 UTC, merged

2022-11-20 10:40 UTC, nara04040 commented on cypress/integration/lotto.spec.js
> +  });
넵! 감사합니다!

2022-11-20 15:33 UTC, jho2301 commented on index.html
> +              <button type="button" id="payment-button" class="btn btn-cyan">확인</button>
form태그에 onSubmit이벤트핸들러를 등록한후, form태그 내부의  submit 타입의 버튼을 클릭하면 submit이벤트가 발생하게됩니다. 
관련해 학습할 수 있는 아티클 공유드려요
https://ko.javascript.info/forms-submit

2022-11-20 15:37 UTC, jho2301 commented on src/js/index.js
> +  }
의도한대로 동작을 한다면 틀린 코드는 아닌거에요. 
다만 코드가 의도한대로 읽히고 이해될 수 있는가, 보다 유연하게 변경에 대응할 수 있는가는 다른 관점의 문제라고 봐주시면 되겠습니다.
그런면에서 크게 이상한점을 느끼지는 않는 것 같아요

2022-11-20 15:38 UTC, jho2301 commented on src/js/lotto.js
> +
합당한 이유로 적절한 판단을 해주셨다고 생각이 듭니다

2022-11-20 15:39 UTC, jho2301 commented on src/js/lotto.js
> +      }
우선 내부에서 사용하고 있는 lottoNumber도 인자로 전달을 받아야할 것 같아요. 그렇게 된다면 분리가 수월해지지 않을까요?

2022-11-20 15:57 UTC, jho2301 commented on src/js/lotto.js
> +
dom은 브라우저 도메인에서 통용되는 개념이라 lotto가 dom에 대해서 직접 알아야할필요는 없어요 하지만 dom api를 사용하고 있기때문에 순수한 서비스로직을 분리하는 것외에는 완전하게 분리는 어려울 것으로 보여요