[클린코드 4기 유승완] 로또 미션 STEP1
next-step/js-lotto pull request #160
Opened 2022-11-13 11:01 UTC by Seung-wan

안녕하세요, 태은님! 리뷰 잘부탁드립니다!
사소한 것 하나하나 다 짚어주셨으면 좋겠습니다!

# 요구사항
- 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- 로또 1장의 가격은 1,000원이다.
- 소비자는 자동 구매를 할 수 있어야 한다.
- 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.

# 여쭤보고 싶은 부분
## cypress
- 테스트를 작성할 때, 아래의 2개의 경우가 확인 버튼을 직접 클릭할 것인지, 혹은 키보드의 엔터키를 누를 것인지만 서로 다른데 이런 경우에도 테스트 케이스를 따로 작성하는게 좋을까요? 아니면 더 효과적인 방식이 있을까요?
'로또 구입 금액을 1000원 단위로 입력하지 않고 확인 버튼을 클릭하면 사용자에게 alert를 띄워준다.' 
'로또 구입 금액을 1000원 단위로 입력하지 않고 키보드의 엔터키를 누르면 사용자에게 alert를 띄워준다.'
- '소비자는 자동 구매를 할 수 있어야 한다', '복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다' 와 같은 요구사항을 테스트하기 위해서 input창에 금액을 입력하고 확인 버튼을 클릭하는 동작이 반복되는데 이런 동작들은 typePriceAndClickButton 이런 식으로 함수를 작성해서 반복을 줄이는게 좋은 방식일까요?

2022-11-14 18:12 UTC, Tanney-102 requested changes
안녕하세요 승완님! 리뷰어 오태은입니다.
코드가 전반적으로 깔끔해서 놀랐습니다 😄
역할에 따라 모듈도 잘 나눠주셨고 각 함수도 필요에 따라 잘 나뉘어 작성된 것 같아요~
테스트도 꼼꼼히 작성해주셔서 인상 깊었습니다.
몇가지 코멘트 남겨드렸으니 확인부탁드려요!

질문 답변드립니다.
1. 엔터 + 클릭을 각각 테스트?
사실 사용자 입장에서 키보드 입력과 마우스 클릭은 다른 behavior 이기에 각각 테스트를 작성해주는 게 맞다고 생각합니다. 다만 이번 미션처럼 form을 submit 하는 경우에는 submit 자체에 대해서만 테스트를 해줘도 충분하다고 생각해요. cypress에서 제공하는 submit command를 활용해보시면 좋을 것 같습니다.

2. descirbe관련
decribe 함수는 테스트의 컨텍스트를 나누기 위해 사용됩니다~
말씀하신 '요구 사항 단위'가 실제 동작하는 '테스트 코드' 단위를 이야기 하시는 게 맞을까요? 
그렇다면 요구 사항 단위에서는 가능하면 it 함수를 사용하여 작성해주세요!
다만 요구사항이 너무 많아진다면 세부 카테고리에 따라 describe를 중첩하여 테스트 구조를 설계해보면 좋을 것 같아요~
describe를 통해 각 테스트들을 그룹화하고 it 함수를 통해 실제 요구사항에 해당하는 테스트 코드를 작성한다고 생각하시면 좋을 듯합니다. 
예를들어 step1 테스트를 다음과 같이 작성해볼 수 있습니다.
```js
describe('로또 티켓 발행', () => {
  describe('로또 금액 폼 입력 테스트', () => {
    beforeEach(() => getLottoInput().clear()) // 예시를 위한 함수입니다.

    it('폼에는 숫자만 입력할 수 있다.', () => {})
    it('1000원 단위의 숫자가 아닐 경우 에러메시지를 보여준다.', () => {})
    ...
  })

  describe('로또 발행 결과 화면 테스트', () => {
    it('발행한 로또의 수가 보여진다.', () => {})
    it('toggle switch가 켜진 상태이면 로또 티켓과 번호를 보여준다.' () => {})
    ...
  })
})
```

답변이 되셨을지 모르겠어요.
혹시 더 궁금하신 점 있다면 언제든 질문 주셔요!

2022-11-14 18:30 UTC, Seung-wan commented on .eslintrc.json
> +  "plugins": ["prettier"],
감사합니다. 남겨주신 링크의 Installation 확인했습니다!

2022-11-15 00:54 UTC, Seung-wan commented on cypress/e2e/lotto.cy.js
> +describe('로또 번호를 생성하는 함수를 테스트한다.', () => {
저도 작성하면서 단지 함수의 동작만을 테스트하는데.. 그래서 e2e에 들어가기엔 뭔가 아닌 것 같기는 한데... 근데 그러면 'cypress를 이용한 단위테스트는 어떻게 작성할까?' 까지 도달을 했지만 여기서 더 생각하기를 멈추고 그냥 우겨넣은 느낌이 있는 것 같습니다. 요렇게 슬쩍 넘어가는것도 조심해야겠습니다. 해당하는 테스트는 분리하는게 좋을 것 같습니다!

2022-11-15 00:54 UTC, Seung-wan commented on index.html
> +              <button type="submit" class="btn btn-cyan js-purchase-button" data-cy="purchase-button">확인</button>
감사합니다!

2022-11-15 03:19 UTC, Seung-wan commented on src/js/service/lotto.js
> +};
무언가 제 마음속에 특정 라이브러리에서 불변성을 지켜야하는 경우에는 배열의 고차함수를 활용하지만 이런 제약조건을 지킬 필요가 없는 곳에서는 '객체 타입을 다룰때 어떻게 다루는게 좋을까?' 이런 생각이 있었고, 스스로 답을 내리지 않아서 이런 유형의 코드를 작성할 때 마다 어떨때는 for문, 어떨때는 파이프라인으로 작성했던 것 같습니다. (현재 작성된 코드는 불변성과는 연관이 없지만?)

가능한 경우라면 배열의 내장 메서드를 적극 활용하도록 해봐야겠습니다.
또, 질문드리고 싶은 부분도 있습니다!

1. 추가적인 변수를 선언하는 것의 문제는 변수를 메모리에 할당해야 하는 비용, 코드를 읽는데 드는 비용으로 볼 수 있을까요?
2. for문 대신에 배열 내장함수를 이용하면 컬렉션을 return하기 때문에 데이터를 다루는 로직이 추가되었을 때 메소드체이닝처럼 작성할 수 있고 데이터가 변화되는 흐름을 한눈에 보기 편하다는것을 장점으로 꼽아볼 수 있을까요? 
`
[...Array(count)].map(() => {...}).map(() => {...}).filter(() => {...})
` 

최근에 드는 생각으로는 프로젝트의 규모가 작다면 불필요한 코드들이 가독성에 큰 영향은 없겠지만, 프로젝트의 규모가 커져서 프로젝트 코드가 많아질수록 불필요한 코드의 한 줄 한 줄이 코드를 읽는데 있어 개발자에게 데미지를 주고, 이게 쌓인다고 생각해서 더욱 클린코드가 중요한 것 같습니다. 감사합니다!

2022-11-15 03:30 UTC, Seung-wan commented on src/js/utils/validation.js
> +};
헛 코드를 다시 보니까 생각이 뭔가 꼬였던 것 같은 느낌이 있는 것 같습니다. 
'조건문에서 사용될 조건으로 truthy, falsy값을 사용하지 않고 조건을 직접 명시해줘야겠다!' 라고 생각을 했고, 
함수는 number를 unit으로 나눈 나머지가 0이면 true를 return하려고 하니
'조건을 !(number % unit) 으로 쓰지 말고 number % unit === 0 처럼 조건을 명시해줘야지!' 까지는 했는데 
이 조건을 사용하는 방식이 아쉬웠던 것 같습니다.

number % unit === 0 이라는 조건 자체를 바로 return하는게 훨씬 좋은 것 같습니다!

2022-11-15 03:37 UTC, Seung-wan commented on src/js/view/lotto.js
> +};
확실히 접두사에 show가 붙어있는 다른 함수들은 HTML tag의 'none' 이라는 class를 제거하여 
'display:none' 속성을 없애서 정말 브라우저에 보여주고 있는데 
```
export const showPurchasedLotto = () => {
  $(SELECTOR.PURCHASED_LOTTO).classList.remove('none');
};

export const showLottoResultForm = () => {
  $(SELECTOR.LOTTO_RESULT_FORM).classList.remove('none');
};
```
showLottoNumber는 toggle method를 사용하기도 하고 보여졌다, 사라졌다 동작하기 때문에 
저도 toggle이라는 prefix가 훨씬 함수의 동작을 잘 표현하고 있는 것 같습니다. 

왜 이렇게 작성했는지 생각해보면, 함수의 동작을 100% 인지하지 못한 것(대충 보여주는거니까~) 또, 뭔가 기존에 show로 써놨으니 그냥 비슷하게 show로 작성할까? 라는 안일한 생각이었던 것 같기도 합니다. 변수명은 항상 신경써야겠습니다. 감사합니다!

2022-11-15 03:42 UTC, Seung-wan commented on src/js/eventHandlers/lotto.js
> +    }
예외 처리를 꼼꼼하게 하지 못한 것 같습니다.

로또 구입 금액에 대해서
1. 음수를 입력하는건 당연히 안되지!
2. 로또 가격은 1,000원이니까 1000원 단위로만 입력할 수 있지.
3. (무의식적으로) 근데 로또를 구매를 할 거니까 0원은 입력하지 않겠지.

이렇게 생각했던 것 같습니다.
0원을 입력하는 경우에도 별개의 에러메시지를 사용자에게 띄워주면 좋을 것 같습니다. 감사합니다!

2022-11-15 04:26 UTC, Seung-wan commented
1. 엔터 + 클릭을 각각 테스트?
submit이라는 command가 있었군요!
역시 문서를 잘 찾아보면 필요한 것들은 이미 구현되어 있는 것들이 많은 것 같습니다. 감사합니다!

2. descirbe관련
요구 사항 단위를 저는 아래와 같은 문장 하나 하나로 말씀드렸습니다! 
```
- 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- 로또 1장의 가격은 1,000원이다.
- 소비자는 자동 구매를 할 수 있어야 한다.
- 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.
```
테스트 코드 단위는 요구사항을 잘게 쪼개서 아래와 같이 생각했습니다!
```
- input 태그에 구입 금액을 입력하면 입력한 금액이 input 태그의 value 값과 같아야 한다.
- 구입 금액은 숫자만 입력할 수 있다.
- 화면에 로또를 발급할 때 클릭해야 할 버튼이 존재한다.
```
제가 해결하고 싶었던 문제는 만약 아래와 같은 라면 자판기를 만든다고 했을 때, 
```
제작할 어플리케이션: 라면 자판기
요구사항 : A, B, C, D,
테스트 코드: A-1, A-2, A-3, A-4, A-5, B-1, B-2, B-3, C-1, C-2 ...
```
테스트 코드가 아래와 같이 작성이 된다면 서로 다른 요구사항의 테스트 코드들이 같은 depth에 작성이 되어서 
요구사항 A와, 연관되어 있는 테스트 코드인 A-1, A-2, A-3, A-4, A-5를 하나의 context로 관리하고 싶었습니다!
```
describe('라면 자판기를 테스트한다', () => {
  it('A-1', () =>{})
  it('A-2', () =>{})
  it('A-3', () =>{})
  it('A-4', () =>{})
  it('A-5', () =>{})
  it('B-1', () =>{})
})
```

말씀해주신 부분에서 'describe는 테스트의 context를 나눈다'고 해주신 문장을 보니 바로 이해가 갔습니다.
요구사항이 많아진다면, describe를 이용하여 구조를 잡아보면 좋을 것 같습니다.
작성해주신 예제 테스트코드가 제가 궁금했던 내용이 맞습니다!
추가로 DCI패턴도 한번 공부해봐야겠습니다. 감사합니다!

2022-11-15 14:03 UTC, Seung-wan commented
eslint는 링크내의 Recommended Configuration을 보고 수정하였습니다. 생각해보니 eslint-config-prettier를 설치하고 사용하지 않았었네요. 아래와 같이 extends의 맨 마지막에 넣어주었습니다!
```
// 요렇게 넣어주면
{
  "extends": ["plugin:prettier/recommended"]
}

// 아래와 같이 적용된다.
{
  "extends": ["prettier"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error",
    "arrow-body-style": "off",
    "prefer-arrow-callback": "off"
  }
}
```
코드를 보다가 또 궁금한 게 생겨서 질문드리려고 합니다!

## 1. 브라우저에서 입력받은 값을 number 자료형으로 변경하려고 할 때, 어느 지점에서 변경하는게 가장 적합한지 궁금합니다.

아래의 코드는 로또 구입 금액을 입력하고 확인 버튼을 눌렀을 때 실행되는 코드입니다. 

```
export const handleSubmit = (e) => {
  e.preventDefault();

  try {
    const lottoPurchasePrice = getLottoPurchasePrice();

    if (validation.isZeroNumber(lottoPurchasePrice)) {
      throw Error(ERROR_MESSAGE.INVALID_ZERO_LOTTO_PRICE);
    }

    if (!validation.isPositiveNumber(lottoPurchasePrice)) {
      throw Error(ERROR_MESSAGE.INVALID_NEGATIVE_LOTTO_PRICE);
    }

    if (!validation.isRemainderZero(lottoPurchasePrice, LOTTO.PRICE)) {
      throw Error(ERROR_MESSAGE.INVALID_LOTTO_PRICE_UNIT);
    }
    ...
```
사용자가 입력한 로또 구입 금액을 가져오기 위해 getLottoPurchasePrice라는 함수를 사용하고 있습니다. 이 함수는 input 태그에 접근하여 value값을 들고 오기 때문에 string 자료형으로 가져오게 되는데요. 지금까지는 가져온 로또 구입 금액으로 비교 연산, 나눗셈 연산을 수행했기 때문에 문자열임에도 문제가 없었지만, 로또 구입 금액을 0원으로 입력하는 경우에 대해 예외처리를 작성하는 중에 뒤늦게 로또 구입 금액을 문자열로 사용하고 있다는 것을 깨닫게 되었습니다. ('0' === 0이 되어서 false가 되었습니다) 생각해보니 타입마다 허용되는 연산이 있기 때문에, 문자열 데이터를 가지고 나누기 연산을 했다는 것이 말이 안되는 것 같았습니다. 따라서 로또 구입 금액을 숫자형으로 바꾸려고 하니 2가지의 장소를 생각해봤습니다.

첫 번째는, DOM에 접근하여 input 값을 가져올 때 숫자형으로 형변환을 해주는 것입니다.
`export const getLottoPurchasePrice = () => Number($(SELECTOR.PURCHASE_PRICE_INPUT).value);`
로또 구입 금액이라는 값은 number 자료형이 타당하기 때문에 여기서 형변환을 해주는게 괜찮을 것 같다고 생각했습니다.

두 번째는, validation 메소드에 매개변수로 넘겨줄 때 형변환을 해주는 것입니다.
```
  if (!validation.isPositiveNumber(Number(lottoPurchasePrice))) {
    throw Error(ERROR_MESSAGE.INVALID_NEGATIVE_LOTTO_PRICE);
  }
```
처음에는 이렇게 하면 number 자료형이 필요한 곳에서만 형변환을 해서 넘겨주니 이것도 괜찮다고 생각했지만, validation 메소드를 사용할 때마다 계속 형변환을 해주는 것은 중복이 발생할 것이라고 생각했습니다.

요런 경우에는 로또 금액이라는 데이터이기 때문에 number 자료형임이 명확해서 처음 DOM에 접근하여 값을 가져올 때 Number로 형변환을 하는게 괜찮을까요?

## 2. 유닛테스트 폴더 구조, 파일 명
### 폴더 구조
cypress의 e2e 폴더안에 유닛 테스트 파일을 작성하면 e2e라는 네이밍에 맞지 않는 것 같아 cypress/unit 혹은, 유닛 테스트를 하려는 모듈과 같은 위치에 작성하려고 했으나 cypress에서 해당하는 테스트 파일을 읽어오지 못하는 것 같았습니다.
혹시 config 설정값으로 cypress가 e2e폴더 아래가 아니어도 테스트 파일을 읽어올 수 있게 할 수 있는 설정이 있는 걸까요?
아니면 e2e 폴더 안에 유닛테스를 작성해도 괜찮은건지 궁금합니다.

### 파일 명
랜덤으로 로또 번호를 생성하는 함수를 테스트하는 파일의 이름을 2가지중에 고민했습니다.
randomNumberGenerator vs lottoGenerator
테스트를 하는 모듈 자체는 랜덤하게 숫자를 생성하는 함수이기 때문에 randomNumberGenerator가 적합할까? lotto라는 도메인에서 이 함수를 사용하는 경우에는 로또 번호 생성기가 되는 것이지만, 유닛 테스트는 함수 그 자체를 테스트하는 것이기 때문에 randomNumberGenerator가 맞을 것 같다는 생각이 들었습니다. 하지만 우리가 원하는 행위는 로또 번호를 생성하는 것이고 유닛 테스트 코드 내부에서도 로또 번호를 생성하는 것에 대해 테스트를 하니 rottoGenerator가 맞다고도 생각이 들었습니다. 
이런 경우에 테스트하려는 모듈 자체의 행위(랜덤하게 숫자 생성) vs 테스트 하려는 도메인의 행위(로또 생성) 어떤 네이밍을 따라가는게 적합할까요?

## 3. 추상화 레벨, 모듈 분리
코드를 다시 보다가 추상화 레벨이 맞지 않는다는 생각이 들었습니다.
lottoPurchaseCount(로또 구매 개수)를 가져오는 부분이었습니다.
```
export const handleSubmit = (e) => {
  e.preventDefault();

  try {
    const lottoPurchasePrice = getLottoPurchasePrice();

    if (validation.isZeroNumber(lottoPurchasePrice)) {
      throw Error(ERROR_MESSAGE.INVALID_ZERO_LOTTO_PRICE);
    }

    if (!validation.isPositiveNumber(lottoPurchasePrice)) {
      throw Error(ERROR_MESSAGE.INVALID_NEGATIVE_LOTTO_PRICE);
    }

    if (!validation.isRemainderZero(lottoPurchasePrice, LOTTO.PRICE)) {
      throw Error(ERROR_MESSAGE.INVALID_LOTTO_PRICE_UNIT);
    }

    // 추상화 레벨이 맞지 않는 것 같다.
    const lottoPurchaseCount = lottoPurchasePrice / LOTTO.PRICE;

    renderLottoPurchaseCountText(lottoPurchaseCount);
    renderLottoIcons(lottoPurchaseCount);

    showPurchasedLotto();
    showLottoResultForm();
  } catch (error) {
    console.error(error);
    alert(error.message);
  }
};
```
로또 구입 금액을 가져오거나, validation을 하거나, view를 조작하는 부분은 다 외부 모듈로 분리되어 있는데 lottoPurchaseCount만 로직이 그대로 작성되어 있는 것 같았습니다. 그래서 이 부분을 getLottoPurchaseCount 라는 함수로 분리를 하고자 했습니다.
getLottoPurchaseCount를 view에 작성해야할지, service에 작성해야할지 고민이 되었습니다. 제 생각에는 view에 작성을 하게 되면 lottoPurchaseCount라는 값은 view에서 그대로 가져올 수 없고 로또 구입 금액을 1000으로 나눠주는 연산이 필요하여 데이터를 행들링하기 때문에 적합하지 않다고 생각했습니다. 그래서 service 에서 작성하였는데 요게 적합한 위치인지 궁금합니다. 

또 service에 작성하는 경우에 사용자가 입력한 로또 구입 금액을 어디서 가져오냐가 또 고민이 되었습니다.

1. 매개 변수로 로또 구입 금액을 받아서 로또 구매 개수를 계산해준다.
```
// service/lotto.js
export const getLottoPurchaseCount = (lottoPurchasePrice) => {
  return lottoPurchasePrice / LOTTO.PRICE;
};

// eventHandlers/lotto.js
const lottoPurchasePrice = getLottoPurchasePrice();
const lottoPurchaseCount = getLottoPurchaseCount(lottoPurchasePrice)
```
2. service에서 view에 접근해서 로또 구입 금액을 가져온다.
```
// views/lotto.js
export const getLottoPurchasePrice = () => Number($(SELECTOR.PURCHASE_PRICE_INPUT).value);

// eventHandlers/lotto.js
export const getLottoPurchaseCount = () => {
  return getLottoPurchasePrice() / LOTTO.PRICE;
};
```
어떠한 접근 방식이 더 괜찮은 것일지 궁금합니다.
지금 생각하기에는 2번 처럼 접근하면 view에 의존적이기 때문에 view에 변화가 생기면 함수가 깨지게 되어 1번 처럼 작성하는 게 괜찮을 것 같습니다. 1번은 또 순수 함수이기 때문에 테스트하기에 용이하고 사이드 이펙트가 없을 것 같습니다.

## 4. validation 조건이 많아질 경우, 예외 처리 

### validation 조건이 많아질 경우
현재는 아래와 같이 사용자가 입력한 로또 구입 금액을 validation 하고 있습니다.

```
// eventHandlers/lotto.js
try {
  const lottoPurchasePrice = getLottoPurchasePrice();

  if (validation.isZeroNumber(lottoPurchasePrice)) {
    throw Error(ERROR_MESSAGE.INVALID_ZERO_LOTTO_PRICE);
  }

  if (!validation.isPositiveNumber(lottoPurchasePrice)) {
    throw Error(ERROR_MESSAGE.INVALID_NEGATIVE_LOTTO_PRICE);
  }

  if (!validation.isRemainderZero(lottoPurchasePrice, LOTTO.PRICE)) {
    throw Error(ERROR_MESSAGE.INVALID_LOTTO_PRICE_UNIT);
  }
...
```
근데 이렇게 작성하면 만약 validation이 복잡해질수록 if문이 너무 쌓일 것 같아서 아예 검증하는 함수를 따로 작성하면 괜찮을 것 같다는 생각이 들었습니다. 그래서 utils/validation에 로또 구입 금액을 검증하는 함수를 아래와 같이 작성하고
```
// utils/validation.js
import { ERROR_MESSAGE, LOTTO } from '../constants/index.js';

const isPositiveNumber = (number) => number > 0;

const isZeroNumber = (number) => number === 0;

const isRemainderZero = (number, unit) => number % unit === 0;

export const isValidLottoPurchasePrice = (lottoPurchasePrice) => {
  if (isZeroNumber(lottoPurchasePrice)) {
    throw Error(ERROR_MESSAGE.INVALID_ZERO_LOTTO_PRICE);
  }

  if (!isPositiveNumber(lottoPurchasePrice)) {
    throw Error(ERROR_MESSAGE.INVALID_NEGATIVE_LOTTO_PRICE);
  }

  if (!isRemainderZero(lottoPurchasePrice, LOTTO.PRICE)) {
    throw Error(ERROR_MESSAGE.INVALID_LOTTO_PRICE_UNIT);
  }
};
```
검증하는 쪽에서는 아래와 같이 작성해보았습니다. 이렇게 작성하는게 괜찮을까요?
```
// eventHandlers/lotto.js
try {
  const lottoPurchasePrice = getLottoPurchasePrice();

  if (isValidLottoPurchasePrice(lottoPurchasePrice)) return;

  const lottoPurchaseCount = getLottoPurchaseCount(lottoPurchasePrice);

  renderLottoPurchaseCountText(lottoPurchaseCount);
  renderLottoIcons(lottoPurchaseCount);

  showPurchasedLotto();
  showLottoResultForm();
} catch (error) {
  console.error(error);
  alert(error.message);
}
```
### 예외 처리
사용자가 입력하는 로또 구입 금액에 대해 예외처리를 할 때 현재는 아래의 경우에 에러를 던지고 있습니다.
1. 음수일때
2. 0일때
3. 1000의 단위로 입력이 되지 않았을 때

그런데 생각해보니 아무 값도 입력하지 않고 확인 버튼을 누를 경우에도 처리를 해줘야 할 것 같습니다.
현재는 아무 값도 입력하지 않고(빈 문자열) 확인 버튼을 누르면 2번에 해당하는 조건에 해당됩니다.
if (lottoPurchasePrice === 0) // 빈 문자열의 경우 Number('')가 되어 lottoPurchasePrice의 값은 0이 된다.

따라서 현재는 에러 메시지로 '로또 구입 금액에 0원은 입력할 수 없습니다.' 를 사용자에게 출력해주는데
아무 값도 입력하지 않고 확인 버튼을 누르는 경우에도 '금액을 입력하고 확인 버튼을 눌러주세요'와 같은 별개의
메시지를 출력해주는게 괜찮을까요?

여쭤보고 싶은게 너무 많네욥 😄 미리 감사합니다!

2022-11-15 15:46 UTC, Tanney-102 commented on src/js/service/lotto.js
> +};
말씀하신 가독성 측면도 중요하지만 '가변 변수'를 '절차적'으로 수정하는 과정을 제거해보자는 의도였습니다!
사실 변수하나 추가한다고해서 크게 메모리 비용이 늘지는 않습니다. 다만 스코프 내 어디에선가 수정될 목적으로 선언된 변수가 늘어나는 건, 그만큼 명령형 코드가 늘어난다는 것을 의미해요. 명령형으로 작성되는 코드는 생각보다 많은 휴먼 에러를 내포합니다. 가독성이 떨어지는 것도 물론이구요! 

이미 잘 추상화 되어있는 내장 메서드를 활용하면 보다 선언적인 코드 작성이 가능합니다. 선언적인 방식은 코드에 신뢰성을 더하고 세부적인 과정보다 코드의 실제 목적에 더 집중할 수 있도록 합니다.
꼭 필요한 경우가 아니라면 명령형으로 변수를 업데이트 하는 방식 보다는 선언적으로 필요한 데이터를 취하는 방식이 좋다고 생각합니다.

2022-11-15 16:08 UTC, Seung-wan commented on src/js/service/lotto.js
> +};
저도 평소에 가능하다면 명령형보다 선언적으로 코드를 짜야한다고 생각하고 있었는데 실제로 작성하는 코드에선 어기고 있었던 것 같습니다. 말씀해주신 키워드들을 보니 팍! 하고 깨닫게 된 것 같습니다. 'generateLottoNumbersToArray 함수를 사용하는 곳에서는 분리를 했으니까 선언적으로 작성이 된거겠지?'까지만 생각하고 실제 내부 구현은 명령형으로 작성이 되어버렸습니다.
이미 추상화 되어있는 내장 메서드를 잘 활용하면서 선언적으로 코드를 작성할 수 있도록 항상 고민해야겠습니다.

'**선언적인 방식은 코드에 신뢰성을 더하고 세부적인 과정보다 코드의 실제 목적에 더 집중할 수 있다.'**

2022-11-15 17:54 UTC, Tanney-102 requested changes
안녕하세요 승완님!
리뷰 내용 잘 반영해주셔서 감사합니다~
코멘트를 통해 생각을 적극적으로 공유해주셔서 재밌게 보았습니다🤗
덕분에 저도 많이 생각할 수 있는 시간이었네요!
아직 고민하고 계신 부분이 많이 있으신 것 같은데 우선 이번 step은 머지해도 좋을 것 같아요! 
다음 step에 고민하신 내용 잘 녹여내 보셨으면 좋겠습니다~
코멘트 확인하시고 리액션 주시면 바로 머지할게요~

질문에 답변드립니다.

### 입력값 자료형 변환 시점
이미 답을 가지고 계신 것 같아요~
입력이 들어온 순간에 필요에 맞게 가공하여 저장하는 게 좋다고 생각합니다.


### cypress 폴더명 변경
v11 기준으로 e2e와 component 만 test type으로 지원하는 걸로 보입니다..!(제가 못 찾은 걸수도..)
cypress에서 제공하는 [unit test example](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/unit-testing__application-code/cypress/e2e/unit_test_application_code_spec.cy.js)도 e2e 폴더 아래 있는 걸로보아 별다른 방법은 없어 보입니다😢 우선 다음 스텝부터는 e2e 위주로 테스트를 작성해주시면 좋을 것 같아요. 방법은 같이 조금 더 고민해보시죠!

### 테스트 파일명
유틸성 모듈을 테스트하기 위한 목적이니 도메인보다는 해당 모듈에 의존하는 게 맞다고 생각합니다.
모듈과 테스트 코드의 컨텍스트가 다를 이유가 없는 것 같아요~

### 추상화 레벨, 모듈 분리
lottoPurchaseCount를 얻는 로직을 함수로 분리한다면 결론 내신대로 service 안에서 순수함수로 구현하는 게 좋아보이네요~ 다만 이 부분을 분리하는 게 그렇게 유의미한 추상화인지는 고민이됩니다.
오히려 handleSubmit 함수 안에서 호출 되는 함수들을 잘 그룹화해서 추상화해보는 게 더 의미있지 않나 싶습니다. 지금의 handleSubmit 함수를 간단히 표현하면 다음과 같습니다.

```js
- view에서 lottoPurchasePrice를 얻는다.
- lottoPurchasePrice가 0인지 검사한다.
- lottoPurchasePrice가 음수인지 검사한다.
- lottoPurchasePrice가 LOTTO.PRICE로 나누어 떨어지는지 검사한다.
- lottoPurchaseCount를 계산한다.
- countText를 그린다.
- lottoIcon을 그린다.
...
```

이 함수를 다음과 같이 설계해볼 수 있을 것 같아요..! 
```js
price를 얻는다.
price를 검사한다.
로또 결과 화면을 그린다.
```

이걸 실제 코드로 어떻게 작성해볼 수 있을지 다음 스텝에서 고민해보시면 좋겠습니다!

### validation
validation 쪽은 이미 추상화를 고민하고 계셨군요👍
그런데
```js
 if (isInvalidLottoPurchasePrice(lottoPurchasePrice)) return;
```
이 로직은 조금 의아하네요.
validation 함수 안에서 boolean 값을 return 하지 않는데 위 조건문이 의미가 있나요?
필요한 경우 이미 에러를 던지고 있기 때문에 그냥 호출하는 걸로 충분해보입니다.
이름도 is prefix 보다는 assert나 validate 같은 prefix가 어떨지 제안드려 봅니다.

그리고 기왕 추상화 하는 김에..!
다음과 같은 방식도 있습니다.
```js
const assert = (predicate, message) => {
  if (!predicate) {
    throw new Error(message)
  }
}

export const assertLottoPurchasePrice = (price) => {
  assert(price > 0, ERROR_MESSAGE.INVALID_NEGATIVE_LOTTO_PRICE)
  assert(price !== 0, ERROR_MESSAGE.INVALID_ZERO_LOTTO_PRICE)
  assert(price % LOTTO.PRICE === 0, ERROR_MESSAGE.INVALID_LOTTO_PRICE_UNIT)
};
```

### 예외 처리
price === 0과 입력자체를 안한 것은 분명 다른 behavior이기에 에러처리도 다르게 해주면 어떨까 싶어요~ 에러 메시지를 추가하는 것도 좋고 입력이 없을 때는 button을 disabled 상태가 되도록 하는 방법도 있습니다.(form submit도 동작하지 않아야겠죠?) 어떤 UX가 더 좋을지 고민해보시면 좋겠네요!

2022-11-16 00:32 UTC, Tanney-102 approved these changes
고생많으셨습니다! 다음스텝에서 뵈어요~

2022-11-16 00:33 UTC, merged