[클린코드 4기 이상훈] 로또 미션 STEP1
next-step/js-lotto pull request #163
Opened 2022-11-14 12:14 UTC by sanghunlee-711

안녕하세요 리뷰어님!

로또 1단계 미션을 진행하였습니다.

아래 질문사항 참고하시면서 리뷰 해주시면 감사드리겠습니다!

추가로 난수 생성 및 중복검사에 테스트가 필요할 것 같아 jest도 간단하게 사용하였으니 참고부탁드립니다 😅

## 질문사항
- 랜덤으로 생성된 숫자들의 각 중복 케이스를 어떻게 확인하면 좋을 지 궁금합니다.
  - 현재는 이중반복문을 돌면서 set 자료형을 통해 중복이 있는 경우가 되면 해당 인덱스의 값을 null로 바꾼 뒤 전체 필터링을 걸고 재귀를 이용해 판단하고 있습니다. 일단 이중반복문이 너무 마음에 안들지만 당장 생각나는게 저 정도 수준이라.. 혹시 좋은 의견있으시면 꼭 조언 부탁드립니다!
- 토글버튼에 별도로 이벤트 위임을 달고 있는데 $target에서 한번의 회문으로만 달 수 있을 좋은 방법이 있을지 좋은 생각이 있으시다면 조언 부탁드립니다

# :dart: 기능 요구사항
- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x] 소비자는 자동 구매를 할 수 있어야 한다.
- [x] 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.

:bar_chart: 테스트 요구사항
- [x] 위 기능들이 정상적으로 동작하는지 Cypress를 이용해 테스트한다.

2022-11-16 20:55 UTC, EungyuCho requested changes
안녕하세요 상훈님~
테스트에서 context로 테스트의 관심사를 묶어주셔서 보기 편했어요~
jest로 로직 테스트까지 해주신점도 인상적이었구요 고생하셨어요!

> 랜덤으로 생성된 숫자들의 각 중복 케이스를 어떻게 확인하면 좋을 지 궁금합니다.
현재는 이중반복문을 돌면서 set 자료형을 통해 중복이 있는 경우가 되면 해당 인덱스의 값을 null로 바꾼 뒤 전체 필터링을 걸고 재귀를 이용해 판단하고 있습니다. 일단 이중반복문이 너무 마음에 안들지만 당장 생각나는게 저 정도 수준이라.. 혹시 좋은 의견있으시면 꼭 조언 부탁드립니다!

요것은 코멘트에서 달아드렸지만 조금 요구사항을 잘못봐주신 것 같아요 😢 
우선 의도하신대로 로또마다 중복을 체크하는 방식으로 구현을 한다면 순회 횟수 자체를 줄일수는 없어보여요 💦 💦
 
순회 횟수 자체는 줄일 수 없겠지만 조금 이해하기 쉽고 안전하게 배열을 다루는 방식을 코멘트로 남겨드렸는데 확인해보시면 좋을 것 같습니다 :)

> 토글버튼에 별도로 이벤트 위임을 달고 있는데 $target에서 한번의 회문으로만 달 수 있을 좋은 방법이 있을지 좋은 생각이 있으시다면 조언 부탁드립니다

요것도 코멘트에서 해결이 되었다고 생각했는데 혹시 적어주신 부분이 해결이 안되었다면 다시 말씀해주세요 🙇 

UX나 네이밍 관련해서 코멘트를 많이 달아드렸는데 한번 확인해주시고 다시 리뷰요청 부탁드릴게요!

2022-11-16 20:55 UTC, EungyuCho commented on src/js/lotto.js
> +    const IS_CONFIRM =
변수를 작성하실 때 UpperCase로 작성하시는 기준이 있을까요? 👀

2022-11-16 20:55 UTC, EungyuCho commented on src/js/lotto.js
> +  }
앱을 상태 기반으로 렌더링을 선택해주신 배경이 궁금해요

2022-11-16 20:55 UTC, EungyuCho commented on src/utils/index.js
> +    throw new Error('난수생성을 위해 1000원 단위로 입력되어야 합니다.');
에러메세지가 따로 contants로 분리해서 관리하면 테스트나 변경이 있을 때 보수하기 편할거에요

2022-11-16 20:55 UTC, EungyuCho commented on src/js/lotto.js
> +    const wrapper = this.$target.querySelector('#purchased-result');
유동적으로 생성되거나 변경되지 않는 element는 생성자에서 초기화해서 가지고 있는게 더 효율적이지 않을까요?

2022-11-16 20:55 UTC, EungyuCho commented on cypress/e2e/lotto.cy.js
> +      cy.get($lottoInput).should('exist');
[custom commands](https://docs.cypress.io/api/cypress-api/custom-commands)를 통해서 테스트 함수를 선언적으로 작성해봅시다~

그러면 불필요한 변수 선언들도 제거할 수 있어보여요~

2022-11-16 20:55 UTC, EungyuCho commented on cypress/e2e/lotto.cy.js
> +      TYPE.forEach((eachTyping) => {
1번만 검증해도 충분할 것 같아요
forEach가 들어가니 검증이 아닌 구현이라는 맥락이 끼어든 느낌이 들기도 하구요!

2022-11-16 20:55 UTC, EungyuCho commented on cypress/e2e/lotto.cy.js
> +  context('로또 1장의 가격은 1,000원이다.', () => {
context로 묶은 테스트들이 해당 context에 적어주신 메세지의 역할을 하고 있을까요?
입력창에 대한 context를 만드는게 더 적절해보여요

2022-11-16 20:55 UTC, EungyuCho commented on cypress/e2e/lotto.cy.js
> +    };
함수는 한가지 역할만 하도록 작성하는걸 권장드려요! [참고](https://github.com/qkraudghgh/clean-code-javascript-ko#%ED%95%A8%EC%88%98%EB%8A%94-%EB%8B%A8%EC%9D%BC-%ED%96%89%EB%8F%99%EC%9D%84-%EC%B6%94%EC%83%81%ED%99%94-%ED%95%B4%EC%95%BC%ED%95%A9%EB%8B%88%EB%8B%A4)

2022-11-16 20:55 UTC, EungyuCho commented on index.html
> +              min="1000" max="100000" />
(UX) 입력창에서 엔터를 치면 로또가 구매가 될것이라 기대했는데 페이지가 리로드 되었어요

2022-11-16 20:55 UTC, EungyuCho commented on cypress/e2e/lotto.cy.js
> +      const TYPE = '5000';
Type보다 PurchasePrice같은 네이밍이 테스트를 표현하는데 더 적절해보여요

2022-11-16 20:55 UTC, EungyuCho commented on src/utils/index.js
> +        copy[j].every((number2) => eachNumbersSetI.has(number2));
요구사항은 아니지만 두 조건 중 하나만 검증해도 충분하지 않나요..??

2022-11-16 20:55 UTC, EungyuCho commented on src/utils/index.js
> +  copy = copy.filter((el) => Boolean(el));
```suggestion
  const verifiedLottoNumbers = randomNumberArray.map((currentRow, rowIndex) => {
    const currentSet = new Set(currentRow);

    for (
      let start = rowIndex + 1;
      start < randomNumberArray.length;
      start += 1
    ) {
      const isDuplicated = randomNumberArray[start].every(currentNumber =>
        currentSet.has(currentNumber)
      );

      if (isDuplicated) {
        return { isDuplicated, numbers: currentRow };
      }
    }

    return { isDuplicated: false, numbers: currentRow };
  });

  copy = verifiedLottoNumbers
    .filter(({ isDuplicated }) => isDuplicated === false)
    .map(({ numbers }) => numbers);
```
요구사항은 아니지만.. 요렇게 변경해보면 어떨까요?

2022-11-17 01:02 UTC, sanghunlee-711 commented on src/utils/index.js
> +};
그러네요 ㅎㅎ.. 로또를 안산지 너무 오래되서 의미를 제대로 이해 못한 것 같습니다 🥲..
어느 가게에서 로또를 자동으로 여러장을 샀을때 중복된 케이스가 나올 수도 있는데 말이죠 ..
로또를 좀 사야겠습니다 ㅎ

2022-11-17 01:05 UTC, sanghunlee-711 commented on src/utils/index.js
> +      if (DUPLICATE_CONDITION) copy[i] = null;
아마 이제 사용되지 않을 util이라 의미가 없긴하지만..
이야기 해주신부분이 맞네요. 
회문을 돌다 아래의 경우가 되어을때 copy[i]가 null이 되는 경우 배열이 아니므로 메서드 호출에 런타임 에러가 날 것 같아요

조언 감사합니다 :)
```javascript
[
        [1, 2, 3, 4, 5, 6],
        [13, 14, 15, 16, 17, 18],
        null,
        [7, 8, 9, 10, 11, 12],
      ];
```

2022-11-17 01:06 UTC, sanghunlee-711 commented on src/js/lotto.js
> +      window.alert('로또 구입 금액을 1,000원 단위로 입력해 주세요.');
오 좋은 것 같습니다 놓쳤던 부분이네요 테스트케이스 작성과 조건을 추가해보겠습니다!

2022-11-17 01:06 UTC, sanghunlee-711 commented on src/js/lotto.js
> +      this.state.moneyAmount >= 1000 && this.state.moneyAmount <= 100000;
좋습니다 :) MIN_VALUE, MAX_VALUE로 분리해볼게요!

2022-11-17 01:11 UTC, sanghunlee-711 commented on src/js/lotto.js
> +    const IS_CONFIRM =
사실 조건에 해당하는 경우 상수라 여겨 큰 생각 없이 UpperCase로 작성하였습니다만.. 
코멘트를 보고 생각을 좀 해봤을때 변수가 합쳐진 조건의 경우 상수라 여겨 UpperCase로 작성해도 괜찮을지 의문이 드네요 🧐..

혹시 조건을 변수로 두실 때 특별히 가지고 계신 네이밍 컨벤션이 있으시면 공유 부탁드려도 될까요?

2022-11-17 01:13 UTC, sanghunlee-711 commented on src/js/lotto.js
> +  }
함수별 역할의 분리, 하나의 역할을 가져야한다는 생각과 렌더링에 필요한 조건을 변수로 관리하게 되며 state기반의 렌더링이 구현에 필요한 가장 적합한 구현 방식이라고 생각하였습니다 :)

2022-11-17 01:26 UTC, sanghunlee-711 commented on src/js/lotto.js
> +    const wrapper = this.$target.querySelector('#purchased-result');
음 그런관점에서 보면 맞는 것 같습니다. 변경될 여지가 없는 요소인데 굳이 함수안에서 변수로 선언할 필요가 없는 것 같네요!

2022-11-17 01:29 UTC, sanghunlee-711 commented on cypress/e2e/lotto.cy.js
> +      cy.get($lottoInput).should('exist');
커스텀 커맨드는 좋은 제안이신 것 같습니다! 

논외로 질문을 좀 드려도 될까요?

현업에서 Cypress를 사용하면서 커스텀 커맨드를 종종 사용해왔는데 프로젝트가 커질때마다 하나의 파일에 여러가지 커맨드가 들어가 관리가 힘들었던 경험이 있었습니다 🥲. E2E테스트를 각 서브 도메인 관점에서 진행한다고 하면 각 커맨드파일을 따로 나눠서 관리하시는 편인가요 ??.. 혹시 관리팁같은게 있으시면 공유 부탁드립니다!

2022-11-17 01:31 UTC, sanghunlee-711 commented on cypress/e2e/lotto.cy.js
> +  context('로또 1장의 가격은 1,000원이다.', () => {
그러네요 이 부분은 사실 요구사항 리스트에서 각 부분을 context로 긁어와 케이스들을 만들다 보니 변경하지 않은 것 같습니다 ㅎ.. 의미있는 텍스트로 변경하는게 좋을 것 같네요

2022-11-17 01:31 UTC, sanghunlee-711 commented on index.html
> +              min="1000" max="100000" />
이 부분은 한번 확인해볼게요!

2022-11-18 04:25 UTC, sanghunlee-711 commented on src/utils/index.js
> +};
https://github.com/next-step/js-lotto/pull/163#discussion_r1023191809
에 대한 리팩토링 진행하였습니다!
while문을 사용하였는데 혹시 메서드를 활용한 더 좋은 방법이 생각나시면 의견공유 부탁드립니다 :)

2022-11-18 04:26 UTC, sanghunlee-711 commented on src/utils/index.js
> +  return randomNumberArray;
https://github.com/next-step/js-lotto/pull/163#discussion_r1024495091
에서 제안해주신 로직을 거의 가져다 쓴 것 같습니다 ㅎㅎ..
map을 통해서 적절한 배열 변환이 효율적인 것 같아 그대로 사용하였습니다.

실제로 앱상에서 사용되지 않는 유틸이지만 연습겸 작성해서 코드에 남겨놓았습니다. 다음 반영사항 때 해당부분 지우도록 하겠습니다!

2022-11-18 04:27 UTC, sanghunlee-711 commented on src/css/ui/modules/list.css
> +.lotto-list {
https://github.com/next-step/js-lotto/pull/163#discussion_r1023196556
에서 이야기해주신 리스트 스타일 반영위해 스타일을 별도 추가했습니다

2022-11-18 04:29 UTC, sanghunlee-711 commented on cypress/e2e/lotto.cy.js
> +    });
https://github.com/next-step/js-lotto/pull/163#discussion_r1023199067
에서 이야기해주신 것 처럼 에러핸들링을 추가하여보았습니다

2022-11-18 04:30 UTC, sanghunlee-711 commented on src/js/lotto.js
> +    });
https://github.com/next-step/js-lotto/pull/163#discussion_r1023220592
조언해주신대로 하나의 이벤트로만 받아보았습니다 :)

2022-11-18 04:31 UTC, sanghunlee-711 commented on src/js/lotto.js
> +    this.$target.addEventListener('keydown', (event) => {
https://github.com/next-step/js-lotto/pull/163#discussion_r1024481917
여기서 이야기해주신 것처럼 `form` 태그의 기본적인 동작으로 인해  리로드 되는 현상이 있어 `e.preventDefault()` 와 기존의 onConfirm() 메서드를 활용해서 onEnter를 추가했습니다

2022-11-18 15:53 UTC, EungyuCho commented on src/js/lotto.js
> +    const IS_CONFIRM =
저는 조건이라도 지역변수는 항상 lowercase로 작성하고 있어요~ (대부분 지역변수를 lowercase로 작성할거에요)
Uppercase로 작성하다보면 외부에서 선언되었다고 착각할 여지가 있어보여서 lowercase로 작성해보는걸 권유드리려했어요 🙏

2022-11-18 16:02 UTC, EungyuCho commented on cypress/e2e/lotto.cy.js
> +      cy.get($lottoInput).should('exist');
현업에서 cypress를 다뤄본적은 없지만 상훈님 같은 상황이라면 도메인별로 분리할 것 같아요.
테스트 파일은 아니지만.. 저도 현업에서도 프로젝트 규모가 커지면서 작게 프로젝트 하던때와 같은 폴더구조로는 관리가 너무 힘들어진다고 똑같이 느꼈어요 그래서 현재는 모든 파일들을 도메인 기준으로 분리해서 작성하고 있어요.

도메인이 명확한 경우에는 도메인폴더에, 두 도메인 이상 기능을 공유하는 경우에는 common폴더를 만들어서 하위 테스트 파일을 만들어줄 것 같아요.

2022-11-18 16:17 UTC, EungyuCho approved these changes
상훈님 추가로 반영해주신 부분 잘 봤습니다 😄 

한번 쭉 살펴봤는데.. 코멘트 드릴만한 부분이 거의 없네요 ㅎㅎ;
질문주신 부분과 로또를 생성하는 부분에서 더 쉬운코드와 도전과제 비스무리한 코멘트를 달았는데 관심있으시면 한번 확인해주세요!

바로 Step2로 넘어가시죠! 고생하셨어요  👏

2022-11-18 16:17 UTC, EungyuCho commented on src/utils/index.js
> +  return randomNumberArray;
```javascript
 if (isDuplicated) return { isDuplicated: true, numbers: currentRow };
```
반환값을 true를 명시적으로 적어주신 디테일 👍👍

2022-11-18 16:17 UTC, EungyuCho commented on src/utils/index.js
> +};
```javascript
function makeLottoNumber() {
  const numberSet = new Set();
  
  while (numberSet.size < 6) { // 6은 상수로 바꾸면 좋을거같아요
    const randomNumber = Math.floor(Math.random() * 45 + 1); // 랜덤값 구하는 로직도 별도 함수로 빼면 좋을 것 같아요
    numberSet.add(randomNumber);
  }
  
  return [...numberSet];
}
```
이렇게 짜는것도 방법이겠네요 👀 

Too much지만 while을 사용하지 않고 for문으로 6번의 순회로 중복되지 않는 번호를 가져오는 방법도 있는데 관심있다면 도전해보셔도 좋아요

2022-11-18 16:17 UTC, merged