[클린코드 4기 최호중] 로또 미션 STEP1
next-step/js-lotto pull request #165
Opened 2022-11-14 13:46 UTC by sannimdev

안녕하세요 리뷰어님!
로또 1단계 미션을 진행하였습니다.

## 테스트에서 궁금한 부분

- 현재는 cypress에서 data속성을 이용하여 해당 개체(입력상자 등)를 인식하고 있습니다. 그런데 `복권 금액 입력 상자`와 같은 항목은 자바스크립트 코드에서도 다뤄야 하는 개체이기 때문에 특정할 수 있는 class를 가집니다. 이러한 개체들은 굳이 `data-cy` 속성보다는 class selector를 통해서 인식하는 방법이 좀 더 바람직할까요?

## 참고사항

- 지금은 index.js를 제외한 모든 자바스크립트 파일이 `/src/js/util` 안에 있습니다. 그래서 정말 기능 구현만을 위한 순수 JS인지 DOM과 같은 view의 영역을 다루는 JS파일인지 분간하기가 힘듭니다. 예를 들어 이곳에서 `LottoBuyer.js`와 `LottoResult.js` 파일은 별도의 모듈로 분리해낼 수 있지만, `Element.js`라거나 `Ticket.js`는 DOM을 조작하는 작업이 든 코드입니다. ui작업을 기준으로 다음번 미션에서 별도의 폴더로 분리하여 제출하려고 합니다.
 
(예정)
<img width="317" alt="image" src="https://user-images.githubusercontent.com/22428471/201675206-6b826dde-8c3b-47e3-9b77-1934e1f5ddf9.png">

## 🎯 기능 요구사항

- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x] 소비자는 자동 구매를 할 수 있어야 한다.
- [x] 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.

## 📊 테스트 요구사항

- [x] 위 기능들이 정상적으로 동작하는지 Cypress를 이용해 테스트한다.

2022-11-15 16:25 UTC, JunilHwang requested changes
안녕하세요 호중님! 로또 미션을 함께하게 된 리뷰어 황준일입니다 🙇‍♂️
먼저 질문에 대한 답변을 드리자면,

> 현재는 cypress에서 data속성을 이용하여 해당 개체(입력상자 등)를 인식하고 있습니다. 그런데 복권 금액 입력 상자와 같은 항목은 자바스크립트 코드에서도 다뤄야 하는 개체이기 때문에 특정할 수 있는 class를 가집니다. 이러한 개체들은 굳이 data-cy 속성보다는 class selector를 통해서 인식하는 방법이 좀 더 바람직할까요?

개인적으로 저는 test를 위해 실행 코드에서 무언가 작업해주는건 지양하는 편입니다. data-cy 또한 마찬가지라고 생각해요! 주어진 코드에 대해 테스트를 하는 방향으로 가는게 적합하지 않을까요!?

---

전체적으로 꼼꼼하게 작성해주셨네요!
배열 메소드 사용법에 대해 공부해서 적용해보시면 더 좋은 퀄리티의 코드가 되리라 생각합니다 ㅎㅎ
자세한 내용은 피드백 내용을 확인 부탁드립니다!

궁금한 점은 언제든 슬랙 혹은 코멘트로 질문 주세요~ 감사합니다 🙇‍♂️

2022-11-15 16:25 UTC, JunilHwang commented on cypress/e2e/dom.cy.js
> +        const myWinnings = [invalidNumber, ...numbers.slice(0, 6)];
보너스 번호를 한 번에 표현하기보단
```js
{
  lotto: [1, 2, 3,4 , 5, 6],
  bonusNumber: 7
}
```
이렇게 표현해주는 자료구조를 하나 만들어서 관리해주면 어떨까요?

2022-11-15 16:25 UTC, JunilHwang commented on package.json
> +    "prettier": "^2.7.1"
eslint와 prettier도 적용해주셨네요 👏👏👏

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/Constant.js
> +};
상수도 네임스페이스로 표현해주셨네요! 무척 보기 좋습니다 👏👏👏

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/Constant.js
> +};
여기서 고민해볼 부분은,
오직 domain에 관련된 상수가 있고
View와 관련된 상수가 있다는 점입니다.
이렇게 다루고 있는 변수의 성격에 따라 파일도 분리해서 관리해주면 어떨까요?

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoBuyer.js
> +  const amount = purchasingAmount / 1000;
TICKET_PRICE라는 상수를 선언했는데 사용하질 않고 있네요 ㅠㅠ

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoBuyer.js
> +}
```js
const lottoNumbers = Array.from({ length: 45 }).map((_, k) => k + 1);
function generateLotto() {
  return lottoNumbers.sort(() => Math.random() - 0.5).slice(0, 6).sort((a, b) => a - b);
}
```
이렇게 미리 1 ~ 45를 정의해놓고 shuffle 해서 사용하면 어떨까요?

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoBuyer.js
> +}
```suggestion
function getUniqueLottoSets(amount, strict = false) {
  const set = new Set();

  while (set.size < amount) {
    const lotto = getRandomNumbers(6);
    if (strict) lotto.sort((a, b) => a - b);
    set.add(lotto.join(LOTTO_DELIMITER));
  }

  return Array.from(set).map((str) => str.split(LOTTO_DELIMITER).map(Number));
}
```
이렇게 표현해도 되겠네요!

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  return [hit, bonusHit];
```suggestion  
  const hit = ticket.filter(lottoNumber => winningSet.has(lottoNumber)).length;
  const bonusHit = winningSet.has(bonusHit);
  return [hit, bonusHit];
```
이렇게 표현할 수 있답니다!

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  const winningSet = new Set([...winningNumbers, bonusNumber]);
```suggestion
const getMyHit = (lotto, winningLotto) => {
```
이렇게 받아올 수 있도록 설계해주면 더 깔끔하지 않을까요!?

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  return result;
배열 메소드(find, filter, map, reduce, some, every, ...)를 최대한 활용해보면 어떨까요?
지금은 직관적으로 이해하기가 무척 어렵네요 ㅠㅠ

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  }
마찬가지로, 여기에도 배열 관련 메소드를 활용해서 리팩토링 해주면 좋을 것 같아요!

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +};
100이라는 숫자도 상수로 관리할 수 있을 것 같아요!

2022-11-15 16:25 UTC, JunilHwang commented on src/js/util/Validator.js
> +export const isUniqueNumbers = (numbers = []) => {
```suggestion
export const isUniqueNumbers = (numbers) => {
```
default 값이 꼭 필요할까요? 오히려 항상 numbers가 있어야 하는게 맞는 것 같아요!

2022-11-15 16:25 UTC, JunilHwang commented on src/js/view/Element.js
> +export const $earningRate = querySelector('span.earning-rate');
Element에 selector 함수도 있고, selector도 있고, Element도 있네요.
이런 경우에는 관심사별로 분리해주는게 좋지 않을까요!?

2022-11-15 16:25 UTC, JunilHwang commented on src/js/view/ui.js
> +    $winningNumbers.forEach(($number) => inputWinningNumbers.push($number.value));
```suggestion
    const inputWinningNumbers = Array.from($winningNumbers).map($number => $number.value);
    const inputBonusNumber = $bonusNumber.value;
```
이렇게 표현해줄 수 있답니다!

2022-11-15 16:25 UTC, JunilHwang commented on src/js/view/ui.js
> +    }
이 부분도 함수로 분리할 수 있겠네요!

2022-11-16 12:22 UTC, sannimdev commented on cypress/e2e/dom.cy.js
> +  };
다음 미션에서도 네이밍할 때 참고하겠습니다!

2022-11-16 12:23 UTC, sannimdev commented on cypress/e2e/dom.cy.js
> +    });
다양한 케이스에 대한 고민을 좀 더 해보겠습니다!
마음이 급해서 STEP2 넘어가기 이전에 테스트 케이스를 리팩터링해야겠다는 생각을 못했습니다 ㅠㅠ
짚어주신 부분 고민하고 넘어갈게요!

2022-11-16 13:12 UTC, sannimdev commented on cypress/e2e/dom.cy.js
> +      cy.get(dom.inputAmount).type('1500');
케이스 대응하여 추가하겠습니다

2022-11-16 13:19 UTC, sannimdev commented on cypress/e2e/dom.cy.js
> +        cy.get(dom.inputBonusNumber).clear().type(bonus);
> 테스트 코드에 이런 로직이 있다면, 무언가 잘못된게 아닐까요?
테스트는 input에 대한 output을 검증하는 과정인데, 이런 함수가 있다는 것 자체가 불필요한 테스트 혹은 적합하지 않은 테스트를 한다고 볼 수 있답니다!

말씀해주신 조언에 따라 output을 검증하기 위해 해당 로직은 제외하여 다시 케이스를 작성해볼게요!

2022-11-16 13:34 UTC, sannimdev commented on src/js/util/LottoBuyer.js
> +  const amount = purchasingAmount / 1000;
STEP2 미션에서 사용 중입니다! 아직 이 코드에는 상수만 작성하고 인용하지 않았습니다 ㅠ

2022-11-19 13:01 UTC, sannimdev commented on src/js/util/LottoBuyer.js
> +}
제안 감사합니다.
제가 나름대로 정한 의미대로 끊어서 작성해볼게요!

2022-11-19 13:05 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  const winningSet = new Set([...winningNumbers, bonusNumber]);
당첨 번호 5개와 보너스 번호 1개가 겹친 경우 혼동이 있을 수 있어 매개변수를 분할하여 받은 것입니다.
다만, tickets와 ticket은 어떤 것을 의미하는지 바로 떠오르지 않기 때문에 lotto, lottos로 명칭을 변경하는 편이 낫겠다는 생각이 들었습니다.

2022-11-19 13:07 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  return result;
저도 이건 항상 드는 고민인데요!
함수형 프로그래밍을 선호하고 배열 메서드를 선호했지만,
때에 따라서는 절차지향적인 프로그래밍이 직관적으로 이해할 수 있겠다 생각이 들어요.
피드백을 과거에 유사한 상황에서 받아 본 경험이 있었기 떄문인데요.
배열 메서드가 워낙 잘 되어 있어서 활용하는 것은 너무 좋다고 생각하지만,
아무래도 익숙지 않고 위와 같은 코드가 더 잘 읽히는 사람들도 있다 보니까 호불호가 걸릴 수 있는 문제일 수도 있다는 생각이 듭니다.

2022-11-19 13:10 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  const prize = { three: 5000, four: 50000, five: 1500000, six: 2000000000, bonus: 30000000 };
저도 프로그래밍에서 반복되지 않도록 상수를 만들어 관리하는 것에 굉장히 많이 공감하는 편인데요!
1회에 한하여 활용될 경우 나중을 대비하여 상수화하는 것은 좋지만,
현재 프로젝트에서는 이 함수 바깥에서 사용될 일이 없어보여서 상수로 관리하지 않고 있었습니다.
혹시라도 리팩터링을 진행하고 STEP3단계까지 진행하면서 이 객체가 다른 곳에서도 쓰일 경우에는 별도의 상수로 관리할게요!

2022-11-19 13:12 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  }
reduce냐 for문이냐.. 
벽붙 벽떨 찍먹 부먹 너무 어려워요!

![image](https://user-images.githubusercontent.com/22428471/202852498-a47b903b-da74-42d0-a769-d29f0f844d00.png)

2022-11-19 13:13 UTC, sannimdev commented on src/js/util/LottoResult.js
> +};
100이라는 숫자나 백분위로 변환하는 수치인 100을 다른 곳에서 사용할 일이 아직은 없어서 관리하지 않고 있었습니다.
이번 미션에서 1회만 참조하게 될 경우에도 상수로 관리함이 바람직할지 고민이에요!

2022-11-19 13:14 UTC, sannimdev commented on src/js/util/Validator.js
> +export const isUniqueNumbers = (numbers = []) => {
요 default값은 함수의 구동을 위해서라기보다는 자바스크립트에서 최대한 타입을 명시하려고 노력한 부분이에요!
타입스크립트처럼 자동완성 기능이 입력된다면 실수를 줄일 수 있지 않을까 해서요!
말씀하신 대로 이곳에서는 항상 numbers라고 하는 배열이 입력되어 들어오는 것이 맞습니다.

2022-11-19 13:16 UTC, sannimdev commented on src/js/util/Validator.js
> +export const isWithInRangedNumber = (numbers = [], greaterThan = 1, lessThan = 45) => {
이곳도 나름대로의 타입을 명시하고자 노력한 부분입니다.
자바스크립트가 약타입 언어이기는 하지만, IDE에서 자동완성 되는 기능을 좀 노려본다면 실수를 줄일 수 있지 않을까 해서요!
타입스크립트가 간절합니다 ㅠ

2022-11-20 06:19 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  const winningSet = new Set([...winningNumbers, bonusNumber]);
`당첨 번호 5개와 보너스 번호 1개가 겹친 경우`

이는 lotto 생성로직에게 책임이 있는게 아닐까요?


const lotto1 = new Lotto(1, 2, 3, 4, 5, 5); -> 오류 발생
const lotto2 = new Lotto(1, 2, 3, 4, 5, 6); -> 통과
new WinningLotto(lotto2, 1); -> 오류 발생

2022-11-20 06:22 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  return result;
배열 메서드의 경우 반복 요소에 대한 역할이 이미 다 존재한답니다!
map -> 새로운 배열을 만들겠다
filter -> 조건에 맡는 배열을 반환하겠다

처럼요!
하지만 for, if의 경우 너무 광범위한 역할을 가지고 있어요.
즉, 코드를 손수 한땀 한땀 읽고 해석해야 어떤 일을 하는지 전체적으로 이해할 수 있게 된답니다!
배열 메소드를 알고 있는 사람과는 이를 토대로 의사소통을 해야 더 효율적으로 할 수 있지 않을까요!?

2022-11-20 06:27 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  }
```js
return Object.value(lottoResult)
.filter(value => value > 0)
.reduce((sum, value) => sum + value, 0);
```
배열 메소드를 쓰게 된다면
"0인 숫자를 제외하고, 나머지를 더한다"
라고 순차적으로 해석이 가능한데 사용하지 않을 이유가 있을까요?

2022-11-20 06:27 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +};
참조 횟수가 중요한게 아니라 이 숫자의 의미를 정의해놓는게 중요하답니다!
@sannimdev

2022-11-20 06:28 UTC, JunilHwang commented on src/js/util/Validator.js
> +export const isUniqueNumbers = (numbers = []) => {
실수가 있다면 오류를 발생시켜서 사용자에게 알려야 하지 않을까요?

2022-11-20 06:29 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  const winningSet = new Set([...winningNumbers, bonusNumber]);
엇.. 이 부분은 제가 코드를 잘못 작성한 듯합니다.
사용자가 생성한 로또 번호 중`당첨번호`와 `보너스 당첨번호`를 각각 몇 개가 일치하는지 카운팅하는 과정인데
불필요하게 set을 만들어서 비교하고 있었습니다.
나머지 피드백 주시는 부분도 검토하여 같이 수정하여 반영할게요!

2022-11-20 06:29 UTC, JunilHwang commented on src/js/util/Validator.js
> +export const isWithInRangedNumber = (numbers = [], greaterThan = 1, lessThan = 45) => {
오히려 이럴 경우 값을 입력하지 않아도 함수를 사용할 수 있기 때문에 또다른 실수를 유발하게 될 수 있어요!
함수에 대한 오류를 IDE나 에디터에서 안내해주지 않을 수 있거든요 ㅠㅠ
타입 때문이라면 차라리 jsdoc을 쓰는게 어떨까요?

2022-11-20 06:40 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  return result;
위와 같은 메서드에서 LottoResult의 유형을 반환한다고 했을 때 활용될 수 있는 메서드는 배열 메서드 중 reduce가 떠오르는데요!
```js
// LottoResult
{ three: 0, four: 0, five: 0, six: 0, bonus: 0 }
```

아래와 같이 배열 메서드를 사용하여 코드를 바꿔보았습니다.
말씀하신 것처럼 for와 if의 경우 너무 광범위한 역할을 가지고 있다고 하셔서 for문의 사용을 지양할 수 있었습니다.
그러나 for문이 빠진다는 점을 제외하면 for문 내에 들어간 로직 자체에는 큰 변화가 없어 보입니다.
이럴 경우에는 제게 답변해주신 내용만으로는 배열 메서드를 익숙해하지 않는 사람에게 `for, if의 경우 너무 광범위한 역할을 가지고 있으니 배열 메서드인 reduce를 씁시다`라고 매력적으로 설득하기에는 역부족이라는 생각이 드는데요.
혹시 다른 의견이 있으시거나 reduce가 아닌 다른 방법으로 고칠 수 있는 부분이 있을까요?

```js
return lottos.reduce(
    (result, lotto) => {
      const [hitCount, bonusHitCount] = getMyHit(lotto, winningNumbers, bonusNumber);
      if (hitCount < 3) return result;
      if (isBonusHit(hitCount, bonusHitCount)) {
        result.bonus += 1;
        return result;
      }
      return (result[NUMBER_DICTIONARY[hitCount]] += 1);
    },
    { three: 0, four: 0, five: 0, six: 0, bonus: 0 }
  );
```

2022-11-20 06:45 UTC, sannimdev commented on src/js/util/Validator.js
> +export const isUniqueNumbers = (numbers = []) => {
넵 이 부분은 jsdoc으로 보완하였습니다

2022-11-20 06:46 UTC, sannimdev commented on src/js/util/LottoResult.js
> +};
숫자의 의미를 정의하는 것이 중요하다는 말씀 기억할게요!

2022-11-20 06:53 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  }
제안해주신 코드 대로 적용할 수는 없었습니다.
왜냐하면, 로또 번호 몇 개를 맞혔는지에 관한 키 값(ex: three, four)이 식별되어야만 하는데요.
Object.value를 쓰게 되면 3개, 4개, 5개, 6개, 5+보너스번호 각각 맞힌 로또 개수는 알 수 있지만, 3개를 3개 맞혔는지 4개를 3개 맞혔는지는 알 수 없어서 당첨금을 계산할 수 없습니다.

그래서 아래와 같이 개선해보도록 하겠습니다.

```js
export const getMyPrizeAmount = (lottoResult = { three: 0, four: 0, five: 0, six: 0, bonus: 0 }) => {
  return Object.keys(lottoResult).reduce((sum, key) => {
    const count = lottoResult[key];
    if (count) {
      return sum + LOTTO_PRIZE[key] * count;
    }
  }, 0);

  // let sum = 0;
  // for (const key of Object.keys(lottoResult)) {
  //   const value = lottoResult[key];
  //   if (value === 0) continue;
  //   sum += prize[key] * value;
  // }
  // return sum;
};
```

2022-11-20 06:57 UTC, sannimdev commented on src/js/util/Validator.js
> +export const isWithInRangedNumber = (numbers = [], greaterThan = 1, lessThan = 45) => {
2022년 11월 19일 코드리뷰를 다시 요청드린 날짜를 기준으로 jsdoc을 이미 적용되어 있습니다!
현실적인 시간의 제약이라는 것이 있고 초반에는 기능을 완성시키고 테스트 개발 등 신경써야 할 부분이 많기 때문에 기술 부채로 남겨 둔 상황이었습니다! 이럴 때는 그 방법이 그나마 유용하겠단 생각이 들더라고요!

2022-11-20 07:09 UTC, JunilHwang approved these changes
안녕하세요 호중님!
피드백 반영 잘 해주셨네요 👍 

먼저 상수에 대해 이야기드리자면,
상수의 경우 "재활용"이 목적이 아닌 "의미 부여"가 목적입니다.
1000 이라는 숫자가 있을 때 
이게 단순히 숫자로 읽힐 때랑 "로또 구매 금액"으로 읽히는건 코드를 해석할 때 의미가 다르니까요!
0이라는 숫자도 이게 단순히 숫자로 읽힐 수도 있지만, 0이 각각의 코드마다 쓰이는 역할이 다를 수 있잖아요?
그래서 숫자에 "의미"를 부여하는 것이 중요하다고 생각해요!

----

그리고 배열 메소드에 대해 고민이 많으신 것 같아요!
저의 의견을 이야기드리자면,

```js
let sum = 0;
for (const key of Object.keys(lottoResult)) {
  const value = lottoResult[key];
  if (value === 0) continue;
  sum += prize[key] * value;
}
```
이 코드에 대해서 해석해보자면
- key 목록을 반복하면서 value 값을 가져오고
- value가 0이면 다음 반복문으로 넘기고
- 그게 아니라면 sum에 value를 더한다
처럼 한땀 한땀 코드를 다 해석해야해요! 코드를 읽는 비용이 무척 크다는거죠
```js
return Object.values(lottoResult)
  .filter(value => value > 0)
  .reduce((sum, value) => sum + value, 0)l
```
이 코드의 경우 `value가 0인 값의 합을 구한다` 라고 직관적으로 해석될 수 있어요!
코드를 읽는 비용 자체가 매우 줄어들지않나요?

반대로 호중님이 생각하시기에 for/if/while 등을 썼을 때의 장점은 뭘까요? 어떤 점이 배열 메소드를 사용하는것보다 더 좋다고 생각하시나요?

----

아직 몇몇 함수에 기본 값이 들어가있는데,
이 함수들이 쓰이는 경우를 생각해보면 어떨까요?
함수에 값을 넘기지 않아도 정상적으로 동작하게 하기 위함일까요?
지금은 대체로 "입력이 정상적으로 이루어져야 하는 경우"를 검증해야 하고, 그렇지 않은 경우에는 오류를 발생시키는 과정이 필요한데 기본값이 있다면 이런 과정 자체가 무의미해지지 않을까요?

혹은 기본값으로 반환하는 경우에 대해 처리하는 로직이 있다면 어떨까요?

---

일단 이번 step은 여기서 마무리하도록 하겠습니다.
남겨놓은 의견은 다음 step 진행하실 때 참고 부탁드립니다 🙏

2022-11-20 07:29 UTC, merged

2022-11-20 07:30 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  return result;
```js
const LottoResult = {
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
  FOUR: 'FOUR',
  FIVE: 'FIVE',
}
const LottoPrizeCondition = {
  [LottoResult.ONE]: { hit: 6, bonus: 0 },
  [LottoResult.TWO]: { hit: 5, bonus: 1 },
  [LottoResult.THREE]: { hit: 5, bonus: 0 },
  [LottoResult.FOUR]: { hit: 4, bonus: 0 },
  [LottoResult.FIV]: { hit: 3, bonus: 0 },
}

const LottoPrize = {
  [LottoResult.ONE]: 2_000_000_000,
  [LottoResult.TWO]: 30_000_000,
  [LottoResult.THREE]: 1_500_000,
  [LottoResult.FOUR]: 50_000,
  [LottoResult.FOUR]: 5_000,
}

const matchLottoPrizeCondition = (prizeCondition, hit, bonus) => prizeCondition.hit === hit && prizeCondition.bonus === bonus;

const computePrizeCountMap = (lottos, winningNumbers = [], bonusNumber) => {
  return lottos
    .map(lotto => getMyHit(lotto, winninNumbers, bonusNumber))
    .map(([hit, bonus]) => Object.entries(LottoPrizeCondition).find(condtion => matchLottoPrizeCondition(condition, hit, bonus)))
    .filter(Boolean)
    .reduce((results, [result]) => {
      results[result] = (results[result] || 0) + 1;
      return results;
    }, {});
}

const computeTotalPrize = (prizeCountMap) => {
  return Object.entries(prizeCountMap).reudce((total, [key, count]) => sum + LottoPrize[key] * count, sum)
}
```

이렇게 자료구조를 같이 활용해보시면 어떨까요!? @sannimdev

2022-11-20 07:32 UTC, sannimdev commented on src/js/util/Util.js
> +export const getNumbers = (array = []) => array.map(Number);
11월 19일 jsdoc을 작성하고 제거하지 않은 잔재인데 다음 PR에서 제거한 내용 반영하겠습니다!

2022-11-20 07:32 UTC, JunilHwang commented on src/js/util/LottoResult.js
> +  }
위의 코멘트 참고해주세요!

2022-11-20 08:14 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  return result;
자료구조도 최대한 배열 메서드를 활용할 수 있는 방안대로 개선해야 배열 메서드를 사용하는 것이 좀 더 수월하네요!

2022-11-20 08:15 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  return result;
절차지향적 로직을 배열 메서드 1개로 변환하는 일대일 대응으로만 생각했는데 여러 배열 메서드를 각기 절차에 맞게 여러 번 활용하는 방법이 있다는 것도 재차 상기하는 편이 좋겠습니다!

2022-11-20 08:37 UTC, sannimdev commented on src/js/util/LottoResult.js
> +  }
[TODO: 자료구조 개선하여 종합적으로 배열 메서드 적용하기](https://github.com/next-step/js-lotto/pull/165#discussion_r1027239573)

2022-11-20 09:32 UTC, sannimdev commented on src/js/util/LottoResult.js
> +};
확장성을 고려한 당첨로직 상수로 선언