[클린코드 4기 박예정] 로또 미션 STEP2
next-step/js-lotto pull request #190
Opened 2022-11-26 08:48 UTC by imgoing222

안녕하세요 리뷰어님!
스텝2까지 오는데 시간이 좀 오래 걸렸네요 ... 😅😅
앗 그리고 커밋이 스텝1이랑 같이 올라가네요...? 다른 방법을 찾아야겠습니다.
11월 23일
d090126c658375a73e477064a829f9c6365f3041 부터가 스텝2 입니다.

우선 이벤트 핸들러의 콜백 함수들이 동작하는 controller 파일을 분리해주었습니다.
모델과 뷰가 연결되어있다고 느껴지는 부분도 제거했습니다.
그리고 로또 모델을 클래스로 관리하기로 결정했습니다.

클래스는 데이터와 이를 조작하는 코드를 하나로 추상화 시킬 수 있는 데이터 타입인데
제 프로젝트에는 로또 데이터가 있고, 로또 데이터를 가지고 조작해주는 코드가 있습니다.
그래서 이렇게 데이터와 데이터를 조작하는 코드를 Lotto라는 클래스 하나로 묶어준다면 모델을 관리하기가 쉽고 가독성이 좋아지겠다고 판단했고, 또 데이터는 private으로 만들어 외부에서 해당 데이터를 참조하면 에러가 발생하게 되므로 의도치 않은 변경을 막을 수 있겠다고 생각했습니다.
그리고 로또 클래스는 실행 시 하나의 인스턴스만 생성되어 계속 사용하면 되겠다고 생각을 해서 싱글톤 패턴을 쓰게 되었습니다.

그리고 난수 생성 시 중복검사 로직을 추가했고, 다른 요구사항들도 구현했습니다.

지금 제가 스스로 코드가 마음에 들지 않는 부분이

1. 다시 시작하기 버튼
controllers 의 `handleRestartButtonClick` 함수가 뭔가 하나하나 다 초기화를 시켜주고 있어서
코드가 좀... 보기에 안 좋다고 생각하는데 어떻게 개선할 수 있을까요?
아예 앱 자체를 다시 실행시키는 방법도 생각을 해봤는데... 그렇게 되면 변경할 부분이 많을 것 같아서 보류해뒀습니다.

2. 로또 모델에서 순위를 정해주는 기능
service/lotto.js 에서 `setRank`라는 메서드를 통해서 결과 당첨 순위를 switch문으로 넣어주고 있습니다.
당장 저거 방법밖에 생각이 안나서 저렇게 작성을 했는데 더 좋은 방법이 있을지 궁금합니다.

코드가 점점 길어지면서 가독성이 떨어지는게 스스로도 느껴지네요😥
설계 문제인 것인지 계속 고민해봤는데 우선 리뷰받고 더 고민하는게 좋을 듯해서 리뷰 요청 드립니다..!

요구사항
- [x] 결과 확인하기 버튼을 누르면 당첨 통계, 수익률을 모달로 확인할 수 있다.
- [x] 로또 당첨 금액은 고정되어 있는 것으로 가정한다.
- [x] 다시 시작하기 버튼을 누르면 초기화 되서 다시 구매를 시작할 수 있다.

2022-11-28 01:49 UTC, InSeong-So requested changes
안녕하세요, 예정님! STEP2 수행하느라 고생하셨어요!
스쿼시 머지를 했기 때문에 커밋 이력이 같이 올라가는 것으로 보일거에요. 실제 리뷰하는 파일은 최종 이력만 비교하기 때문에 괜찮습니다😊

딱 원하시는 내용을 리뷰로 남겨드린 것 같으니 확인해보시고 궁금하거나 이상한 부분이 있다면 꼭 이야기해주세요. 로직 간 의존성이나 클린 코드에 대한 고민을 지속적으로 해주시는 게 코드에 많이 녹아있어서 좋은 방향으로 많이 반영되는 것 같아요.

한 번 수정해보시고, 다시 리뷰 요청해주시면 감사하겠습니다🙇‍♂️

2022-11-28 01:49 UTC, InSeong-So commented on cypress/e2e/lotto.cy.js
> +		const $showResultButton = cy.get('[data-cy="showResultButton"]');
`'[data-cy="purchaseInput"]'`같은 셀렉터는 상수화시켜도 좋을 것 같아요!

2022-11-28 01:49 UTC, InSeong-So commented on cypress/e2e/lotto.cy.js
> +		});
중복된 케이스에 대한 테스트케이스도 필요해보이네요🤔

2022-11-28 01:49 UTC, InSeong-So commented on index.html
>  									/>
👍

2022-11-28 01:49 UTC, InSeong-So commented on src/js/constants/lotto.js
> +	},
[숫자 구분 기호 (Numeric Separators)](https://helloworldjavascript.net/pages/130-number.html)라는 것이 있습니다. 이를 활용해보면 어떨까요?!

2022-11-28 01:49 UTC, InSeong-So commented on src/js/controllers.js
> +import { LOTTO } from "./constants/lotto.js";
`./constants` 로 합칠 수 있지 않을까요?

```js
import { LOTTO, ERROR_MESSAGE } from "./constants/index.js";
```

2022-11-28 01:49 UTC, InSeong-So commented on src/js/controllers.js
> +};
오... `$allWinningNumberInputs`는 다른 모듈에서 참조하는 변수네요. 이러면 사이드 이펙트가 발생합니다...! 해당 엘리먼트로 제어하는 무언가가 여러 곳에 파편화되어 있다면 유지보수를 하는 부분도 점점 많아지겠죠🥲

해당 파일에 존재하는 코드가 `/view/elements.js`와 긴밀하게 의존하는데, 쿼리한 변수를 그대로 가져다 쓰는 것은... 위와 같은 문제가 발생합니다. 어떻게 MVC 형태로 쪼갤 수 있을까요?

2022-11-28 01:49 UTC, InSeong-So commented on src/js/controllers.js
> +	);
🥲 이런 형태의 사이드이펙트가 발생하면 어느 시점에 어떤 이벤트로 인해 상태가 변경되는지 확인하기 힘들어집니다. 앞서 언급한 내용의 연장선이에요.

2022-11-28 01:49 UTC, InSeong-So commented on src/js/controllers.js
> +	changeInnerText($totalLottoCount, 0);
뭔가 많은 변수들을 참조 및 수정하거나 함수를 호출하는데, `lotto.initialize()` 로도 대부분의 로직을 제어할 수 있을 것 같은 네이밍입니다. 좀 더 직관적으로 각 함수와 변수를 유기적이게 묶을 수 없을까요?

2022-11-28 01:49 UTC, InSeong-So commented on src/js/service/lotto.js
> +	}
```js
this.#lottos = Array.from({length: number}, createRandomNumbers);
this.#inputTotal += number * 1000;
return this.#lottos;
```
로 축약할 수 있겠네요! `#lottos`는 멤버 변수이므로 반환 값을 활용하지 않아도 될 것 같네요😊

2022-11-28 01:49 UTC, InSeong-So commented on src/js/service/lotto.js
> +			: (this.#bonusNumber = numbers);
`this.#bonusNumber`의 존재 의의가 궁금하네요! 많이 쓰이는 곳이 없다면 제거하는 방향도 고민해보면 좋겠어요😇

2022-11-28 01:49 UTC, InSeong-So commented on src/js/service/lotto.js
> +		return [this.#result, this.#earningTotal, this.#inputTotal];
`for...of`는 이터러블한 객체를 특수하게 핸들링할 때 사용하도록 의식하는게 좋습니다. 저희에겐 배열 고차함수가 존재하니까요! `forEach`로 바꾸면 어떨까요?

그리고 배열로 반환하는 케이스는 예정님만의 컨벤션이 있을까요? 만약 사용자라면 어느 위치에 어떤 변수가 오는지 알기 위해서 Lotto 클래스 파일을 확인해야할 것 같거든요🥲

2022-11-28 01:49 UTC, InSeong-So commented on src/js/service/lotto.js
> +		).length;
이렇게 줄일 수도 있겠네요!
```js
const {length: sameNumberCount} = lottoNumbers.filter(this.#winningNumbers.includes);
```

2022-11-28 01:49 UTC, InSeong-So commented on src/js/service/lotto.js
> +		}
`switch-case` 문보다는 객체를 활용해보면 어떨까요? lookup table을 찾아보고 적용해보시면 좋을 것 같네요😁

2022-11-28 01:49 UTC, InSeong-So commented on src/js/service/lotto.js
> +	}
함수로 선언할 필요가 있는 연산일까요?!

2022-11-28 01:49 UTC, InSeong-So commented on src/js/utils/operate.js
> +
👍 이 함수도 export하면 어떨까요? 테스트케이스에서 동일한 코드를 본 것 같네요!

2022-11-28 01:49 UTC, InSeong-So commented on src/js/utils/operate.js
>  	}
```js
while(true) { ... ]
```
현재에서는 금기시되는 코드입니다. 특정 조건을 명확히 부여하는 것이 while 스코프 내부를 해석하지 않아도 이해할 수 있어서 좋아요! 중복 난수를 여기서 처리하는 것 같은데 다른 형태로 접근하면 어떨까요? 자바스크립트의 자료구조를 고민해보면 좋겠습니다!

2022-11-28 01:49 UTC, InSeong-So commented on src/js/view/templates.js
> +  );
map을 써도 되지 않을까요?!

2022-12-11 13:54 UTC, imgoing222 commented on src/js/view/templates.js
> +  );
map을 하고 join으로 합쳐서 보내라는 말씀이실까요...?! 👀
reduce를 쓰면 한번에 해결될 것 같아서 reduce를 사용했는데 map을 사용하는것이 더 바람직할까요??

2022-12-11 14:19 UTC, imgoing222 commented on src/js/utils/operate.js
>  	}
네! set을 이용해서 리팩토링 해보았습니다!

2022-12-11 16:10 UTC, imgoing222 commented on src/js/service/lotto.js
> +		}
네! https://github.com/next-step/js-lotto/pull/190/commits/688463eb3867b4fdc21151dd272beda2da7e987b 이렇게 리팩토링 해보았습니다

2022-12-11 16:11 UTC, imgoing222 commented on src/js/constants/lotto.js
> +	},
감사합니다! https://github.com/next-step/js-lotto/pull/190/commits/8f60dd59e5646213d29aef0c5eff2a1c7c57349d

2022-12-11 16:12 UTC, imgoing222 commented on src/js/controllers.js
> +import { LOTTO } from "./constants/lotto.js";
감사합니다!! https://github.com/next-step/js-lotto/pull/190/commits/ded726ef6b8038257ee4653fda7c51aded7da853

2022-12-11 16:54 UTC, imgoing222 commented on src/js/service/lotto.js
> +		return [this.#result, this.#earningTotal, this.#inputTotal];
객체로 반환하고 forEach문 사용하도록 리팩토링 했습니다! https://github.com/next-step/js-lotto/pull/190/commits/6903531647147fbe0d84877ec6134bb8577494a3

2022-12-11 16:55 UTC, imgoing222 commented on src/js/service/lotto.js
> +			: (this.#bonusNumber = numbers);
2등을 가려낼때 bonusNumber가 필요해서.... 제거할 수는 없을 듯 합니다ㅠㅠ

2022-12-11 17:09 UTC, imgoing222 commented on src/js/service/lotto.js
> +	}
오..! 굳이 함수로 선언하지 않아도 복잡하지 않고 의도가 드러나보이는 거 같아서 그냥 연산하도록 바꿨습니당 😁

2022-12-11 17:47 UTC, imgoing222 commented on cypress/e2e/lotto.cy.js
> +		const $showResultButton = cy.get('[data-cy="showResultButton"]');
https://github.com/next-step/js-lotto/pull/190/commits/82ab44f7194bbf5801b11f9eb93227fdc469a666

2022-12-11 17:49 UTC, imgoing222 commented on cypress/e2e/lotto.cy.js
> +		});
e2e 테스트는 사용자가 실제 서비스를 사용하듯이 구현해야한다고 알고 있습니다!
중복 케이스를 검증하는 부분이 여기에 들어가도 괜찮을까요...?! 아니면 따로 로또 모델을 테스트 해주는 파일을 만들어야 할까요??

2022-12-11 18:01 UTC, imgoing222 commented
안녕하세요 인성님!! 😀
몸이 꽤 오랫동안 안 좋아서 회복하느라 지금 엄청 밀렸네요 ㅠㅠㅠ 다시 매일 꾸준히 해나가야겠습니다~!!

체크해주신 부분 거의 다 리팩토링 해봤고 
인성님 의견을 조금 더 듣고 고치고 싶은 부분은 대댓글로 달아뒀습니다!

적어주신 리뷰중에 controller에서 view와 긴밀하게 의존한다고 하셔서 이렇게... 저렇게... 해보았는데
최선이 아닌 것 같다는 생각이 듭니다
보시고 혹시 이상한 방향으로 제가 리팩토링 한거면 조금 더 힌트를 주시면 다시 해보겠습니다 😅

그리고 궁금한 점이 있는데
이렇게 구현해야할 프로젝트를 보시면 인성님은 어떤 사고흐름으로 구조를 설계하시는지 궁금합니다.
'이 프로젝트가 구현해야할 기능은 이러이러하니까 어떠어떠한 패턴을 사용해서 구현해볼까...?'
이렇게 생각하시나요??

저는 그때 class들을 전체적으로 제거하면서
코드를 한곳에 몰아넣자니 너무 복잡해진다고 생각해 가독성을 높여보려고 MVC를 이 프로젝트에서 도입했는데
괜찮은 선택이였는지 모르겠습니다...!

아 그리고 패턴에 대해서 공부를 좀 했는데 여러가지로 많더라구요
실무에서 자주 사용하거나 꼭 알아야하는...? 혹은 추후 프로젝트에 유용하게 사용할만한 패턴도 추천해주시면 감사하겠습니다!!

2022-12-15 11:10 UTC, InSeong-So approved these changes
안녕하세요, 예정님! 리뷰가 많이 늦어졌네요🙇‍♂️
기존과 비교해서 코드가 정말 깔끔해졌고, 읽기 편한 네이밍을 많이 차용해주셔서 좋았습니다😊
건강 때문에 힘드셨을텐데 잘 반영해주셨어요. 고생 많았습니다🥹

> 적어주신 리뷰중에 controller에서 view와 긴밀하게 의존한다고 하셔서 이렇게... 저렇게... 해보았는데
최선이 아닌 것 같다는 생각이 듭니다
보시고 혹시 이상한 방향으로 제가 리팩토링 한거면 조금 더 힌트를 주시면 다시 해보겠습니다 😅
- 최선은 아니라도 좋은 스탭이라고 생각되네요! view와 controller가 긴밀하다는 의미는 특정 유저 이벤트(submit 등)나 어떤 비즈니스 로직이 실행될 때 view의 상태를 controller에서 읽고 수정하는 것이 반복되었기 때문이에요. 이는 model의 상태를 변경하고 그에 따라 view가 변경되도록 하는 형태가 더 옳다고 느꼈어요.
- 단순히 querySelector로 DOM 객체를 가져온 변수를 핸들링하기 때문에라고 생각합니다. 따라서 좋은 스탭이라고 생각해요. 다음에는 view, controller, model의 영역과 한계를 촘촘히 가져가보면 더 좋을 것 같아요!
- [간단한 자바스크립트 MVC 예제](https://github.com/taniarascia/mvc)를 남겨드릴게요. 이를 보면 예정님이 다음엔 어떻게 해봐야지, 하는 느낌을 받을 수 있을 것 같아요😊

> 그리고 궁금한 점이 있는데
이렇게 구현해야할 프로젝트를 보시면 인성님은 어떤 사고흐름으로 구조를 설계하시는지 궁금합니다.
'이 프로젝트가 구현해야할 기능은 이러이러하니까 어떠어떠한 패턴을 사용해서 구현해볼까...?'
이렇게 생각하시나요??
- 프로덕션이라면 기획, 디자인이 존재하기 때문에 서비스 아키텍처를 간단하게 그리면서 구현합니다. 현업에서는 React / Vue를 많이 사용하기 때문에 해당 프레임워크(라이브러리)로 구현 가능한 패턴을 많이 고민하늰 편이에요.
- 그러나 사이드 프로젝트라면... 빠른 구현이 필요한 경우 손에 익어서 구현 가능한 패턴을, 시간에 여유가 있다면 조금 더 견고한 앱을 만들기 위해 밑바닥부터 설계하는 등 취사선택하는 편입니다.
- 그러나 자바스크립트로 만드는 간단한 앱이나 러닝에 도움이 되는 무언가를 구현해봐야 한다면 다양한 방법을 많이 시도하는 편이에요. Java에서 유명한 GoF 패턴들을 JavaScript 로 구현해보거나, React/Vue/Angular/Svelte 등이 가진 철학을 JavaScript로 구현해본다거나, RFC 스펙에 추가되거나 새로운 API를 적극적으로 활용해서 구현해보거나, 그 중에 마음에 든 패턴이나 코드를 섞어서 저만의 컨벤션으로 만들거나 말이죠. 이러면서 많은 시행착오와 뿌듯함도 느끼면서 코드를 작성하고 있어요.

누군가 정해주는 괜찮은 선택은 없습니다! 자신이 느끼기에 지난 번 작성한 코드보다 지금이 보기 좋다면, 더 성능이 낫다고 판단되면 그게 그때 당시의 자신이 할 수 있는 최선이자 좋은 선택이라고 생각해요. 어설프게 남들이 잘 작성해 놓은 코드를 써서 구현하는 것보다, 이런 교육의 장에서는 최대한 많이 시도해보고 쌓아올리는 경험이 중요하답니다. 그렇기 때문에 예정님은 좋은 선택을 하셨지 않을까 싶어요.

실무 패턴이라면... 제가 많이 공부했던 여러 사이트를 올려둘게요!
- [[번역] 10가지 소프트웨어 아키텍처 패턴 요약](https://mingrammer.com/translation-10-common-software-architectural-patterns-in-a-nutshell/)
- [유용한 리액트 패턴 5가지](https://velog.io/@dnr6054/%EC%9C%A0%EC%9A%A9%ED%95%9C-%EB%A6%AC%EC%95%A1%ED%8A%B8-%ED%8C%A8%ED%84%B4-5%EA%B0%80%EC%A7%80)
- [모던 웹 앱 디자인 패턴(번역)](https://patterns-dev-kr.github.io/)
- [타입스크립트 디자인 패턴](https://refactoring.guru/ko/design-patterns/command/typescript/example)

부디 도움이 되셨으면 좋겠습니다!
남은 내용은 교육 기간에 꼭 한 번쯤은 페어 프로그래밍을 해봤으면 좋겠네요!

미션 고생하셨습니다🥳

2022-12-15 11:10 UTC, merged