[클린코드 5기 이진호] 로또 미션 STEP1
next-step/js-lotto pull request #230
Opened 2023-08-23 12:10 UTC by Gn0lee

안녕하세요! 로또 미션 첫 PR 요청드립니다!

부족한 점이 많지만 잘 부탁드립니다 🙇🏻‍♂️

한 객체가 너무 많은 역할을 하지 않도록 분리하는데 초점을 맞춰 보았습니다.

그래서 LottoGame 클래스는 여러 클래스들을 이용해서 게임을 진행하는 역할을 하도록 설계했습니다.

설계 후 테스트 코드를 작성해 보려고 하니 이미 다른 클래스에서 테스트한 기능을 사용해서 이것을 테스트 하는 것이 맞는지 그리고 무엇을 테스트해야할지 막막해졌습니다😓

LottoGame 클래스의 설계가 모호하거나 구현이 복잡해서 테스트를 찾는것이 어려운건지 LottoGame의 특성상 그러한것인지 리뷰어님의 의견이 궁금합니다!

계속 고민하다가 너무 오래 붙잡고 있는것 같아서 리뷰요청 드립니다..ㅎㅎ

감사합니다!

2023-08-26 09:16 UTC, yujo11 requested changes
안녕하세요 진호님 리뷰가 늦어져서 죄송합니다 🙇‍♂️🙇‍♂️🙇‍♂️

피드백을 드리는 코멘트 외에도 앞으로 남은 기간 진호님과 로또 미션을 진행하면서 진호님의 코드를 잘 이해하기 위해 궁금한 부분들에 대해서도 질문을 남겼는데요. 텍스트라서 늬앙스가 잘 전달되지 않다보니 때로는 이런 코멘트에 부담을 느끼시는 분들이 많더라구요 😅  혹시나라도 진호님이 부담을 안 느끼셨으면 해서 말씀 드립니다 ㅎㅎ

>설계 후 테스트 코드를 작성해 보려고 하니 이미 다른 클래스에서 테스트한 기능을 사용해서 이것을 테스트 하는 것이 맞는지 그리고 무엇을 테스트해야할지 막막해졌습니다😓

테스트를 실행시켜봤을 때 크게 중복되거나 하는 부분은 찾지 못 했는데요. 지금 미션의 요구사항인 "단위 테스트"에서 "단위(unit)"에 집중해서 지금처럼 각 모듈들의 의존적이지 않은, 독립적인 테스트를 진행하시면 좋을거 같아요. 각 모듈별로 하나하나의 동작들에 대해 검증이 된다면 그것이 곧 전체 플로우에 대한 테스트가 될테니까요!

step1 고생 많으셨습니다 진호님! 👍 👍 👍

2023-08-26 14:46 UTC, Gn0lee commented on src/__test__/LottoGame.spec.js
처음 테스트 코드 구현할때는 구매비용, 수익금 을 인자로 받아서 수익률을 계산하는 메소드를 구현하려고 했는데 어차피 숫자 두개를 나누는 간단한 기능이라 getProfitRatio로 대체하였습니다.

그래서 해당 테스트는 삭제하였습니다.

2023-08-26 14:49 UTC, Gn0lee commented on src/class/Viewer.js
말씀하신대로 View 관련 로직들을 수행하는 목적으로 만든 class 입니다.

컨트롤러 클래스에서 LottoGame으로부터 정보를 받아서 Viewer에게 넘기는 방식으로 구현하다보니 따로 클래스를 만드는 것이 효율적이라 생각했습니다.

그리고 이번 미션에서는 step 이 진행됨에 따라 viewer가 달라지는것 같아서 Viewer.js에 step별 Viewer 클래스를 따로 만들려 했습니다.

2023-08-26 14:55 UTC, Gn0lee commented on src/class/Viewer.js
> +  }
이전 미션때 저도 제시해주신 방법으로 구현을 했었습니다. 그런데 이전 미션의 리뷰어님께서 async await를 남용하는 것 같다는 피드백을 주셔서 위와 같은 방식으로 수정을 했었습니다.

getUserInput에서 readline의 결과물을 사용하는 것이 아닌 단순 promise만 전달하기 때문에 LottoGame에서만 await를 하는것이 저도 맞는것 같아 await를 뺐었습니다.

리뷰어님의 생각은 어떠신지 궁금합니다!

2023-08-26 14:56 UTC, Gn0lee commented on src/class/LottoTicketRules.js
> +      typeof max === "number" && Number.isInteger(max) && max > 0;
지금 다시 보니 코드가 중복되는 것 같고 검사 기준이 일반적이라 util 함수로 바꾸었습니다~

2023-08-26 14:57 UTC, Gn0lee commented on src/class/LottoTicketRules.js
> +      isMaxValidFormat && isMinValidFormat ? min < max : false;
저는 최소값이 최대값보다 커야한다에 집중하다보니 isMinSmallerThanMax라는 변수명이 나온것 같네요ㅎㅎ

좀더 좋은 변수명을 고민하다가 아이디어가 잘 떠오르지 않아서 챗지피티와 논의를 해서 새로운 변수명으로 수정해보았습니다😅

2023-08-26 15:03 UTC, Gn0lee commented on src/class/LottoTicketRules.js
> +        : false;
저는 평소 변수명을 작성할때 영어 문법에 가깝게 작성을 해왔습니다. 그래서 "is range valid?" 라는 문장을 변수명으로 바꾸다보니 isRangeValid로 작성했습니다. 

코멘트를 읽고나니 어떤것이 더 자연스러운지 좀 헷갈리네요..ㅎㅎ

제가 다른 분들의 코드를 많이 안읽어 봐서 그런건가 싶기도 하구요😅

국내에서는 isValidRange같은 변수명을 더 일반적으로 사용하는지 궁금합니다!

2023-08-26 15:05 UTC, Gn0lee commented on src/class/LottoTicketRules.js
> +  constructor(min, max, length) {
개인이 사용하는 로또라면 rule도 변경이 가능해야할 것 같아서 정할수 있게 해보았네요ㅎㅎ

알아봐 주시다니 감사합니다ㅎㅎ

2023-08-26 15:06 UTC, Gn0lee commented on src/class/LottoPrizeRules.js
> +      prizeAmount: 2000000000,
이런 방법이 있는지 처음 알았네요!

처음에 0개수 세느라 힘들었던 기억이 스쳐가네요..😂

2023-08-26 15:08 UTC, Gn0lee commented on src/class/LottoVendor.js
> +      price <= 0 || price === undefined ? this.#defaultPrice : Number(price);
undefined 검사 로직이 꽤 있었는데 이렇게 할 수 있었네요👍🏻

2023-08-26 15:09 UTC, Gn0lee commented on src/class/LottoVendor.js
> +      price <= 0 || price === undefined ? this.#defaultPrice : Number(price);
사용자가 조금 더 편하게 사용할 방법을 생각했는데 피드백을 주는것이 더 좋은 것 같아서 수정하였습니다~!

2023-08-26 15:19 UTC, Gn0lee commented on src/class/LottoPrizeRules.js
> +    }
처음에는 너무 많은 에러를 반환하면 오히려 사용하기가 힘들거라 생각해서 유효하지 않으면 기본값으로 설정했습니다.

그런데 코멘트를 보고 생각해보니 원하는대로 설정이 안되는 것을 더 이상하게 생각할 것 같아서 에러를 반환하는것으로 변경하고 테스트 코드도 수정하였습니다.

그리고 기본값들은 클래스에 포함시키지 않고 같은 파일의 상수로 변경하였습니다.

이유는 외부에서 조회할 필요가 없고 클래스 안에 있으면 접근하여 값을 수정할 수도 있다고 생각했기 때문입니다

2023-08-26 15:20 UTC, Gn0lee commented on src/class/LottoPrizeRules.js
> +          : false,
위의 내용과 비슷하게 undefined일때는 false 처리를 하려고 했습니다.

그런데 undefined가 true와 같지 않으니 다른 곳에서 false처럼 사용할 수 있을 것 같아 해당 코드를 삭제했습니다.

대신 유효성 검사시 undefined 또는 boolean만 허용하도록 수정하였습니다

2023-08-26 15:22 UTC, Gn0lee commented on src/class/LottoTicket.js
> +  }
이 부분도 에러를 반환하도록 수정하였습니다!

2023-08-26 15:23 UTC, Gn0lee commented on src/class/LottoTicket.js
> +  }
랜덤 숫자를 만드는 것을 다른 클래스에서 사용할 일이 없을거라 생각해서 메소드로 만들었습니다.

그런데 클래스의 역할과는 큰 상관이 없는것 같아서 util 로 분리하고 함수명을 좀 더 구체적으로 수정해 보았습니다~

2023-08-26 15:24 UTC, Gn0lee commented on src/class/LottoPrizeCalculator.js
> +    }
Number.isInterger의 매개변수로 number만 허용하는 줄 알았는데 찾아보니 그게 아니었더라구요ㅎㅎ

그래서 불필요한 타입 검사를 삭제하였습니다~

2023-08-27 16:18 UTC, yujo11 commented on src/class/Viewer.js
> +  }
아하 그런 이유가 있었군요 위와 같은 이유로 async/await 를 제외하신 점도 이해는 가네요!

실제 입력을 기다릴 필요가 없다면 제외해도 상관없을거 같습니다!

2023-08-27 16:22 UTC, yujo11 commented on src/class/LottoTicketRules.js
> +        : false;
진호님이 말씀해주시는 내용을 보니 제가 너무 한국어 관점으로만 생각을 했었나 싶기도 하네요 😅

"국내"라고 하기에는 제가 경험한 부분은 극히 일부분일거라 국내에서는 어떻다라고 말씀 드리긴 어렵지만, 제가 그동안 경험했던 코드와 코드베이스들에서는 `isValidRange`라는 이름을 더 많이 봐왔기 때문에 `isRangeValid`라는 변수명이 조금 어색하게 느껴진거 같아요.

이런 변수명에 대한 부분은 컨벤션에 따라 달라질 수 있기 때문에 지금은 이런 의견이 있구나 정도로만 생각하고 넘어가셔도 좋을거 같습니다!

2023-08-27 16:24 UTC, yujo11 approved these changes
안녕하세요 진호님~

코멘트 남긴 부분 꼼꼼하게 확인하고 반영해주셔서 감사합니다!

추가로 질문 주신 부분들에 대해서도 답변 남겼으니 확인해주시면 좋을거 같네요!

step2에서 다시 뵙겠습니다 고생 많으셨습니다! 👍 👍 👍

2023-08-27 16:24 UTC, merged