[클린코드 5기 이정민] 로또 미션 STEP 3
next-step/js-lotto pull request #231
Opened 2023-08-23 18:01 UTC by froggy1014

스텝2에서 사용했던 MVC 로직을 최대한 사용하려 하였습니다.

제가 바닐라 JS가 익숙하지않아서 처음에 익숙하지 않고 처음 세팅하는데 오래 걸렸습니다.

약간 빨리해야겠다는 생각때문에 커밋을 제대로 자르지 못해서.. 난해 하실 수 있겠네요.

아무쪼록 잘 부탁드립니다...

https://froggy1014.github.io/js-lotto/dist

2023-08-25 10:33 UTC, InSeong-So requested changes
step 1, 2, 3에 대한 웹팩 설정을 각각 가져가셨네요!
우선 base 설정 객체를 하나 만들고 각 config 파일을 간소하게 가져가면 어떨까요?
```
- base.config.js
- step1.config.js
- step2.config.js
- step3.config.js
```

```js
// step1.config.js
const baseConfig = require('./base.config.js');

module.exports = {
  ...baseConfig,
  entry: "./src/step1-index.js",
  // 그 외 오버라이드 할 설정
};
```

View 쪽 변경 사항이 크게 없어서 "오!" 했는데요, LottoClerk의 변경사항을 보면서 살짝 탄식했습니다.
관련 내용은 코멘트를 달아 드렸는데... 미션 일정 상 정민님이 해당 코드를 리팩토링하고
영화 리뷰 앱을 만들기까지 정말 시간이 부족할 것 같네요.

어프루브... 하는 게 일정 상 맞겠지만 안일함을 드리는 것 같아 RC를 하고, 추후 여유가 생길 때
재요청 주면 피드백하겠습니다.

긴 미션 수고하셨습니다!👍

2023-08-25 10:33 UTC, InSeong-So commented on src/domain/model/LottoMachine.js
> +  }
생성자 함수에서 많은 역할을 하는 것처럼 보이네요!
메서드로 분리해서 관리하면 좀 더 직관성이 높아질 것 같아요.

2023-08-25 10:33 UTC, InSeong-So commented on src/domain/controller/LottoClerk.js
> +  constructor({ app }) {
지독하게 많은 코드가 밀집되어 있는 클래스 같아요.

특히 내부 필드로 쥐고 있는 View 요소가 너무너무 많은 것 같은데요,
좀 더 View라는 것을 활용해봄은 어떨까 생각해봅니다.

지금 형태는 Controller(+ View)인 느낌이에요.

소위 도메인 로직... 모델의 내부를 직접 수정하는 것도 보이네요.
다음 미션도 진행해야 하니 일정이 빡빡할 수 있겠지만...

정민님이 `LottoClerk` 클래스를 리팩토링하는 시간에 많은 노력을 붓는다면 엄청난 성장을 할 것 같아요.
1. MVC를 역할에 맞게 정리하기: 노드 / 브라우저 환경에서 어떻게 모델을 건드리지 않으면서 컨트롤러의 큰 변경 없이 제어할 지
2. 원시값을 제어하는 방식에 대한 결정
3. 이벤트 핸들링, 스타일링 제어를 각각 아토믹하게 적용하면 어떤 피로가 몰려오고 이를 해결하려면 무엇을 활용해야 하는지
4. 일관된 코드 작성이란 무엇인지

위와 같은 내용은 끊임없이 정민님의 자바스크립트 코드에 고민을 갖게 만들 겁니다. 리팩토링을 한 번, 두 번 진행하면서 본인이 짠 코드를 재검증하면 정말 좋을 것 같아요.

2023-08-26 18:01 UTC, froggy1014 commented
@InSeong-So 

안녕하세요. 

일단 리팩토링을 피드백을 주신대로 리팩토링을 진행해보았습니다. 

일단 View단에서 생성과 동시에 DOM을 제어할 수 있도록 하였고 컨트롤러 단에서
 
model을 던져서 그 정보와 함께 그리도록 만들었습니다. 

그리고 clerk, customer, machine이라는 모델을 각각 만들어줘서 각 역할에 맞는 

정보를 들고, 그리고 모델안에서 데이터를 가공할 수 있는 메소드 또한 추가를 하였습니다. 

예를 들면 customer 모델에서는 profitRate 계산해서 뱉어주는 메소드같은..(?) 

그리고 Controller단에서는 view에서 가져온 요소들에 이벤트를 바인딩하고, 해당 이벤트마다 

실행될 로직들을 넣어놓고, 모델과 뷰에 각 다루도록 만들었는데. 

다름이 아니고, 피드백 주신 내용중에 

`원시값을 제어하는 방식에 대한 결정`과 아토믹한 적용이라면 .. 어떤식인지 잘 그려지지않네요.

감사합니다.

2023-08-29 15:25 UTC, InSeong-So approved these changes
필요한 부분에 대한 개선을 많이 진행해주셨네요 🙌
수고 많으셨습니다!

model, view가 유기적으로 통신하는 구조는 좋습니다.
하지만 여전히 클래스가 알아야 하는 view의 정보가 너무 많네요.
이 부분은 다음 미션에서 더 고민해보고, 아직 확신이 안든다면 제게 디엠을 주시면 좋겠습니다.
함께 이야기해보고 코드를 수정해보면 더 효과가 좋지 않을까 싶어요.

코멘트 주신 내용 중... 이야기를 해보자면,
1. 원시값을 제어하는 방식에 대한 결정: 클래스 인스턴스의 멤버 변수에 대한 이야기입니다. 지나치게 많은 원시값이 멤버 변수로 선언되어 사용되고 있지 않은지 생각되네요.
2. 아토믹한 적용: 소위 마이크로 매니징 같은 것이라 생각하면 좋겠습니다. 각 엘리먼트마나 스타일을 적용하고, 이벤트를 바인딩하고, 이를 핸들링하는 행위보다 이벤트 위임이나 form 등의 브라우저 API를 활용하는 것이 확실히 효율적이라는 것이기 때문이에요.

그럼에도 해소가 되지 않았다면, 꼭 디엠을 주셔서 이야기 함께 해보면 좋겠습니다!
이만 어프루브할게요. 긴 미션 수고 많으셨습니다 🥰

2023-08-29 15:25 UTC, merged