[클린코드 5기 공은채] 로또 미션 STEP 1
next-step/js-lotto pull request #232
Opened 2023-08-25 06:36 UTC by ericagong

## 📄 3분 요약

안녕하세요. 멘토님, 만나뵙게되어 반갑습니다. 가감없는 피드백 부탁드립니다. 많이 배워가겠습니다 🥊

- 이번 로또 미션 [step 1]은 세 가지 목표를 가지고 진행했습니다.
(1) 변경 용이성을 고려한 나만의 설계 사이클 ****정의***(8/26 토요일 링크 첨부 예정)***
(2) **객체 내 응집성이 높고, 객체 간 의존성은 최소화** 할 수 있는 설계 방식 고민
(3) 프로덕트 코드와 테스트 코드의 **리팩토링 우선 고려 사항을 다르게 처리**

- 제 나름대로 복기를 위해 설계 방식 결정 배경을 정리하면서 PR이 길어졌네요. `고민했던 지점 및 연관 질문` 부분과 코드만 읽어주셔도 충분합니다!

## 🙆🏻 설계 방식 결정 배경
💡 모든 설계 방식은 `향후 요구사항 변경 시, 수정 및 확장이 용이한가` 라는 기준 하에 채택 여부를 결정하였습니다.
💡 패턴에 종속되지 않기 위해, `꼭 필요한지 점검` 후 패턴 도입 시 문제가 해결되는 경우만 디자인 패턴을 도입했습니다.

✅ MVC 패턴
- `Domain 로직`을 담당하는 `Model`들과 `UI 로직`을 담당하는 `View`로 분리하고 `Controller`가 중개하도록 처리해, **Domain 로직 변경 or UI 로직 변경이 발생했을 때, 나머지 영역에 영향을 미치지 않도록** 하기 위해 도입.

✅ 전략 패턴
- 현재 요구사항 하에서는 로또는 임의의 랜덤 숫자로만 발급되지만, 향**후 사용자가 원하는 숫자로 로또를 발행할 수도 있다고 생각**하여, 전략 패턴 도입.
    - `IssueStrategy` 를 추상 클래스 형태로 구현하고, `RandomIssueStrategy` , `FixedIssueStrategy` 가 상속하도록 처리.
        - 추상 클래스이므로 new 연산자로 호출 못하도록 처리.
        - 추상 메서드 구현 안하면, 에러 반환하도록 처리.
        
✅ Static Factory method 패턴
- **객체 간 유일한 소통 수단을 메시지로 한정**하고자, 객체 생성 과정을 static factory method 패턴으로 작성해 공용 인터페이스를 제공.
    - 객체 생성 시 호출하는 메서드명에서 전달 인자 개수에 대한 힌트를 얻을 수 있도록, 한 개인 경우 `of`로 두 개 이상인 경우 `from`으로 처리해 가독성 향상.
    
✅ RuntimeError → CustomError 상속 구조
- CustomError가 GlobalError의 에러 메시지 반환 메소드를 상속받아 사용 가능.
- Controller 내의 try-catch 내 에러 처리 지점에서 GlobalError의 에러 메시지 반환 메소드로 간단하게 처리.

✅ Lotto → WinningLotto 상속 구조
- `Lotto` 내 로또 번호 유효성 확인 메소드, 로또 번호 반환 메소드를 재사용하기 위해 상속 구조 도입.

## 🤔 고민했던 지점 및 연관 질문

### ❓단위 테스트 범위와 깊이

- `단위 테스트가 점검해야하는 범위`는 어디까지인지 고민됩니다.
    - 해당 함수에 작성된 모든 코드를 한 줄, 한 줄 검사해야하는지, 원하는 결과값을 반환하는 지 여부만 확인하면 되는지, 함수 내 중요하다고 개발자가 판단한 부분만 검증하면 되는지 판단이 서지 않아 질문드립니다.
    - [관련 코드 질문]
- 각 `단위 테스트에서 담당 해야하는 깊이` 또한 궁금합니다.
    - 만약 createLotteryMachine에서 사용자가 지정한 번호 배열의 로또를 발행해주는 FixedIssueStrategy를 사용한다고 가정해 보겠습니다.
        - createLotteryMachine 내부의 로또 발행 함수인 issueLottosWith에서 사용자가 제공한 배열과 발행한 로또 숫자가 일치하는지 까지를 검증해주어야 하나요?
        - 개인적으로는 FixedIssueStrategy의 getNumber에서 고정 숫자 배열을 반환하는지를 검증하면, issueStrategy에서는 로또 숫자 일치 여부까지 검증해야할 책임은 없는 것 같긴 합니다.
        - 그럼 호출 결과가 배열인지까지만 검증하는 게 createLotteryMachine 테스트 코드의 책임인건가요?

### ❓변수화 의사결정과 선언 위치

- 사소할 수 있지만, 변수 선언 여부와 선언 위치에 대해 질문드리고자 합니다.
    - 정답은 없다는 것을 알지만… 멘토님의 방식도 들어보면서 관점을 넓혀보고 싶어요. 🙏🏻
- 저는 `변수화의 목적 = 데이터 재사용`이라고 생각해서 원래 재사용 하게 될 데이터만 변수로 선언해 왔습니다.
    - 그런데 nextstep을 진행하면서 매직 넘버 사용을 지양하기 위해 변수로 선언할 것을 제안받으면서, **가독성 향상을 위해서도 변수화를 할 수 있겠구나..** 라는 생각을 하게 되었어요.
    - 가독성을 높이기 위해 어떨 때는 변수화를 하기도 하고, 하지 않을 때도 있어서, 프로젝트를 하면서 제 나름의 변수화 기준을 세우기 위해 노력하고 있는 중입니다… 설계에 정답이란 없고, 개발자는 트레이드 오프 간에 선택할 수 밖에 없는 숙명을 받아 들여야 함을 알고 있지만, 트레이드 오프 선택 과정에 도움을 얻고자… 멘토님의 변수 선언 기준은 무엇인지 여쭤보고자합니다.
- 설계란 코드를 어디에 배치할 것이냐 고민하는 작업이기에, 변수의 위치는 어디로 할 것인지도 프로젝트를 하면서 내내 신경이 쓰이더라구요.
    - 사실 스코프와 재사용성만 고려해 처리하면, 해당 변수를 참조하는 곳들이 만나는 가장 가까운 스코프에 선언하면 됨은 자명하죠.
    - 그렇지만 그렇게 쓰면 코드 가독성이 지옥으로 가는 것 같고 어딘가 불편한 느낌이 들어서 이번 프로젝트에서는 그냥 최상위 스코프에 적어주는 방식을 택했습니다 😔…
    - (팀바팀이겠지만..) 실무에서는 변수 위치 설정 시 고려 기준에서 적정 스코프가 먼저인지, 아니면 가독성이 먼저인지 더 많이 쓰이는 경우가 있다면, 알려주시면 고민이 해결될 것 같아요.
- [관련 코드]

### ❓테스트 코드의 스코프

- 테스트 코드를 작성하면서 describe와 it 각 블록에서 사전에 작성한 코드가 서로 영향을 미치게 되어 테스트가 실패하는 몇몇 경우를 마주했어요. 우선, 최대한 영향이 없게 beforeEach나 beforeAll, afterEach, afterAll를 사용하거나, it 별로 코드를 고립시켜 서로 영향을 미치지 않게 조치해두었습니다. 근본적인 해결책은 아닌 것 같아서 질문드립니다.
- [관련 질문]

### ❓서로 다른 역할의 두 객체에서 동일 유효성 검사의 반복

- 현재 코드에서 Lotto와 IssueStrategy에서 동일한 유효성 검사 중복 진행하고 있어요.
    - 처음에는 한 곳에만 있거나 코드를 재사용해도 될 것 같다고 생각했지만, Lotto는 Lottoe대로 자신의 로또 번호를 검증할 책임을 IssueStrategy가 자신이 건네주는 발행 번호를 검증할 책임을 가진다고 생각해서 유효성 검사를 각 객체에서 한 번 씩 진행하고 있어요.
    - 한 번 점검해주시고, 코드 재사용성을 위해 더 나은 방안이 있다면 편하게 제안해주세요. 😄

### ❓데이터 타입 변환의 책임 소재

- View에서 readLine 인터페이스로 읽어온 데이터 타입이 모두 string이기 때문에 도메인 로직의 Model에 건네주기 전, 각각 적절한 데이터 타입으로 변환해 주어야 했어요.
- 현재 코드 상으로는 View에서 전달된 string이 Controller에서 각 데이터 타입으로 변환되어 Model로 전송되는데요. 혹시 이 구조가 적절한지 점검 후 피드백 부탁드리겠습니다! 👊🏻

## 😓 향후 변경 희망 지점

1. step1을 진행하면서, 설계에 너무 시간을 들이다보니, 구현에 진입하는 게 늦어졌어요. 코드 작성을 하면서 설계를 변경하는 것이 TDD의 묘미인데, 제가 놓쳤던 것 같아 반성합니다. 다음부터는 **설계와 구현을 떨어트려 생각하지 않고, 간략히 설계 과정을 거친 뒤, 바로바로 코드를 짜며 설계를 검증하는 식**으로 진행하려 합니다.
2. **while문 사용**이 아쉬워서, step2에서는 변경하고자 합니다.
3. **commit을 기능 단위**로 정리하지 못했네요. 죄송합니다. 다음 step 부터는 반영하도록 하겠습니다.

2023-08-25 06:39 UTC, ericagong commented on __tests__/createResultChecker.test.js
> +          expect(revenuePercentage).toBe(`${expectedRevenuePercentage}%`);
-현재 getSummarizedInfo() 테스트 코드에서는 반환값만 확인하고 있습니다. 
- 단위테스트 범위와 관련하여 getSummarizedInfo() 내부 함수의 호출 여부까지 코드 한 줄 한 줄 모두 테스트해야하는지 질문드립니다.

2023-08-25 06:43 UTC, ericagong commented on src/js/domain/ResultChecker/createResultChecker.js
> +  });
- 변수 선언 위치를 가독성을 고려하여 함수 내 최상위 스코프로 넣어주었습니다만, 사실 getStatistics 함수에서만 사용되는 변수입니다. 
- 해당 변수가 필요한 범위에 맞춰 getStatistics 내부로 넣어주는게 바람직할까요?

2023-08-25 06:46 UTC, ericagong commented on __tests__/createMatchChecker.test.js
> +});
- 이 대목을 하단 코드처럼 작성했을 때, `expect(spyWinningLottoFrom).toBeCalledTimes(1);` 가 3회로 테스트코드의 다른 부분에 영향을 받더라구요. 분명 clearAll도 처리해주었는데, 발생 원인이 대체 무엇인지, jest의 it 구문은 병렬적으로 처리되는건지... 의문이 듭니다.
```jsx
describe("당첨 로또 설정 테스트", () => {
  const { setWinningLotto } = createMatchChecker();
  const spyWinningLottoFrom = jest.spyOn(WinningLotto, "from");
  setWinningLotto([1, 2, 3, 4, 5, 6], 7);
  it("당첨 로또 생성 함수를 1번 호출한다.", () => {
    expect(spyWinningLottoFrom).toBeCalledTimes(1); // 3
  });

  it("당첨 번호와 보너스 번호를 인자로 전달한다.", () => {
    expect(spyWinningLottoFrom).toBeCalledWith([1, 2, 3, 4, 5, 6], 7);
  });
  jest.clearAllMocks();
});
```

2023-08-25 06:50 UTC, ericagong commented on src/js/createLotteryPlatform.js
> +import { convertToArray, convertToMatchingDataType } from "./convertValue.js";
☑️ string -> 적절한 데이터 타입 변환 지점이 Controller가 적절한지 점검 부탁드립니다!

2023-08-25 06:53 UTC, ericagong commented on src/js/domain/Lotto/index.js
> +    this.#isBonusMatch = null;
🖐️ 의도한 `null`이며, 프로그램 전반에서 유지하고 있습니다. 다만, 확장 시 당연하게도 휴먼 에러에 취약해질 수 밖에 없는 지점인 것 같기도 해요. 혹시 현재 방법을 개선할 방법이 있다면 힌트 부탁드립니다!

2023-08-25 06:54 UTC, ericagong commented on src/js/domain/LotteryMachine/RandomIssueStrategy.js
> +  _getNumber() {
🖐️ `protected`로 구현하고 싶은데, 불가능해서 우선 protected 컨벤션을 따랐습니다...

2023-08-25 06:54 UTC, ericagong commented on src/js/domain/LotteryMachine/createLotteryMachine.js
> +    while (maximumPurchaseCount--) {
🖐️ while문을 변경하고 싶은데, 좋은 아이디어가 있다면 공유해주시면 step2에 적극 반영해볼게요. 도전적인거 던져주세요!

2023-08-25 06:58 UTC, ericagong commented on src/js/domain/Lotto/index.js
> +  }
- 만약 FixedIssueStrategy로 사용자가 고정된 Input값을 넣을 수 있게 설계한다면, FixedIssueStrategy에서도 동일한 유효성 검사가 필요했어요. 
- 처음에는 한 곳에만 있거나 코드를 재사용해도 될 것 같다고 생각했지만, Lotto는 Lottoe대로 자신의 로또 번호를 검증할 책임을 FixedIssueStrategy가 자신이 건네주는 발행 번호를 검증할 책임을 가진다고 생각해서 유효성 검사를 각 객체에서 한 번 씩 진행하는게 맞다고 생각했어요. 
    - FixedIssueStrategy를 구현한다고 생각해봤을 때, Lotto/FixedIssueStrategy 각각에서 유효성 검증을 수행하는게 적절한지? 혹시 코드 재사용성을 위해 더 나은 방안이 있는지? 궁금합니다. 😄

2023-08-27 16:07 UTC, InSeong-So requested changes
은채님, 안녕하세요! 리뷰어 소인성입니다🙇‍♂️
은채님이 시도하신 것, 해보고자 한 것이 엄청 많은 것 같아요.
분명 PR 후 읽으면서 피드백을 했는데... 시간이 엄청 흘러버렸네요🥲

기본적으로 코드를 꼼꼼하게 짜시는 분이라, 전체적인 흐름을 잘 이해하면서 어떤 피드백을 해드릴지 고민을 많이 했습니다. 이 부분은 은채님이 PR 본문에 적어주셨듯, `설계와 구현을 떨어트려 생각하지 않고, 간략히 설계 과정을 거친 뒤, 바로바로 코드를 짜며 설계를 검증하는 식`을 고려해보면 좋을 것 같습니다. 주니어-미들급까지  top-down 형식의 접근은 조금 이른 것 같다는 개인적을 생각을 합니다 😅

> 🙆🏻 설계 방식 결정 배경
- 👍 너무 좋습니다. 명확하고 이해하기 쉬워 잘 와닿았어요.
- 관련 코멘트도 몇 개 남겨드렸으니 확인해보면 좋을 것 같습니다.

> ❓단위 테스트 범위와 깊이
- 이게 위에서 언급한 설계와 구현을 떨어뜨려 생각하다보니~ 의 여파이지 않을까 싶습니다. 예를 들어 `A 함수를 실행하면 B가 나온다`라는 아토믹한 함수라면 단순히 테스트해도 문제가 되지 않을 거에요. 정의를 아주 간략하게 가져가서, 순수 함수라고 생각해볼게요.
- 순수 함수는 a, b, c, d ... 여러 개를 실행해도 동일한 입력 = 동일한 출력 이라는 가정을 갖습니다. 그렇다면 순수 함수의 집합은 이미 **잘 실행된다**를 전제로 깔게 돼요. 이 경우 최초 호출 함수만 테스트해도 괜찮은 거죠.
- 반면 내부 함수를 전부 테스트해야 하는 경우, 사이드 이펙트의 관리가 미흡하거나 구현 부분이 어딘가에 의존적이라는 이야기가 돼요. 유틸리티 함수인지, 비즈니스 로직인지 잘 고민해보고 어디서부터 어디까지 테스트할지 결정을 잘 해야 할 것 같습니다.
- 로직의 기능 테스트, e2e 테스트를 어떻게 가져가는지 한 번 찾아보면 좋겠습니다.

> ❓변수화 의사결정과 선언 위치
- 코드를 본 뒤, 이 코멘트를 읽으면서... 은채님의 노력을 충분히 느낄 수 있었습니다. 이렇게 정리할 수 있을 것 같네요.
  - 매직 스트링을 공유하는 상황이라면 특정 파일에 상수를 선언하고 **호출해서** 사용합니다. 그 이유는 상수가 변경될 필요가 있을 때, 하나의 파일만 관리하면 앱 전역에 퍼진 상수를 한 번에 관리할 수 있기 때문입니다.
  - 해당 파일이나 함수에서만 사용되는 변수라면, **스코프 최상단**에 선언해서 사용합니다. 특정 함수가 호출될 때 굳이 상수를 다시 선언해줄 필요가 없는 상황이기 때문입니다.
- 결론을 짓자면 변수/상수라는 단어의 차이를 명확히 하고 어떤 함수 내부에서 상수를 핸들링하기 보다 파일 단위로 관리하는 것이 좋지 않을까 생각합니다.

> ❓서로 다른 역할의 두 객체에서 동일 유효성 검사의 반복
- 은채님의 의도는 이해했으나, 다른 이들을 이를 쉽게 받아들이지 않을 것 같아요. 의도와 상관 없이 중복 코드가 생겼기 때문입니다.
- 전략 패턴이라면, 이러한 중복 코드가 "없어야"합니다. 객체의 전략은 추상화된 상태로 존재하고, 메세지가 되는 객체가 해당 전략을 핸들링하기 때문에 이러한 세부적인 코드가 중복될 필요는 없죠. 이 부분은 좀 더 고민하고, 함께 이야기 해보면 좋겠네요!

> ❓테스트 코드의 스코프
- 코멘트 남겨드렸습니다!

> ❓데이터 타입 변환의 책임 소재
- 기본적으로 Controller가 유저 입력에 대한 데이터 변환에 대한 책임을 질까요...? 쉬운 예로, 프론트에서 사용자 입력이 되었는데 백엔드가 해당 데이터를 그대로 받진 않을 것 같네요!

은채님, 정말 수고 많으셨어요!
한 번 더 피드백을 주고 받는게 좋을 것 같아 RC 드립니다💪

2023-08-27 16:07 UTC, InSeong-So commented on __tests__/createMatchChecker.test.js
> +});
기본적으로 호출된 순서대로 처리됩니다. describe 또한 마찬가지에요.

clearAllMocks 가 호출되는 시점이 describe 내부 스코프라 그런 게 아닐까 싶은데, `afterEach` 코드로 호출해보면 어떨까요?

2023-09-04 05:19 UTC, ericagong commented on src/js/domain/ResultChecker/createResultChecker.js
> +  });
결국 협업 환경에 대한 고려가 선행되어야 한다는 말씀이시군요 👍 
말씀해 주신 사항대로 재사용이 발생하는 경우라면, 별도 파일로 분리처리하겠습니다.

2023-09-04 05:21 UTC, ericagong commented on src/js/createLotteryPlatform.js
> +import { convertToArray, convertToMatchingDataType } from "./convertValue.js";
@InSeong-So 
현재 설계에서 createLotteryPlatform이 컨트롤러 로직을 담당하고 있습니다. 
> 🖐️ string -> 적절한 데이터 타입 변환 지점이 Controller가 적절한지 점검 부탁드립니다!
ㄴ 여기서는 "사용자가 입력한" 데이터의 타입 변경 지점을 여쭤본 거였어요. 
답변이 늦어서 죄송합니다.

2023-09-04 05:24 UTC, ericagong commented on src/js/domain/Lotto/index.js
> +  }
안그래도 사용하면서, 전략 패턴이 아니라 유틸 함수라고 생각하긴 했어요.. ㅎㅎ
현재 동적으로 전략을 변경하는 메소드를 별도로 만들어 두지 않았는데, 이후에 추가할 의도가 있었어서 전략 패턴이라고 칭했던 것 같네요🥲

잘 짚어주셔서 감사합니다.

2023-09-19 04:41 UTC, ericagong commented
## 📄 3분 요약

안녕하세요. 멘토님, 늦어져서 죄송합니다. 지난 번 STEP1 피드백을 기반으로 STEP2까지 진행하여 PR 올립니다.
많이 배워가겠습니다 🥊

- 개인적으로 지난 step1 PR의 설계 방식이 너무 복잡하다고 느꼈습니다. " 객체 지향적인 설계를 하자"는 생각에 매몰되어 객체 지향을 하는 목적에 대해 잊고 있었더라구요. 
- 로또 미션 [step 2]는 `1. 가독성 -> 2. 변경 용이성`을 중심에 두고 코드를 작성했습니다. 
- step1과 달리 이번에는 멘토님이 짚어주신대로, `설계와 구현을 떨어트려 생각하지 않고, 간략히 설계 과정을 거친 뒤, 바로바로 코드를 짜며 설계를 검증하는 식`으로 진행했습니다. 피드백 사이클이 더 짧아져서 좋았습니다.

## 🙆🏻 설계 방식 결정 배경
💡 모든 설계 방식은 `추상화`를 1순위, `변경 시 관리 용이성`을 2순위로 두고 도입 여부를 결정했습니다.
💡 `낮은 결합도`와 `높은 응집도`를 가진 객체를 구현하기 위해 신경썼습니다. 

✅ MVC 패턴
- UI와 도메인 로직의 `변경 빈도가 다르기 때문`에, UI 로직과 도메인 로직을 분리하였습니다. 
- UI/도메인 각각 요구 사항 변경 시 `변경으로 인한 파급 효과의 범위를 제한`하기 위해 Model과 View 사이 Controller가 중개하는 `MVC 패턴`을 도입했습니다.

✅ 목적에 맞는 상속과 합성 관계 사용
- `ValidationError` 하위 `customError`는 `is-a`관계이므로 상속 구조를  도입했습니다.
- `WinningLotto` 클래스에서 `Lotto` 내부 유효성 검사 코드를 재사용하면서도, 의존성을 낮추기 위해 상속 대신 합성 관계를 사용했습니다.

✅ `static factory method` 패턴 
- 다른 객체에서 `new` 연산자를 사용해 직접 구체 클래스에 의존하는 것을 막기 위해, 객체를 생성하는 `of`, `from` static method를 만들어 의존성을 낮췄습니다. 

## 🔨  STEP1 피드백 기반 변경 사항
1. 실행 결과를 예측하기 쉽도록 가능한 한 `순수함수` 형태로 구현했습니다. 
2. 여러 파일에서 공유하는 매직 스트링은 constants 파일로 분리하고, 그 외 특정 모듈 내에서만 사용되는 값은 해당 모듈의 변수로 스코프 최상단에 선언해 주어 함수 호출시마다 재선언되지 않도록 처리하였습니다. 
3. 동일 유효성 검사 반복 부분을 제거했습니다. 
4. 사용자 입력값의 타입 변환 책임 소재는 `View`에 있다고 판단하여, 데이터 변환 로직을 `View`로 이동하였습니다.

## 🤔 고민했던 지점 및 연관 질문
### ❓class가 불필요한 경우
- `createLottoMachine`, `createStatistics`를 일반 모듈로 구현하고, 공용 인터페이스로 사용할 메소드만 return하여 외부에서 접근 가능하게 처리하였습니다. 인스턴스별로 독립적으로 관리해야할 데이터가 없기 때문에, class로 굳이 구현할 필요성이 없다고 판단했기 때문입니다. 
-  위 판단 근거가 적절한가요? 멘토님은 어떠한 경우에 class로 구현하겠다고 판단하시는지 그 기준을 공유해주시면 좋겠습니다. ☺️

2023-09-19 04:44 UTC, ericagong commented on src/js/domain/ResultChecker/errors.js
> +  static MESSAGE = "구매 금액은 0 이상의 양수여야합니다.";
인스턴스마다 message를 별도로 선언할 필요가 없다고 생각해서 `static`으로 관리했습니다.

2023-09-19 04:44 UTC, ericagong commented on src/js/domain/ResultChecker/createRevenueCalculator.js
> +  }
반영해 두겠습니다.

2023-09-19 04:54 UTC, ericagong commented
## 💬 점검 희망 부분
1. 설계 방식이 적절한지, 의문이 드는 부분이 있다면 가감없이 의견 부탁드립니다. 
2. step2 구현 시, 사용자 입력 에러 처리 및 게임 재시작 로직을 `while`문과 `goToFlag`로 구현했는데, 뭔가 아쉽네요. 좀 더 깔끔한 코드로 리팩토링 하고 싶은데 힌트 주시면 좋을 것 같아요.
3. 최대한 의도가 드러나게 메소드/변수명 네이밍했는데 아쉬운 부분이 있으면 의견 주세요.

2023-09-21 05:39 UTC, InSeong-So reviewed
아이고... 은채님 늦어서 정말 죄송합니다!
부랴부랴 점심 시간 이용해서 리뷰해드렸는데... 다시 한 번 죄송해요😭

> 설계 방식이 적절한지, 의문이 드는 부분이 있다면 가감없이 의견 부탁드립니다.
- 코드가 깔끔하고 좋아서 읽기 수월했습니다. 저도 비슷하게 작성하는 경향이 있어서 더 쉽게 읽힌 것 같아요.
- 책임과 역할을 많이 떨어뜨리기 위해 노력하신 게 보입니다! 한 가지 궁금한 것은, 은채님이 생각하는 Error는 MVC 어디에도 위치할 수 있는 것 처럼 보이는데 어떤 의도인지 듣고 싶어요.

> step2 구현 시, 사용자 입력 에러 처리 및 게임 재시작 로직을 while문과 goToFlag로 구현했는데, 뭔가 아쉽네요. 좀 더 깔끔한 코드로 리팩토링 하고 싶은데 힌트 주시면 좋을 것 같아요.

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/models/Lotto/index.js
> +  }
👍 빡빡한 에러 체킹이네요!
여기를 조금 더 발전시켜 보자면, 각 조건문을 메서드로 분리해서 가독성을 높일 수 있겠습니다!

```js
// as-is
if (!Array.isArray(lottoNumbers)) throw new LottoNumbersNotArrayError();

// to-be
isArrayLottoNumbers(lottoNumber);
```

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/models/WinningLotto/index.js
> +  }
사용하신 `form, of...` 형태가 종종 보여요. 모나드 패턴을 적용하고자 하신 것 같은데 맞을까요?

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/models/WinningLotto/index.js
> +        return RANKS.SECOND;
이 조건문이 의미가 있나요..?!

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/models/WinningLotto/errors.js
> +  static MESSAGE = "Lotto 인스턴스 형태가 아닙니다.";
여긴 에러 객체가 모델로 존재하는데... 어디서는 컨트롤러, 어디서는 모델이네요!
은채님이 생각하시는 에러는 어떤 책임과 역할을 갖고 있을까요?

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/models/Rank/index.js
> +  RANK_UPPER_BOUND = RANKS.NONE;
이런 멤버 변수는 변경이 불가능하다라는 제약이 없어서... 가급적이면 상수 처리해주세요!

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/models/LottoMachine/createLottoMachine.js
> +    }
Array.from 이나 Array() 등을 통해서 for문이 아니라 map 구문 등으로 해소할 수 있을 것 같아요.
지속적으로 언급하지만, `스코프 바깥에 있는 변수를 수정`하는 행위는 지양해주면 좋겠습니다!

2023-09-21 05:39 UTC, InSeong-So commented on src/js/domain/controller/LottoPlatform.js
> +        while (goToFlag === 1) {
변수명...이 좀 더 직관적이었으면 좋겠네요!
그리고 반복문 내부에서 goToFlag를 지속적으로 수정하고 비교하는데, 제3자가 이걸 보면 어떤 의도인지 이해하는데 시간이 좀 걸릴 수 있습니다🥲

또 while => while 구문이 있는데, 다른 방법은 없을까요?
while 구문은 가급적 한 번만 사용하기를 권장드립니다. 현재 코드에서도 Array API를 활용하면 충분히 처리할 수 있는 것처럼 보여요!

2023-09-21 05:46 UTC, merged

2023-09-21 05:50 UTC, ericagong commented
확인했습니다! STEP3 PR에 피드백 반영해서 가져오겠습니다 :)

2023-09-21 10:41 UTC, ericagong commented on src/js/domain/models/createStatistics.js
> +    const revenueRate = (totalRevenue / totalPurchased) * 100;
짚어주셔서 감사합니다. 확실히 `Array.prototype.reduce`를 사용하는 편이 사이드 이펙트가 적겠네요. 습관을 들여볼게요!

2023-09-21 10:46 UTC, ericagong commented on src/js/domain/ValidationError.js
> +}
현재 제 설계에 의하면 Validation을 domain logic에서 처리해주고 있어서, 도메인에 포함될 것 같습니다. 
@InSeong-So 혹시 validation 에러 체크는 항상 view에서 수행해주어야 하나요?
개인적으로는 유효성 체크는 프론트에서 한 번 서버에서 또 한 번 중복 체크하는 편이 좋다고 생각합니다. 
step1, 2에서는 프론트의 에러 체크는 구현하지 않고, 서버단의 에러 체크를 구현했습니다. 

멘토님의 피드백에서 궁금한 점이 있습니다. 
피드백의 방향이 (1) domain과 마찬가지로 view 단에도 유효성 체크가 있어야 한다는 것인지, (2) domain에 있는 유효성 체크가 view 단으로 이동해야한다는 것인지 알려 주실 수 있나요?

2023-09-21 10:53 UTC, ericagong commented on src/js/domain/models/Lotto/index.js
> +  }
코드 일관성을 위해 동일한 방식으로 처리하도록 하겠습니다.