[클린코드 6기 이현서] 로또 미션 STEP 1
next-step/js-lotto pull request #267
Opened 2024-05-13 11:34 UTC by Vespucci95

안녕하세요. 리뷰어님!
로또 미션 진행하면서 고민되는 부분들을 정리해보았습니다.
잘 부탁드립니다!

---

### 도메인 영역에 대한 고민

"요구사항은 언제든지 변경될 수 있고, 이에 대응하는 유연한 코드 작성을 위해서는 도메인 영역을 최대한 작게 분리해보고 시작해보자"

위와 같은 생각으로 초기에는 요구사항을 다음과 같이 정리해보았는데요.

```txt
- 상품: 상품으로 분류되는 정보들을 관리 ( 상품명, 가격, 상품 고유번호 등,,)
   - 로또 1매 (상품) : 로또 대한 정보들을 관리
- 로또 기계 : 로또(상품)을 판매하는 기계
- 로또 추첨 기계 : 로또 당첨 번호 추첨과 관련된 작업
```

초기에는 위와 같이 작성하고보니 다음과 같은 역할들도 필요하지 않을까? 하는 생각이 들었습니다.

```txt
- 거래에 대한 행위 (구매, 판매)
- 금액 관리
- 사람(유저)
  - 거래 행위를 일으킬 수 있다.
  - 금액(지갑)을 가진다.
  - 보유한 상품에 대한 정보를 포함
```

이렇게 설정하고보니 초기 요구사항에 비해 너무 과하다는 생각이들어서
최종적으로는 아래와 같이 도메인을 분리하여 진행하게 되었는데요.

```txt
`LottoMachine` : 당첨 로또 번호를 관리
`LottoTicket` : 로또 1매에 대한 정보를 관리
`Product` : 상품으로 분류되는 정보들을 관리
```

미션을 진행하다보니 역할에 맞지않는 메서드들이 붙는다는 느낌이 들었습니다.

사소한 피드백이라도 남겨주시면 고쳐보도록 하겠습니다.
감사합니다! 🙇

2024-05-14 17:29 UTC, yujo11 requested changes
안녕하세요 현서님 만나서 반갑습니다!

로또 미션 함께 하게 된 조윤호입니다 잘 부탁드립니다~~

이번 리뷰를 조금 늦게 드리게 되어 죄송합니다. 🥲 다음 리뷰는 꼭 빠르게 드릴 수 있도록 하겠습니다!

전체적인 코드를 봤을 때 JavaScript를 능숙하게 사용하고 있다는 느낌을 받았습니다. 코드 하나하나 자체의 로직보다는 코드를 보며 궁금한 점들과 구조에 대해 리뷰를 남겼습니다!

요구사항을 분석하며 많은 생각을 하신게 느껴진 코드였는데요. 처음 생각하신 것보다 많은걸 덜어냈음에도 "나중"을 생각하셔서 추가 된 코드들이 많이 보였는데요.

지금 단계에서 필요한 코드들은 무엇인지, 그리고 미래를 대비해 코드를 미리 작성하는 대신 어떤 구조로 작성해야 추후 요구사항들에 따라 유연하게 대처할 수 있을지를 우선적으로 생각해보셔도 좋을거 같습니다!

미션 진행하느라 고생 많으셨습니다 ~~ 👍 👍 👍

2024-05-14 17:29 UTC, yujo11 commented on src/js/domain/LottoMachine.js
> +    const chartMap = new Map([
일반 객체 대신 Map을 사용하신 이유가 있을까요?

2024-05-14 17:29 UTC, yujo11 commented on src/js/domain/LottoMachine.js
> +    this.#winningAmounts = winningAmounts;
winningAmounts도 key-value가 대응될거 같은데 이 친구는 배열로 관리하는 이유가 있을까요?

2024-05-14 17:29 UTC, yujo11 commented on src/js/ConsoleApp.js
> +  lottoMachine.winningNumbers = writeLottoNumbers(winningNumbers);
`Setter`가 존재하는데 바로 값을 할당해주는 이유가 있을까용 ㅎㅎ

2024-05-14 17:29 UTC, yujo11 commented on src/js/domain/LottoMachine.js
> +  }
이렇게 특정 값에 대해 getter와 setter가 모두 존재하고 외부에 열려 있다면 이 필드는 `LottoMachine`에 존재하지 않아도 되는게 아닐까요?

2024-05-14 17:29 UTC, yujo11 commented on src/js/domain/LottoMachine.js
> +    let netReturn = 0;
`net`은 어떤 의미로 쓰인건지 궁금합니다!

2024-05-14 17:29 UTC, yujo11 commented on src/js/domain/LottoMachine.js
> +    let netReturn = 0;
`let`을 사용하지 않고 로직을 작성하는 방법이 있을까요?

2024-05-14 17:29 UTC, yujo11 commented on src/js/domain/LottoTicket.js
LottoTicket이 굉장히 많은 역할을 수행해주고 있는거 같은데요.

만약에 사용자가 6자리 숫자의 로또와 7자리 숫자의 로또, 8자리 숫자의 로또 중 하나를 선택해서 구입하고 결과를 볼 수 있도록 변경해달라는 요청이 들어온다면 이 LottoTicket은 재활용하기 어려워 보이는데요. 이런 요구사항에도 유연하게 대응할 수 있으려면 어떻게 코드를 작성하면 좋을지 한번 같이 고민해보시면 좋을거 같습니다!

2024-05-14 17:29 UTC, yujo11 commented on __tests__/Product.test.js
> +      '%s 는 상품명이 될 수 없다.',
`each`의 활용 좋네용 👍 👍 👍

2024-05-14 17:29 UTC, yujo11 commented on __tests__/Product.test.js
> +      '%s 는 상품명이 될 수 없다.',
decribe과 context를 적절하게 사용하며 어떤 상황에서 어떤 걸 테스트하고 어떤 결과값을 기대하는지 더 명확하게 해주시면 좋을거 같습니다!
ex)
```js
describe('Product 상품명 테스트', () => {
  context('상품명은 N글자 이상 M글자 이하의 텍스트(string)만 등록 가능하다.', () => {
    test('123123가 상품명으로 들어올 경우 XX에러를 Throw 한다.', () => { ... })
  }
})
```

2024-05-16 15:02 UTC, Vespucci95 commented on src/js/view/LottoIO.js
> +    throw TypeError(ERROR_MESSAGE.INVALID_LOTTO_FORMAT);
놓친 부분인 것 같습니다. 여러 곳에서 throw를 던지고 있었는데 try catch 구문을 사용한 부분이 없었네요..!
ConsoleApp.js 에서 전체적으로 모든 에러에 대해서 catch 하도록 변경하였습니다.

저는 전체적으로 처리해보았는데 혹시 더 좋은 방법이나 개선할 방향이 더 있을까요??

2024-05-16 15:08 UTC, Vespucci95 commented on src/js/ConsoleApp.js
> +  lottoMachine.winningNumbers = writeLottoNumbers(winningNumbers);
입력받은 로또 문자열을 배열 형태로 변환하여 전달하면서 나오게된 형태인 것 같습니다..!

- `writeLottoNumbers` 는 LottoUtil.js 의 `convertLottoStringToLottoArray`로 변경해보았습니다!

2024-05-16 15:18 UTC, Vespucci95 commented on src/js/domain/LottoMachine.js
> +    let netReturn = 0;
> `net`은 어떤 의미로 쓰인건지 궁금합니다!
- ROI(투자 대비 수익률)에 대한 수식을 살펴보다가 순수익률을 netReturn 으로 표현한 부분이 있어서 그대로 사용해보았습니다..!
- `netReturn` 이라는 명칭을 모두 `profit` 으로 변경하였습니다

> `let`을 사용하지 않고 로직을 작성하는 방법이 있을까요?
- `LottoMachine`에서 `LottoCalculator`로 메서드 위치를 변경하였습니다.
- 객체로 접근하여 값을 변경하도록 변경해보았습니다!

2024-05-16 15:25 UTC, Vespucci95 commented on __tests__/Product.test.js
> +      '%s 는 상품명이 될 수 없다.',
테스트 코드를 `describe-context-it` 형태를 사용하도록 변경하였습니다.
명확한 표현 명심하도록 하겠습니다! 감사합니다 🙇

2024-05-16 15:26 UTC, Vespucci95 commented on __tests__/Utils.test.js
> +  it('금액에 콤마(,)를 추가합니다.', () => {
테스트 코드 자체로 명세가 된다. 명심하도록 하겠습니다. 감사합니다!

2024-05-16 15:44 UTC, Vespucci95 commented on src/js/domain/LottoTicket.js
`LottoTicket`의 계산식은 `LottoCalculator` 으로 역할을 위임하도록 변경해보았습니다!
추가로 7자리의 로또 8자리의 로또도 표현할 수 있도록 개선해보았습니다..!

2024-05-16 15:56 UTC, Vespucci95 commented
안녕하세요 조윤호 리뷰어님!
꼼꼼하게 리뷰 해주셔서 감사드립니다..! 🙇 
피드백 주신 내용들 포함하여 리뷰 재요청 드립니다!

말씀해주신 내용들을 종합해서 고민해보았을 때 `LottoTicket` `LottoMachine` 에 있던 계산식을
`LottoCalculator`로 역할을 위임하는 방향으로 진행해 보았는데요!
의견 주신 내용들을 잘 포함하였는지는 약간 걱정이 들지만 일부 반영이 되었다고 생각되어 요청드립니다!

감사합니다!

2024-05-18 07:29 UTC, yujo11 approved these changes
안녕하세요 현서님 이번에도 리뷰가 조금 늦어졌네요 🥲

리뷰 꼼꼼하게 확인해주셔서 감사합니다 commit이 꼼꼼하게 나뉘어져 있어 변경 된 내용을 파악하기 좋았습니다! 👍 👍 👍 

이번 step은 여기서 merge하고 다음 step으로 넘어가면 좋을거 같네요!

고생 많으셨습니다 현서님~~ 👍 👍 👍

2024-05-18 07:29 UTC, yujo11 commented on src/js/domain/LottoCalculator.js
> +  ];
배열로 관리하는 대신 객체로 관리되어도 좋을거 같네용

2024-05-18 07:29 UTC, merged