[클린코드 6기 엄지연] 로또 미션 STEP 1
next-step/js-lotto pull request #272
Opened 2024-05-15 17:26 UTC by jjiyeon

안녕하세요 준일님! 
만나서 정말 반갑습니다😊 ..유어 마이 리뷰어..🤩
제가.. 개인 사정으로인해 늦게서야 리뷰를 요청드려요.. 최대한 빠르게 따라갈 수 있도록 노력해보겠습니다🎉

클린코드 정신(?!)을 가지고 훈련하지 않았던터라, 많이 부족합니다. 
먼저, 솔직한 코멘트 감사드려요👍

익숙해지려고 노력하는 것들
- 테스트 코드 작성이 이번 js 6기 스터디 진행하면서 놀랍게도 처음 접하는 부분이라, 먼저 테스트 코드로 쪼개는 과정이 쉽지 않았던것 같아요. 최대한 작은 테스트 단위로 쪼개보는 연습을 해보고 있습니다.
- 어디까지 역할을 분리할지 기준을 어떻게 잡을지 고민입니다. 예를 들면, 컨트롤러라는 레이어를 두고, 금액을 받고 로또를 발행하는 역할을 분리해서 넘겨주는게 좋을까요?   

따듯한 5월을 생각했지만, 날씨가 제법 변덕을 부리네요.
감기 조심하세요!

감사합니다.

2024-05-16 05:25 UTC, JunilHwang requested changes
안녕하세요 지연님!
로또 미션을 함께하게 된 리뷰어 황준일입니다.
앞으로 잘 부탁드려요 😄🙏

...

미션을 급하게 진행한게 눈에 보이네요 🥹

전체적인 리뷰를 종합해보자면 다음과 같습니다.

### 1. 상수로 만들기

지금 단순히 숫자로 쓰이는게 아니라 유의미한 값으로 쓰이는 숫자들이 있는데 이런 것들은 다 상수로 만들어서 관리해주면 어떨까 싶어요!
에러 문구를 만들 때에도 쓰일 수 있을 것 같습니다.

### 2. 바깥에서 조작하는 경우에 대한 고려

지금은 lotto instance도, winningLotto instance도 바깥에서 멤버변수를 조작할 수 있습니다.
그래서 lotto의 instance일 때 lotto의 규칙이 안전하게 지켜지고 있음을 보장할 수 없어요.
객체는 그 객체로 존재하기만 해도 모든 규칙이 보장되어야 하지 않을까요?

예를 들자면,

- String의 instance는 값이 이상할지언정 어쨌든 string이다.
  - `new String(1)`
  - `new String("1")`
  - `new String(true)`
- Number의 instance는 값이 NaN일 수 있으나 어쨌든 number이다.
  - `new Number(1)`
  - `new Number("1")`
  - `new Number(true)`
- Lotto의 instance는 XXXXXXX

여기서 `XXXXXXX` 가 어떻게 정의되면 좋을까요?

---

그리고 질문에 대한 답변을 드리자면,

> 어디까지 역할을 분리할지 기준을 어떻게 잡을지 고민입니다. 예를 들면, 컨트롤러라는 레이어를 두고, 금액을 받고 로또를 발행하는 역할을 분리해서 넘겨주는게 좋을까요?

일단 이 문장을 이해하기가 어렵네요..

"컨트롤러, 인풋, 도메인이 있고 컨트롤러가 인풋 레이어를 통해서 사용하여 금액을 받고 이걸 로또 도메인에 넘겨준다." 로 이해하면 좋을까요?

일단 다른 부분은 몰라도 도메인의 역할을 어디까지 정의할 것인지만 고민해도 충분하다고 생각합니다!
그러다보면 자연스럽게 다른 부분도 어떤 역할을 수행하도록 만드는게 좋을지 인지할 수 있다고 생각해요 ㅎㅎ

역할에 대한 부분은 제가 위에 남긴 내용을 참고해주시면 좋겠습니다.

2024-05-16 05:25 UTC, JunilHwang commented on src/domain/Lotto.js
> +export default Lotto;
```js
const lotto = new Lotto();
lotto.number = 1
```

이러면 어떻게 될까요~?

2024-05-16 05:25 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +  }
앞선 리뷰처럼, winningLotto를 만든 후에 바깥에서 값을 변경해버리면 어떻게 될까요~?

2024-05-16 05:25 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +    });
여기서 쓰이는 3, 4, 5, 6 등은 다 의미가 있는 숫자 같아요!
상수로 만들어서 관리해주면 어떨까요~?

2024-05-16 05:25 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +    });
여기서 쓰이는 문자열 또한 상수로 만들어주면 실수할 확률이 더 적을 것 같네요!

2024-05-16 05:25 UTC, JunilHwang commented on src/constants/number.js
> +export const FIFTH_PRIZE = 5000;
이런 상수들은 domain에 있어야 코드를 읽을 때 더 수월하지 않을까 싶어요!

2024-05-16 05:25 UTC, JunilHwang commented on src/constants/error.js
> +};
잘 보면 여기에도 1, 45, 6 등의 의미있는 숫자들이 쓰이고 있습니다 ㅎㅎ
로또에 대한 요구사항(규칙)이 달라지면 수정할 곳이 많아지겠네요!?

2024-05-16 05:25 UTC, JunilHwang commented on src/util/random.js
> +};
이 함수는 input 자체를 변경해버리고 있어요!
input은 변경하지 않고 output만 만들어내기 위해선 어떻게 해야 좋을까요~?

2024-05-16 05:25 UTC, JunilHwang commented on __tests__/Lotto.test.js
> +  });
"당첨 번호가 1~45 사이의 정수가 아닐 때 오류가 발생한다" 로 표현해야 맞을 것 같아요!

2024-05-16 05:25 UTC, JunilHwang commented on __tests__/Lotto.test.js
> +  test("로또 한장 가격은 1,000원이다", () => {});
여기는 테스트가 없네요!

2024-05-16 05:25 UTC, JunilHwang commented on __tests__/Lotto.test.js
> +});
Lotto에 대한 test인데 WinningLotto 로 검증하고 있어요!
테스트를 분리해야 하지 않을까 싶네요 ㅎㅎ

2024-05-16 05:25 UTC, JunilHwang commented on __tests__/Lotto.test.js
> +  });
보너스 번호는 1 ~ 45 인지 검사하지 않아도 무방할까요~?

2024-05-16 05:25 UTC, JunilHwang commented on src/step-console-index.js
> +    winningLotto.split(",").map(Number),
값이 완전히 잘못된 형태가 아니라면, 일단 수용하는 방식으로 만들어주면 어떨까요~?
가령, `new Number("1")` `new Number(true)` `new String(1)` `new String(true)` 이런 모습들을 상상해보면 좋답니다!

2024-05-16 05:25 UTC, JunilHwang commented on src/step-console-index.js
> +  });
여기에 도메인 로직이 섞여있는 것 같네요!

2024-05-16 05:25 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +    if (arrayNumber.length !== 6) {
6은 이미 정의된 상수라서, 여기에도 적용해주면 좋겠네요!

2024-05-21 15:51 UTC, jjiyeon commented on src/step-console-index.js
> +    winningLotto.split(",").map(Number),
준일님 코멘트 고맙습니다👍
new Number("1")이든 new Number(true)가 Number의 객체이니, 
수용하는 방식으로 만들어 준다면.. 그대로 받은 값을 넘겨주고 필요하다면, winningLotto안에서 값을 사용하기 좋게 확인하라는 의미일까용?

2024-05-21 16:30 UTC, jjiyeon commented
안녕하세요 준일님🤩
리뷰 주신 부분 반영을 해보았습니다..!
또, 더 나은 방향으로 제시해주시면 참고 하겠습니다.

감사합니다

2024-05-21 16:38 UTC, JunilHwang commented on src/step-console-index.js
> +    winningLotto.split(",").map(Number),
"값의 타입과 상관 없이, 값이 winningLotto로 사용하기 합리적이라면 수용해도 좋지 않을까?" 입니다!

2024-05-21 18:12 UTC, JunilHwang approved these changes
안녕하세요 지연님!
피드백 반영 잘 해주셨네요 👏🏻👏🏻

### 1. 유효성 검사 오류

일단 지금 LottoMachine에 유효성 검사에 대한 오류가 존재합니다.
코멘트 남겨놨으니 확인 부탁드려요!
마찬가지로 테스트 코드도 변경되어야할 것 같네요 ㅎㅎ

다르게 생각해보면, 테스트 케이스가 여러개 있었다면 충분히 찾아낼 수 있는 오류였습니다.
그래서 다양한 테스트 케이스를 만들어보는게 중요해요!

### 2. 관심사 중복

로또 번호의 최소/최대값을 Lotto에서도 검사하고, WinningLotto에서도 검사합니다.
그렇다면 이걸 하나로 묶어서 표현할 수 있지 않을까요~?

### 3. Lotto의 책임범위

LottoMachine에서 정렬을 한 다음에 Lotto에게 값을 넘겨주는데요,
다르게 이야기하면 Lotto instance의 값은 정렬된 상태를 보장하지 않는다는 이야기입니다.
이럴 때는 어떻게 해야 좋을까요!?

### 4. WinningLotto의 책임

WinningLotto는
- 로또 번호도 검사하고
- 보너스 번호도 검사하고
- 로또랑 당첨 로또의 갯수도 비교하고
- 우승 상금도 만들어내고

이렇게만 나열해도 무척 많은 일을 하고 있는 것 같지 않나요!?

그래서 일단 이 미션을 진행하면서 최대한 많은 도메인을 만들어보고, 각각의 도메인 한 가지 책임만 가지도록 하는 방식으로 설계해보면 어떨까요?

그 다음에 불필요한 도메인이라고 판단되는 것들을 하나씩 소거하는거죠 ㅎㅎ

저는 오버엔지니어링도 해봐야 적정 범위를 판단할 수 있다고 생각합니다!

---

일단 이번 단계는 여기서 마무리하도록 하겠습니다 ㅎㅎ
다음 단계 진행하면서 참고해주세요!
감사합니다~

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/LottoMachine.js
> +  }
```suggestion
  #generateRandomLotto() {
    const set = new Set();
    while (set.size < 6) {
      const num = randomNumber(MIN_NUMBER, MAX_NUMBER);
      set.add(num);
    }
    
    return new Lotto(set);
  }
```
이런 방법은 어떨까요~?

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/LottoMachine.js
> +  }
즉, Lotto의 instance가 내보내는 값은 "정렬된 상태" 가 보장되어야 합니다.

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/LottoMachine.js
> +    return randomLottoList.map((lotto) => new Lotto(lotto).number);
number를 들춰서 가지고 있는게 어떤 이점이 있을까요?

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/LottoStats.js
> +    });
```suggestion
    const total = Object.entries(this.#stats).reduce((acc, [key, value]) => acc + PRIZE[key].prize * value, 0);
```
이렇게 reduce로 표현할 수도 있답니다!

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +class WinningLotto {
WinningLotto와 Prize는 분리해야 하지 않을까요~? 서로 관심사가 조금 다른 것 같아요!

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +    isBonus: false,
```suggestion
    isBonus: false,
```
`is`라는 prefix는 이런 모습에 더 적합하지 않을까요?

```js
function isBonus(lotto, lottoNumber) {
  return !lotto.contains(lottoNumber)
}
```

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +    }
이건 Lotto에도 있는 검증로직이랍니다 ㅎㅎ
즉, 똑같은 관심사를 다루고 있다는 것이고, 그렇다면 하나의 도메인으로 추출할 수 있지 않을까요~?

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +      const matchCount = lotto.filter((x) => this.number.includes(x)).length;
"lotto와 lotto를 비교해서 같은 값의 갯수를 반환한다"
이건 누구의 역할이라고 볼 수 있을까요?

2024-05-21 18:12 UTC, JunilHwang commented on src/domain/WinningLotto.js
> +    return prizeList;
"당첨 로또"와 "우승 상금"이 같은 관심사라고 볼 수 있을까요?

2024-05-21 18:12 UTC, merged