클린코드 6기 변광진] 로또 미션 STEP 1
next-step/js-lotto pull request #273
Opened 2024-05-15 23:58 UTC by Quska45

리팩토링을 거의 못하고 되는 대로 코딩한 부분이 많아져버렸습니다 ㅠㅠ
코드 후반에는 함수형 코딩을 해보려고 했는데 제대로 작성이 됐는지 궁금하네요.
함수형 프로그래밍으로 작성된, 혹은 흉내내려고 해본 부분이 보이신다면 언급해주시면 감을 잡는데 도움이 될 것 같습니다.

질문

클래스를 작성할 때 필드를 전부 없애버리고 모든 메서드가 순수함수의 형태로 작성되면 함수형 프로그래밍에 가까워 질 것 같은데 제 생각이 맞는지 궁금합니다.
따라서 클래스는 단순히 특정 기능들을 모아 놓은 메서드들의 집합정도로 사용해보면 어떨까 싶은데 어떨까요?
그게 아니라면 함수형 프로그래밍을 위해 어떤 식으로 구조를 작성해가면 좋을지 아이디어를 좀 주시면 감사하겠습니다.

2024-05-17 16:49 UTC, yujo11 requested changes
안녕하세요 광진님! 만나서 반갑습니다!

로또 미션 함께하게 된 리뷰어 조윤호입니다 잘 부탁드려요

먼저 리뷰가 늦어져서 죄송하다는 말씀 드립니다 🥲 다음 번 리뷰는 꼭 빠르게 드릴 수 있도록 하겠습니다 🙇‍♂️

>클래스를 작성할 때 필드를 전부 없애버리고 모든 메서드가 순수함수의 형태로 작성되면 함수형 프로그래밍에 가까워 질 것 같은데 제 생각이 맞는지 궁금합니다.
따라서 클래스는 단순히 특정 기능들을 모아 놓은 메서드들의 집합정도로 사용해보면 어떨까 싶은데 어떨까요?
그게 아니라면 함수형 프로그래밍을 위해 어떤 식으로 구조를 작성해가면 좋을지 아이디어를 좀 주시면 감사하겠습니다.

모든 메서드가 순수함수가 된다면 함수형 프로그래밍의 핵심 개념(입력에만 의존하고 side effect가 존재하지 않는)에 가까워 보이기는 하는데요.

class가 가지고 있는 값들에 의존하지 않고 모든 메서드를 순수함수로 만든다면 굳이 class를 사용할 필요가 없이 객체로만 묶어도 좋을거 같네용 ㅎㅎ

---

미션 진행하느라 고생 많으셨습니다 광진님~~! 👍 👍 👍 

다음번 리뷰는 꼭! 빠르게 드리도록 하겠습니다!!

2024-05-17 16:49 UTC, yujo11 commented on src/js/util.js
> +  if (value <= 0) {
0보다 같거나 작으면 false를 반환해주고 있어 `isPositiveNumber`같은 이름이 더 적절할거 같네요

2024-05-17 16:49 UTC, yujo11 commented on __test__/util.test.js
utl에 대한 테스트도 꼼꼼하게 작성해주신 부분이 좋네요 ㅎㅎ 👍 👍 👍

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +      throw new Error();
throw를 해주는 로직이 전체적으로 많이 보이는데 catch하는 곳을 못 본거 같네요 그대로 앱이 종료되는걸 의도하신걸까요?

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +      throw new Error();
Error가 throw 됐을 때 Error 내용을 보고 어느 지점에서 왜 실패한건지 알 수 있도록 해보시면 더 좋을거 같네용

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +  }
"랜덤한 숫자를 생성한다."라는 로직은 Lotto 라는 도메인과 무관하게 사용할 수 있을거 같아요

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +export default class Lotto {
지금은 6개의 번호를 맞추는 로또만 존재하는데 유저의 선택에 따라 7개, 8개의 번호를 맞추는 로또까지 요구사항으로 추가된다고 한다면 이 Lotto 클래스를 사용할 수 있을까요? 어떻게 구성되면 이런 변경사항에 유연하게 대응할 수 있을지 생각해보셔도 좋을거 같습니다 ㅎㅎ

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +      reward: 2000000000,
큰 숫자(긴 숫자)는 numeric seprator를 사용해보시면 좋을거 같아요!
```suggestion
      reward: 2_000_000_000,
```

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +  #lottoPrice = 1000;
이 `lottoPrice`도 상수처럼 보이는데 위에서 선언한 `LOTTO_NUMBER_COUNT`와는 다른 형식으로 작성되어 있네요

상수는 UPPER_CASE로 작성한다던지 하는 일관성 있는 컨벤션을 적용해보시면 좋을거 같습니다!

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +    }
hitNumberCount가 3일 때 `RANK[5]`에 접근하는 지금 방식을 보면 코드가 한 눈에 들어오지 않고 추후 변경에 대응하기 위해서는 하나하나 인덱스를 맞춰줘야 할거 같은데요(ex - 숫자 10개를 맞출 수 있고, 1등부터 10등까지 당첨 될 수 있다) 

hitNumberCount에 상응하는 객체를 만들어서 사용하거나 다른 방법을 고민해보셔도 좋을거 같습니다!

2024-05-17 16:49 UTC, yujo11 commented on src/js/lotto.js
> +    }
추가로 현재 코드만으로는 "왜" 3개를 맞추면 5등인지는 도메인에 대한 지식이 없는 사람이라면 전혀 알 수가 없을거 같네용

2024-05-17 16:49 UTC, yujo11 commented on __test__/lotto.test.js
> +  test("", () => {
여기는 비워두신 이유가 있을까요?

2024-05-17 16:49 UTC, yujo11 commented on __test__/lotto.test.js
> +    expect(() => lotto.getWinningNumberByString("1,2,3,4,5 ")).toThrow();
`.each()`메서드를 활용해서 개별 테스트로 실행해도 좋을거 같네요!

2024-05-17 16:49 UTC, yujo11 commented on __test__/lotto.test.js
> +  it("1등이 당첨된 경우", () => {
테스트는 개발자의 의도를 테스트 하는 용도로도 쓰이지만 테스트 코드 그 자체가 명세가 되어 작동하는데요.

"어떤 상황"에서 "어떤 동작"을 했을 때 "어떤 결과"를 기대하는지 테스트명에 드러나면 더 좋을거 같습니다! 지금의 테스트명으로는 어떤걸 테스트 했는지 알기가 어려울거 같아요

2024-05-20 03:43 UTC, Quska45 commented on src/js/lotto.js
> +  }
수정 했습니다.

2024-05-20 03:43 UTC, Quska45 commented on src/js/util.js
> +  if (value <= 0) {
수정 했습니다.

2025-02-13 09:53 UTC, closed without merging