[클린코드 6기 원동현] 로또 미션 STEP 3
next-step/js-lotto pull request #288
Opened 2024-05-27 02:07 UTC by Hellol77

안녕하세요~ 리뷰어님!

이번 스텝도 잘 부탁드립니다!

### 고민
1.
이번 스텝에서 가장 고민했던 부분은 lottoController 부분입니다. 작성해보니 lottoController 부분이 상당히 비대해졌습니다. 따라서 다른 폴더에 관심사에 맞게 코드를 분리해보았습니다. 제가 잘 나누었는지 더 좋은 방법이 있을지 리뷰어님이시라면 어떻게 접근 하셨을지 궁금합니다.

### 배포
https://hellol77.github.io/js-lotto/

2024-05-29 16:04 UTC, InSeong-So requested changes
안녕하세요, 동현님!
브라우저 도입되면서 뭔가 많이 정신 없으셨을텐데, 그래도 도메인 설계와 분리를 잘 해두다보니 큰 혼란 없이 개발하신 것 같아요. 수고 많으셨어요!

> 이번 스텝에서 가장 고민했던 부분은 lottoController 부분입니다. 작성해보니 lottoController 부분이 상당히 비대해졌습니다. 따라서 다른 폴더에 관심사에 맞게 코드를 분리해보았습니다. 제가 잘 나누었는지 더 좋은 방법이 있을지 리뷰어님이시라면 어떻게 접근 하셨을지 궁금합니다.
- 제 개인적인 생각으로는 1) view 로직이 혼재되어 있고 2) handler 로직이 중복되는 것 같습니다. 관심사를 고립하려했던 시도는 잘 보였으나 조금 더 고민 포인트가 있다고 봐요.
- controller 코드는 그대로 두면서, view 클래스가 browser > node로 변경되면 어떨까요? 이런 부분을 한 번 생각해보면 더 도움이 되지 않을까 싶습니다.

RC 한 번 드려볼게요! 간단하게 리팩토링 해보시면 좋겠습니다🙇‍♂️

2024-05-30 08:37 UTC, Hellol77 commented on src/js/LottoController.js
> +    });
해당 함수에서 이벤트 객체를 사용하지 않아서 넘겨주지 않았었는데요! 넘겨주는 것이 더 좋은 이유가 함수가 이벤트에 의존하고 있음을 보여주기 위함과 추후에 추가할 수도 있는 기능 때문이 맞을까요??

2024-05-30 09:35 UTC, Hellol77 commented on src/js/LottoController.js
> +    this.#purchasePrice;
습관적으로 작성해버렸네요 😭

2024-06-01 12:25 UTC, InSeong-So commented on src/utils/querySelector.js
> +};
1. 저는 거의 무조건 try-catch를 선택하는 편입니다☺️ 앱의 안정성을 보장할 수 있는 간단하고도 강력한 장치이기 때문이에요. 그리고 간단 로깅, 코드 간결성도 try-catch 구성과 함께 할 수 있기 때문에 선택보다는 함께 가져가는 방향을 고민해보면 좋습니다.
2. 좋은 포인트를 고민하게 되셨네요. 좋습니다👏👏👏 일단 함수의 역할에 따라 다릅니다. lodash 같이 유틸성 함수들은 바깥에서 처리할 수 있게 throw error를 해주는 것이 맞구요, 어떤 비즈니스 로직에서는 최상위에서만 처리하도록 합니다. 즉, 역할과 책임에 따라 그 방식을 각각의 사용처에 맞게 사용해야 해요. 그리고 try-catch를 내부에서 사용한다고 외부에서 사용하지 못하는 것은 아닙니다. 내부에서 catch 부분에 에러가 발생하면, 다시 throw error를 던져도 되니까요. 에러 인스턴스를 새로 생성하느냐, 하지 않느냐로 분기가 나뉠 뿐이죠.

2024-06-01 12:27 UTC, InSeong-So approved these changes
수고 많으셨습니다, 동현님!
마지막 스탭까지 열심히 해주셔서 고마워요👏👏👏
여기서 마무리하고, 남은 기간 다음 영화 미션도 파이팅입니다!

2024-06-01 12:27 UTC, InSeong-So commented on src/utils/querySelector.js
> +};
서로 다른 방식으로 구현을 해보신 것 같아요. `$` 함수를 제 방식대로 조금 고쳐보겠습니다.

```js
const $ = (target) => {
  try {
    if (typeof target !== "string") {
      console.error(ERROR_MESSAGE.NOT_A_STRING);
      return null;
    }
    const element = document.querySelector(target);
    if (!element) {
      console.error(ERROR_MESSAGE.ELEMENT_NOT_FOUND(target));
      return null;
    }
    return element;
  } catch (error) {
    console.error(error.message);
    return null;
  }
};
```

이렇게하면 return 값이 null 또는 element로 제한되기 때문에 코드 안정성이 높아진답니다.

2024-06-01 12:28 UTC, merged