[클린코드 1기 이상우] 로또 미션 STEP 3
next-step/js-lotto pull request #59
Opened 2021-11-28 07:09 UTC by lsw1164

<a href="https://lsw1164.github.io/js-lotto/">🖥️ 데모 링크</a>

<a href="https://github.dev/lsw1164/js-lotto">WEB VSCODE 링크</a>

## ⚙️ Before Started

```
npm install
```

실행은 아래의 커맨드로 할 수 있습니다.

```
npm start
```
## ✔ Test with cypress

```
npm test
```

## 🎯 3단계 요구사항
### 1) 구입 기능
- [x] 소비자는 수동 구매(스스로 구매 번호를 입력)를 할 수 있어야 한다.
- [x] 수동 구매를 위한 input UI는 스스로 구현한다.
- [x] 수동 구매 후 남는 금액이 있다면 자동으로 구매할 수 있어야 한다.
- [x] 🧪 위 기능들이 정상적으로 동작하는지 Cypress를 이용해 테스트한다.
### 2) 배포
- [x] 배포 : 실행 가능한 페이지에 접근할 수 있도록 github page 기능을 이용하고, 해당 링크를 PR과 README에 작성한다.

2021-11-28 10:12 UTC, glassyi commented on cypress/integration/lotto.spec.ts
> +      });
inputManualLottoNumbers 함수와 inputLottoNumbers 함수 두개를 하나로 쓸 수 있을 것 같아서
개인적으로 한번 수정해보았습니다~! 
이건 그냥 참고만 해주시면 될 것 같아요!

``` js
const inputLottoNumbers = (id, numbers: number[], bonus?: number) => {
    cy.get(id2Query(id))
      .find(class2Query("input[type='number']"))
      .each(($input, i, $inputs) => {
        if (i >= winningNumbers.length) return;
        cy.wrap($input).type(`${i === $inputs.length - 1 && bonus ? bonus : numbers[i]}`);
      });
  };
```

2021-11-28 10:24 UTC, glassyi commented on cypress/integration/lotto.spec.ts
> +      validateInput(Id.inputManualLotto, 6);
inputManualLottoNumbers 함수가 직접적인 테스트 데이터를 입력하는 단계라서 그 이후에 assertion 코드가 오는건 자연스럽지만 inputManualLottoNumbers 함수 실행 전에 validateInput 함수를 호출것이 유의미한지 잘 모르겠습니다. 🙂 
혹시 상우 님의 의도가 있으셨다면 말씀 부탁드립니다!

2021-11-28 10:48 UTC, glassyi commented on src/ts/components/App.ts
> +        submitUserLottoList: (lottoList: Lotto[]) =>
``` js
submitUserLottoList = (lottos: Lotto[]) => {
  ...
}
```
props로 넘겨주는 메소드들(submitUserLottoList, submitWinningLotto)을 arrow function으로 쓰면
인자로 넘길 때 좀 더 간략 해질 것 같아요!

``` js
this.inputManualLottoComp = new InputManualLotto(
  $(id2Query(Id.inputManualLotto), this.$target),
  {
    submitUserLottoList: this.submitUserLottoList
  }
);
```

2021-11-28 10:52 UTC, glassyi commented on src/ts/components/InputManualLotto.ts
> +        </div>
모달로 처리하신 ui가 보기 좋았습니다! 👍

2021-11-28 11:29 UTC, glassyi requested changes
상우 님 안녕하세요~ 
step3 코드 작성 하시느라 너무 고생하셨어요! 👍
상우 님이 작성하신 코드를 보면서도 저도 많이 배워 가네요.

제 개인적인 생각 몇가지 코멘트 남깁니다! 
확인 부탁드립니다.

감사합니다 🙂

2021-11-28 11:40 UTC, lsw1164 commented on cypress/integration/lotto.spec.ts
> +      validateInput(Id.inputManualLotto, 6);
invalid한 input 필드 개수 변화를 검증하기 위해 inputManualLottoNumbers 전후로 호출해줬습니다

2021-11-28 12:35 UTC, lsw1164 commented on src/ts/components/App.ts
> +        submitUserLottoList: (lottoList: Lotto[]) =>
아 처음부터 메서드 만들 때 arrow function으로 작성하면 되겠네요 👍

2021-11-29 13:12 UTC, glassyi approved these changes
고생하셨습니다. 다음 미션도 화이팅하세요!

2021-11-29 13:13 UTC, merged