[클린코드 2기 nanuya(윤보미)] 로또 미션 STEP 1
next-step/js-lotto pull request #87
Opened 2022-03-20 05:22 UTC by nanuya

안녕하세요. 클린코드 2기 윤보미입니다.
step1 구매하기 기능 추가했습니다.

최대한 역할을 분리하기 위해 노력했습니다..
잘 부탁드립니다 🙏

### 참고사항
- 모달은 index 에 있던 내용을 그대로 복붙해서 modal.js 로 옮겨놓았습니다! 관련 기능은 스텝 2에서 진행하겠습니다 :)

# 🎯 요구사항

## 구입기능
- [x] 로또 구입 금액을 입력하면, 금액에 해당하는 로또를 발급해야 한다.
- [x] 로또 1장의 가격은 1,000원이다.
- [x] 소비자는 자동 구매를 할 수 있어야 한다.
- [x] 복권 번호는 번호보기 토글 버튼을 클릭하면, 볼 수 있어야 한다.

# 🧪 테스트

## 구입기능
- [x] 최소 구매금액은 1000원이다.
- [x] 금액을 입력하면, 해당 금액만큼 로또를 발급한다.
- [x] 번호보기 토글 버튼을 클릭하면, 복권번호를 볼 수 있다.
- [x] 로또를 새로 발급하면, 로또 번호가 숨겨진다.

## 공부하게 된 내용
- 상태가 변경되면 render 가 실행되도록 `Proxy 와 `Reflection` 을 사용했습니다. [JavaScript Proxy. 근데 이제 Reflect를 곁들인](https://ui.toast.com/weekly-pick/ko_20210413) 
- 처음에는 랜덤으로 45개의 수를 생성하도록 하다보니 중복되는 숫자처리도 그렇고 진행이 어렵더라구요ㅠㅠ 그래서 찾아보니까 랜덤 정렬 시 숫자가 중복되지 않게 난수를 추출하는 [피셔의 예이츠 셔플](https://malonmiming.tistory.com/106)을 따라했습니다.

2022-03-22 16:28 UTC, jho2301 requested changes
안녕하세요 보미님 
리뷰어 전환오입니다
프레임워크를 하나 만들어주신듯하네요!
어떤 방식으로 동작을 할지 흥미롭게 봤던 것 같아요.

좀더 보완했으면 좋겠는 점은 이 기능들을 더 직관적으로 사용을 할 수 있도록 고민을 해보면 어떨까요?

다른 사람과 협업을 했을 때, 보미님이 만들어주신 프로토콜이 상대방에게 잘 받아들여질 수 있을지 관점에서 고민해보시면 좋지 않을까 생각합니다.

고생하셨습니다!

2022-03-22 16:28 UTC, jho2301 commented on src/js/utils/index.js
> +  Array.from({ length: number }, (_, i) => (callback ? callback(i) : i));
Array.from 인자이긴한데 개인적으로는 range에서 콜백이 무슨역할을할지 알기 어렵다는 인상이 들어요. range는 단순 increment 숫자 배열만 반환하고,  callback인자는 사용하는쪽에서 map으로 사용해보도록하면 어떨까요?

2022-03-22 16:28 UTC, jho2301 commented on src/js/views/LottoDetailHeader.js
> +      emit('@toggle', target.checked, $app);
이벤트이름이 일반적인데 좀 더 구체적으로 지어줘도 괜찮지 않나 싶어요

2022-03-22 16:31 UTC, jho2301 commented on src/js/service/lotto.js
> +};
currying을 적극적으로 사용해주고 계신데, 저는 currying이 명시적으로 잘쓰였는가에 대해선 의문으로 남는 것 같아요. either(() => { numbers, size: amount})가 어떤 동작을할지 예측이 굉장히어렵네요..

2022-03-22 16:41 UTC, jho2301 commented on src/js/views/LottoDetailList.js
> +  };
렌더를 하게되면 LottoDetailList의 모든 요소가 새로 바뀌는 것 같은데, 요소가 굉장히 많아지면 성능적으로 많이 아쉬울것같아요

2022-03-22 16:43 UTC, jho2301 commented on src/js/views/MoneyForm.js
> +      const form = convertFormDataToObject($moneyForm);
object와 같은 일반적인 네이밍보다는 실제로 어떤 데이터로 convert되는지 나타내주시면 좋을 것 같아요

2022-03-22 16:51 UTC, jho2301 commented on src/js/views/MoneyForm.js
> +      const form = convertFormDataToObject($moneyForm);
FormData의 메서드들을 그대로 사용해봐도 괜찮지 않을까싶네요

2022-03-22 22:13 UTC, nanuya commented on cypress/integration/lotto.spec.js
> +    });
오 훨씬 이해하기 좋을 것 같아요! 감사합니다!! 테스트코드를 집중해서 잘 만들어보고 싶었는데... 아직 너무 어렵게 느껴지더라구요 ㅠㅠ

2022-03-26 09:02 UTC, nanuya commented on src/js/App.js
> +  );
https://github.com/next-step/js-lotto/pull/87/commits/b2fe5675ee3414d8ee8c1dc4b3dff82bbda93857 이름을 변경해보았습니다..!

2022-03-26 09:04 UTC, nanuya commented on src/js/App.js
> +  eventBinder([moneyForm, lottoDetailHeader]);
이번에는 되도록이면 함수를 사용해서 작성하고 싶었습니다..! 그러다보니 이벤트를 바인딩해주는 시점을 각 컴포넌트 내부에서 만들기가 어려워서 앱까지 끌고오고 되었습니다.. 이 부분은 클래스로 구조 변경하면서 함께 수정하였습니다!

2022-03-26 09:06 UTC, nanuya commented on src/js/dom/index.js
> +  components.forEach((component) => component?.bindEvents?.());
오... 이전 pr 까지 확인해주셨다니.. 정말 감동이고 감사합니다!! 🙇‍♂️🙇‍♂️🙇‍♂️

오히려 이번에 클래스를 사용했어야했는데..ㅠㅠ 제가 잘 못 생각을 했습니다..! 조언해주신대로 추상클래스를 만들어 구조를 변경해보았습니다! 말씀해주신 부분이 적절하게 적용 되었을까요...?? 구조를 아예 변경하다보니 체인지가 많아졌습니다.. 감사합니다!

2022-03-26 09:07 UTC, nanuya commented on src/js/business/lotto.js
> +  const candidates = range(max, (i) => i + ONE);
아하! 제가 과하게 작성했어요^^;; 말씀대로 `0, 1` 로 충분히 명시적이라 다시 수정하였습니다!

2022-03-26 09:08 UTC, nanuya commented on src/js/utils/index.js
> +  Array.from({ length: number }, (_, i) => (callback ? callback(i) : i));
초기화를 같이 해주면 좋을 것 같아 `callback` 을 사용하였는데.. 말씀해주신 것 처럼 `range` 와 `callback` 부분은 분리하는게 역할을 더 명확하게 나누는 것 같습니다!  감사합니다!

2022-03-26 09:09 UTC, nanuya commented on src/js/views/LottoDetailHeader.js
> +      emit('@toggle', target.checked, $app);
`@toggle-numbers` 로 변경하였습니다!

2022-03-26 09:14 UTC, nanuya commented on src/js/service/lotto.js
> +};
넵! 오류 핸들링이 어렵네요... 오류 핸들링을 한번에 처리하고 싶어서 잘 못 된 추상화를 시도했습니다ㅠㅠ 

https://github.com/next-step/js-lotto/pull/87/commits/b8a5906ac8368bbf76e41e59cb40cae0d5f52cea 이런식으로 쪼개고 이름을 변경하였는데.. 더 좋은 방안이 있을까요..?? 

혹시 리뷰어님께서는 평소 오류 핸들링을 어떻게 하시는지 궁금합니다..! 👀

2022-03-26 09:15 UTC, nanuya commented on src/js/store/stateWrapper.js
> +};
아..! `state` 로 이름을 변경하였는데.. 사실 마땅한 이름을 생각하지 못해서 일단 `store`로 두었습니다.. 이런경우 어떤 이름으로 하면 좋을까요..??

2022-03-26 09:15 UTC, nanuya commented on src/js/views/MoneyForm.js
> +      const form = convertFormDataToObject($moneyForm);
`FormData` 메서드를 사용하도록 수정했습니다!

2022-03-26 10:09 UTC, nanuya commented
안녕하세요, 환오리뷰어님! 
이전 pr 까지 확인해주셔서 감사합니다!

사실 이번 코드를 작성할 때 가독성이나 다른 분들과의 협업 관점에서는 생각하지 못 하고 코드를 작성했어요.
리뷰해주신 내용 보면서 또 다른 관점에서 생각하게 되었습니다. 감사합니다.

- 클래스로 리팩토링하면서 `LottoController` 와 `WinningController` 두 가지 컨트롤러를 일부로 작성해보았습니다.
실제로는 `LottoController` 만으로 충분하지만, 만약 애플리케이션이 커지게 되면 `state proxy` 동작부분과 `Controller` 들을 라우팅처리를 어떻게 할 수 있을까 라는 부분을 상상하며 확인해보고 싶어서 오버 엔지니어링이지만 나누어 구현해보았습니다.

- 에러 핸들링을 우아(?)하게 처리해보고 싶은데.. 리뷰어님께서는 어떤 방식으로 핸들링하시는지 궁금합니다~! 

감사합니다.

2022-03-26 11:01 UTC, nanuya commented on src/css/index.css
> +}
`endOfLine` 을 vscode 전역으로 설정하고, `prettier` 에서도 설정했는데.. `css` 파일에서만 계속 eol 이 생기네요 ㅠㅠ

2022-03-27 14:07 UTC, jho2301 approved these changes

2022-03-27 14:07 UTC, merged

2022-03-27 14:08 UTC, jho2301 commented
안녕하세요 보미님 리뷰 반영이 잘된듯 해서 선 어프루브 했어요!
코멘트는 밑에 남기도록 하겠습니다

2022-03-27 14:10 UTC, jho2301 commented on src/css/index.css
> +}
흠 ㅜㅜ. 포매터 세팅에 .css 확장자가 빠져있는지 확인이 필요할 것 같은데 보통 그냥 되는데 이상하네요..

2022-03-27 14:13 UTC, jho2301 commented on src/js/dom/index.js
> +  components.forEach((component) => component?.bindEvents?.());
적절하게 분리가 된듯합니다! 반영해주셔서 감사합니다!!

2022-03-27 14:38 UTC, jho2301 commented
> 에러 핸들링을 우아(?)하게 처리해보고 싶은데.. 리뷰어님께서는 어떤 방식으로 핸들링하시는지 궁금합니다~!

어렵네요!ㅎㅎ 하나로 특정할 수 없는 많은 경우가 있을 것 같아요. 
다만 어느정도 제가 의식적으로 갖고있는 멘탈모델이라고 말씀드릴 수 있을만한 것은, 저는 에러가 있을 때 이 에러를 throw할 지, 해당 지점에서 핸들링할지를 고민해보는 것이에요.

어떤 함수에서 에러를 발생한 즉시 처리한다고 하면, 그 함수를 사용하는 쪽에서는 에러가 핸들링된 채로 사용을 할 수 있을텐데
1. 에러핸들링을 별도로 하지 않아도 되니 에러에 대한 고려없이 함수를 사용할 수 있다는 점
2. 함수를 사용하는 쪽에서 특정한 방식으로 에러를 처리해야할 필요성이 있을 때, 대응을 하기가 어렵다는 점
이렇게 있을듯 하네요.

예를 들어서 validation함수 자체에서 에러가 발생했을 때 alert으로 에러메세지를 띄운다면, alert이 필요하지 않은 경우에는 validation레벨에서 에러를 핸들링한 것이 적절하지 않은 경우가 될 수 있을 것 같아요.

방법적으로는 여러가지 방법이 있을 수 있겠지만, 가장 기본적으로 떠오르는 생각은 위하고 같아요. 
답이 되었는지 모르겠네요 🙇

2022-03-27 14:43 UTC, jho2301 commented on src/js/store/stateWrapper.js
> +};
저라면 요런 코어로직만 모아놓은 폴더를 하나 만들어서 모아둘 것 같긴한데, 
두번째 의견은 사실 그렇게 중요한 것 같진 않아요.
스타일에 관한 부분이라 넘겨주셔도 될 것 같습니다

2022-03-27 14:49 UTC, nanuya commented on src/js/store/stateWrapper.js
> +};
아하! 오..! 코어폴더를 만들어서 두면 좋을것같네요! 아이디어 감사합니다:)