[클린코드 2기 이병현] 로또 미션 STEP1
next-step/js-lotto pull request #90
Opened 2022-03-20 14:37 UTC by Tolluset

2022-03-20 14:49 UTC, Tolluset commented on index.html
> +          <form class="mt-5" data-target="lotto-pay-form">
https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

cypress best practices를 사용하였습니다.

2022-03-20 14:49 UTC, Tolluset commented on index.html
> +              <button type="submit" class="btn btn-cyan">확인</button>
form 버튼으로 사용하기 위해 타입을 `submit`으로 변경하였습니다.

2022-03-20 14:49 UTC, Tolluset commented on index.html
> +          <section class="lotto-paid-section mt-9" data-target="lotto-paid-section">
초기에 구입된 로또 섹션을 보여주지 않기 위해 클래스를 지정하였습니다.

2022-03-20 14:49 UTC, Tolluset commented on package.json
> +    "cypress:dashboard": "npx cypress run --record --key 118c38e2-f22f-4683-9eb7-9bf45c90e4aa"
`cypress.json`에 추가키가 있어야지만 사용할 수 있기에 걱정하지 않으셔도 됩니다.

2022-03-20 14:49 UTC, Tolluset commented on src/css/shared/modules/layout.css
> +}
디스플레이 유틸 추가하였습니다.

2022-03-20 14:49 UTC, Tolluset commented on src/js/index.js
> +  e.preventDefault();
폼의 서브밋 액션시 페이지 리로드를 막기위해 이벤트를 취소하였습니다.

2022-03-20 14:49 UTC, Tolluset commented on src/js/index.js
> +  if (lottos === undefined) $lottoPayForm.reset();
로또 구입이 실패하면 폼을 초기화 시킵니다.

2022-03-20 14:49 UTC, Tolluset commented on src/js/index.js
> +  e.preventDefault();
[Q]

이부분은 클릭 이벤트시 콜백이 두번씩 실행되였기 때문에 이벤트를 취소하였지만, **왜 두번 작동하는지 이해가 되지 않습니다**

2022-03-20 14:49 UTC, Tolluset commented on src/js/models/lotto/index.js
> +    return this.#makeLottoCards(counts);
로또 구입후 구입한 로또 목록을 반환합니다.

2022-03-20 14:49 UTC, Tolluset commented on src/js/models/lotto/index.js
> +      if (result.includes(randomNumber)) continue;
중복된 로또 번호는 추가하지 않습니다.

2022-03-20 14:49 UTC, Tolluset commented on src/js/models/lotto/index.js
> +    return result.sort((a, b) => a - b);
오름차순으로 로또번호를 정렬합니다.

2022-03-21 03:30 UTC, roy-jung requested changes
병현님 안녕하세요, 리뷰어 로이입니다.
코드 잘 봤어요. 간결하게 딱 필요한 코드만으로 잘 작성해 주셨네요.
몇가지 아쉬운점이나 개선이 필요한 부분 코멘트 남겼으니 확인해 보시고
궁금한점이나 이견 있으시면 댓글 남겨주세요 :)

2022-03-21 03:30 UTC, roy-jung commented on src/js/index.js
> +const $lottoPaidCards = document.querySelector('[data-target="lotto-paid-cards"]');
https://docs.cypress.io/guides/references/best-practices#Selecting-Elements
말씀하신 `Best Practice`의 내용을 잘 살펴보시면, css나 js의 변경으로부터 고립된 별개의 선택자를 사용하라는 의미입니다. 즉 test를 위한 선택자와 실제 코드에서의 선택자를 분리시키라는 거예요.
![스크린샷 2022-03-21 오후 12 07 45](https://user-images.githubusercontent.com/6881617/159200293-1727bae9-c18c-4568-a26d-da57951eea13.png)

2022-03-21 03:30 UTC, roy-jung commented on src/js/index.js
> +    .join('');
https://developer.mozilla.org/ko/docs/Web/API/Element/insertAdjacentHTML

2022-03-21 03:30 UTC, roy-jung commented on src/js/index.js
> +  e.preventDefault();
label에 대해 'click'이벤트로 등록하셨는데, click은 버블링이 있는 이벤트입니다.
따라서 input에서 한 번, label에서 또 한 번 이벤트가 호출된 것이죠.
내용은 input의 checked value를 바꿔주는 동작이니, 대신 input에 change 또는 input 이벤트로 바꾸시는게 좋겠어요.

2022-03-21 03:30 UTC, roy-jung commented on src/js/index.js
> +  }
input의 실제 checked 프로퍼티 여부와 무관하게 동작하므로 문제가 있습니다.
예를 들어 콘솔창에서
```js
document.querySelector('input[type=checkbox]').checked = false
```
를 입력해보신 다음, 다시 동작을 수행해 보세요. 누가 이렇게 하겠냐 싶으실 수 있지만, 이렇게 의도적으로 파괴하지 않더라도 어느순간 오작동이 발생할 가능성을 완전히 배제할 수 없습니다. 그런 경우에라도 화면에 보여지는 상태는 서로 동일하게 처리하셔야 해요.

2022-03-21 03:30 UTC, roy-jung commented on src/js/models/lotto/index.js
> +export default Lotto;
static method만 있는 클래스가 클래스로서의 가치가 있을까요? 이런건 그냥 객체로 만들어도 충분하지 않을까요?

2022-03-21 03:30 UTC, roy-jung commented on src/js/models/lotto/index.js
> +    return this.#makeLottoCards(counts);
위에서는 Lotto, 아래에서는 this를 쓰셨네요. 일관성을 지켜주세요.

2022-03-21 09:57 UTC, Tolluset commented on src/js/index.js
> +const $lottoPaidCards = document.querySelector('[data-target="lotto-paid-cards"]');
아 그렇군요... 제가 잘 못 이해했네요.. 감사합니다!!

2022-03-21 09:58 UTC, Tolluset commented on src/js/models/lotto/index.js
> +export default Lotto;
그러네요... 프라이벳을 쓰고 싶은 정도의 의도로 사용했는데, 함수들로만 구성해보겠습니다!

2022-03-21 09:58 UTC, Tolluset commented on src/js/models/lotto/index.js
> +    return this.#makeLottoCards(counts);
빠트렸네요.. 린트를 추가해보겠습니다....

2022-03-21 10:51 UTC, Tolluset commented on src/js/index.js
> +  }
https://github.com/next-step/js-lotto/pull/90/commits/f48a21584f3dc06834a242948d882953b19f62e0

말씀하신대로 동일한 처리를 위해 토글이 아니라 명시적으로(리셋과 같은) 변경시키는 편이 좋네요!

2022-03-21 10:59 UTC, Tolluset commented on src/js/models/lotto/index.js
> +export default Lotto;
https://github.com/next-step/js-lotto/pull/90/commits/d4e58ce9f13b4cabfbd76f519f2cafbfa2192ad9

클래스는 그러면 어떨 때 사용해야 하나요? (캡슐화, 은닉화 등등... 알고는 있는데 정말 필요한 경우를 못 느끼겠습니다....)

제가 클래스를 잘 사용해보지 않아서....

그리고, 코멘트에 달은 커밋처럼 함수들만 나열해서 변경하였는데요, 그러면 함수를 사용하는 경우와 클래스를 사용하는 경우는 어떤 장단점이 있는건가요? 🤔  (함수를 사용, 클래스를 사용)

개인적인 의견으로는 **상태를 가지고 있는 객체** 이 부분이 편리하지 않더라고여... 
객체가 상태를 가지고 있으면 다른곳에서 변경 되는 경우에 알 수가 없고, 버그가 생기는 경우에 관련된 모든 코드들을 알아봐야하는점이 불편하더라고여....

오히려 함수들을 이용하여 그 때 그 때 필요한 값을 얻을 수 있는게 편하게 느껴졌습니다. 클래스를 사용하면 객체의 상태를 관리할 수 있는 점이 좋은건가요?

2022-03-21 11:01 UTC, Tolluset commented on src/js/index.js
> +  e.preventDefault();
https://github.com/next-step/js-lotto/pull/90/commits/33f6a09b8963e34375baff898f0a0d98568d2a2b

클릭조차 필요없어지게 되네요!!! 감사합니다!

이벤트에 대한 이해가 조금 늘은 것 같습니다! (버블링, 캡처 알고 있다고 생각했는데 전혀 모르고 있었네요...)

2022-03-21 11:03 UTC, Tolluset commented on src/js/index.js
> +    .join('');
[Q]

https://github.com/next-step/js-lotto/pull/90/commits/8fa9ece9c62a5107c20f9f36fdc2a53d04a7f1ea

변경해보긴 해봤는데, 이번 경우는 덮어쓰기가 더 간단하다고 느껴졌습니다.

그래도 혹시 `insertAdjacentHTML`만의 어떤 이점이 있는 건가요...? (성능상이라던지, 보안이라던지...)

2022-03-21 11:04 UTC, Tolluset commented
질문은 아래의 두개가 있습니다!! 리뷰 감사합니다!

https://github.com/next-step/js-lotto/pull/90#discussion_r830982292

https://github.com/next-step/js-lotto/pull/90#discussion_r830978351

2022-03-21 11:07 UTC, Tolluset commented on src/js/index.js
> +const $lottoPaidCards = document.querySelector('[data-target="lotto-paid-cards"]');
https://github.com/next-step/js-lotto/pull/90/commits/56c897643c419c3d18c544adc2a7e06fb0691d5f

변경해두니까 마음이 편하네요 😄

2022-03-21 14:34 UTC, roy-jung commented on src/js/index.js
> +  }
제 생각에는 toggle이라는 단어는 그대로 두되, flag를 각 메서드에 전달하는 방식이 어떨까 합니다.
```js
const toggleLottoPaidCards = (show = false) => {
  ...
  toggleLottoPaidCardsLayout(show)
}
const toggleLottoPaidCardsLayout = (show = false) => {
  $lottoPaidCards.classList.toggle('flex-col', show);
  ...
}
```

2022-03-21 14:42 UTC, roy-jung commented on src/js/models/lotto/index.js
> +export default Lotto;
클래스는 new 연산자를 써서 인스턴스를 생성하는 목적이 메인이 되는 것이 일반적입니다.
클래스 자신을 객체처럼 (static) 활용하기만 하고, 인스턴스를 생성하지는 않는다면 이는 (추상적인 개념의) 클래스가 아니라, (구체적으로 실존하는) 객체일 뿐이에요.
함수와 클래스는 애초에 그 목적 자체가 다르니 장단점을 비교하는건 무의미해 보입니다. 함수를 인스턴스를 생성하는 목적으로 쓰고자 한다면 그보다는 클래스를 쓰는 편이 낫겠고, 반대로 클래스를 함수처럼 쓰고자 한다면 그보다는 함수를 쓰는 편이 낫겠죠 ㅎㅎ

상태는 별개의 얘기입니다. 클래스 인스턴스만이 상태를 가질 수 있는건 아니고, 함수의 클로저를 활용한 객체도 얼마든지 내부상태를 가질 수 있습니다.

2022-03-21 14:45 UTC, roy-jung commented on src/js/index.js
> +  }
```js
$lottoPaidCards.replaceChildren()
```
으로 간단히 처리할 수 있어요.

2022-03-21 15:41 UTC, Tolluset commented on src/js/index.js
> +    .join('');
>  이미 사용중인 element 는 다시 파싱하지 않는다. 그러므로 element 안에 존재하는 element를 건드리지 않는다. (innerHtml은 과 좀 다름). innerHtml보다 작업이 덜 드므로 빠르다.

이 부분이군여! 감사합니다!!! 👍

2022-03-21 15:46 UTC, Tolluset commented on src/js/models/lotto/index.js
> +export default Lotto;
그렇군여.. 추상적으로 제공할 것인가 부분이 있네요...

인스턴스를 생성하는 목적, 그렇군여..!

이 부분은 좀 더 많은 경험, 공부를 해봐야 알 것 같습니다.. 아직은 클래스로 처리해야 하는 문제인지 함수로 해야하는 문제인지 기준이 어렵게 느껴지네요 😢

2022-03-22 00:58 UTC, roy-jung commented on src/js/models/lotto/index.js
> +export default Lotto;
넵! 어떤 미션이든 정답은 없습니다 ㅎㅎ

2022-03-22 00:59 UTC, roy-jung commented on src/js/index.js
> +  }
메소드는 워낙 많으니 천천히 하나씩 늘려가시면 됩니다. 중요한 것도 아니니 :)

2022-03-22 01:03 UTC, roy-jung approved these changes
피드백 반영해주신것 확인했습니다.
전체적으로 필요한 코드를 간결하게 구현하셔서 읽기에 수월했네요.
추가로 코멘트 남긴 것은 step2때 이어서 진행하셔도 되니
이번 스텝은 여기서 승인 및 머지하도록 할게요. 다음 스텝때 봬요 :)

2022-03-22 01:03 UTC, merged